{
  "sha1": "hvnz71eya5lebs76cvqgw1n0mox27iq",
  "insertion": {
    "when": "2024-06-03T18:59:30.064Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
group queue {
 rectangle color=green position=30,30 dimension=20,5
 rectangle color=green position=30,34 dimension=15,5
 rectangle color=green position=30,38 dimension=10,5
}
queue position=0,0 rotation=10
@endcute
