{
  "sha1": "omf6rq5c4ojoyy4qnint3wpm946466t",
  "insertion": {
    "when": "2024-06-04T17:28:40.005Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2

!definelong AUTHEN(x,y)
x -> y : hello
y -> x : ok
!enddefinelong
AUTHEN(Bob1,Alice)

@enduml
