{
  "sha1": "fqaxkv74mcv7dpbondjdgyywfdi70bl",
  "insertion": {
    "when": "2024-06-01T09:03:06.521Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'skinparam dpi 700
A -> B
note right : this is right of the user B

A ->] : this goes to the very right of the diagram
note right : How can this note be right of the arrow ?

A -x B : hello
A x-- B : hello ?
A ->x B : hello
A x<-- B : hello ?
@enduml
