{
  "sha1": "mvafejxcce9ol7fiio7uabhmrdm5m27",
  "insertion": {
    "when": "2024-06-03T18:59:35.735Z",
    "url": "https://forum.plantuml.net/15983/element-line-style-not-applied-in-usecase-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
usecase c #line.dashed
@enduml
