{
  "sha1": "mvzhsgvbs7kg3s9sq9xfhfl0qmdnaud",
  "insertion": {
    "when": "2024-06-03T18:59:35.777Z",
    "url": "https://forum.plantuml.net/16588/style-allow-all-style-for-mainframe",
    "user": "plantuml@gmail.com"
  }
}
@startuml

legend
The legend
end legend

participant a
a --> bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb 

@enduml
