{
  "sha1": "heu8a4i7u7nshscnbj5b91g9gwiyupp",
  "insertion": {
    "when": "2024-06-03T18:59:29.517Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
<style>
.Foo {
  BackgroundColor red
}
.Foo2 {
  BackgroundColor #FFFF00
  FontColor blue
  FontSize 8
}
</style>
(*) --> "Activity 1" <<Foo>>
--> "this is long
on 2 lines" <<Foo2>>
@enduml
