{
  "sha1": "e0llyqtpv42wl53re6oimsnze83z3bc",
  "insertion": {
    "when": "2026-02-18T22:26:04.229Z",
    "url": "https://github.com/plantuml/plantuml/issues/1492",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Bob -> Alice : hello
note left Bob : left
& note right Bob : right
@enduml
