{
  "sha1": "e0r5o24s4ypak7zuvgp5e8qu9p4a4dn",
  "insertion": {
    "when": "2024-06-01T09:03:03.698Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
(*) --> "Activity 1" #red
--> "Other test
   on several
   lines" #00FF00
   
if "" then
  --> "Dummy" #orange
endif
@enduml
