{
  "sha1": "7hn69jpvy5jhd5h2vp1gqy077ntgvms",
  "insertion": {
    "when": "2024-05-30T20:48:21.206Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
group queue {
 stick color=green position=30,30 dimension=20,5
 stick color=green position=30,34 dimension=15,5
 stick color=green position=30,38 dimension=10,5
}
queue position=0,0 rotation=10
@endcute
