{
  "sha1": "7hr129j5kdmp8rh61qq6ndiimj8myvi",
  "insertion": {
    "when": "2024-05-30T20:48:21.210Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
split
	  split
	    :A;
	    detach
	  split again
	    :B;
	    detach
	  end split
split again
 :C;
 detach
end split
:toto1;
 detach
:toto2;
@enduml
