{
  "sha1": "wkk6uf24i41nzdhjalbq54m6ux59ak",
  "insertion": {
    "when": "2026-02-18T22:25:27.063Z",
    "url": "https://github.com/plantuml/plantuml/issues/2536",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class User
class Item
User "owner which is very long"/1 -- "0..n"/items Item
@enduml
