{
  "sha1": "ajjs12y3jqqdmx6u2l6z4devqxc8i5n",
  "insertion": {
    "when": "2024-05-30T20:48:21.890Z",
    "url": "https://github.com/plantuml/plantuml/issues/309",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
repeat :foo as starting label;
  :read data;
  :generate diagrams;<<output>>
  backward :This is backward;
repeat while (more data?)
end
@enduml
