{
  "sha1": "c0scy949hku4iyu0bzmal9lyrs0wgyh",
  "insertion": {
    "when": "2024-06-01T09:03:00.754Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam reverseColor RBG
start
:foo1;
#red:foo2;
#AliceBlue:while (data available?)
  :read data;
  :generate diagrams;
endwhile
#blue:if (graphviz installed?) then (yes)
  :process all%n()diagrams;
else (no)
  :process only
  __sequence__ and __activity__ diagrams;
endif
#DarkCyan:repeat
  :read data;
  :generate diagrams;
repeat while (more data?)
stop
@enduml
