{
  "sha1": "fc06w0ahr86fmuyg8x7coe9od3nzqvj",
  "insertion": {
    "when": "2024-06-01T09:03:05.928Z",
    "url": "https://github.com/plantuml/plantuml/issues/337",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    namespace java.util {
        abstract class AbstractSet<E>
        
        namespace function {
            interface Supplier<T> {
                {abstract} +get(): T
            }
        }
    }
@enduml
