{
  "sha1": "4ghcxt364zv5c5z93kjyy2eu4o2co3d",
  "insertion": {
    "when": "2024-05-30T20:48:20.486Z",
    "url": "https://forum.plantuml.net/11892/scale-not-honoured-in-gantt-chart",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
scale 0.5
[Prototype design] lasts 15 days
[Test prototype] lasts 10 days

Project starts 2020-07-01
[Prototype design] starts 2020-07-01
[Test prototype] starts 2020-07-16
@endgantt
