{
  "sha1": "6q383p6i5in8b274ifikrv92jghlzmu",
  "insertion": {
    "when": "2024-05-30T20:48:21.022Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

class Dummy
Dummy --> Foo : A link
note on link #red;line.dotted:blue;text:white : note that is red

Dummy --> Foo2 #blue;text:red : Another link
note right on link #blue;line:yellow;text:purple
	this is my note on right link
	and in blue
end note


@enduml
