{
  "sha1": "swzuvl2oxiucw5vipid05a0q1fedms0",
  "insertion": {
    "when": "2024-06-04T17:28:45.569Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:state1;
partition use_case {
repeat
:state0;
repeat while(wait for call) -> callback failed
->callback ok;
}
:state2;
end
@enduml
