{
  "sha1": "xp4dz2wpjlk0tthf3e3zy190gjb4zk",
  "insertion": {
    "when": "2024-06-04T17:28:46.951Z",
    "url": "http://forum.plantuml.net/7944/is-it-possible-to-run-only-the-preprocessor?show=7945#a7945",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package MyPackage {

component MyComponent [[http://www.google.com]] [
This one has
a very long
description
] 

}
@enduml
