{
  "sha1": "r58l5cvtdwjfrp1ytsa0bsxcbm95d2j",
  "insertion": {
    "when": "2024-06-04T17:28:43.344Z",
    "url": "http://wiki.plantuml.net/site/preprocessing-json",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!$partlen=2
!$data={"partlen": "2", "participants" :[
{"name": "XYZ" ,"as": "xyz"},
{"name": "RST" ,"as": "rst"},
{"name": "UVW" ,"as": "uvw"}
]
}
!$partlen=$data.partlen
!$i=0
   
:a;
:$i;
:$partlen;
:$data.participants[$i].name as $data.participants[$i].as;
:$data.participants[0].name as $data.participants[0].as;
:$data.participants[1].name as $data.participants[1].as;
:$data.participants[2].name as $data.participants[2].as;
:b;
@enduml
