{
  "sha1": "43yjqrau0wgrcty8v983v0sb3aee4ja",
  "insertion": {
    "when": "2024-05-30T20:48:20.418Z",
    "url": "https://forum.plantuml.net/17885/decimal-time-values-not-accepted-in-parameters-procedures",
    "user": "plantuml@gmail.com"
  }
}
@startuml
binary "enable" as EN

@0 as :start
@5.5 as :en_high 
@10 as :en_low
@:en_high-2 as :en_highMinus2

@:start
EN is low

@:en_high+1
EN is high

@10.5
EN is low

@enduml
