{
  "sha1": "7d16kze2f32lr9fjf8mphtg53e46lya",
  "insertion": {
    "when": "2024-05-30T20:48:21.170Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title essai
actor Alice
actor Bob
Alice -> Bob : coucou1
Alice -> Bob : coucou2
Alice -> Bob : coucou3
Alice -> Bob : coucou4
Alice -> Bob : coucou5
Alice -> Bob : coucou6
Alice -> Bob : coucou7
Alice -> Bob : coucou8
@enduml
