{
  "sha1": "lyeyx4mx9xm297heepeqq14h9dqg30x",
  "insertion": {
    "when": "2024-06-03T18:59:34.665Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

Activate SerialManager
Activate InputStream
Activate ByteBuffer

group PURGE RX
    [-> SerialManager: purgeRx()
        SerialManager -> ByteBuffer : clear()
        ...
        SerialManager <-- ByteBuffer
    [<-- SerialManager: purgeRx()
end

newpage

group RECEPTION DONNEES
    [-> SerialManager : A()
        SerialManager -> ByteBuffer : compact()
        SerialManager <-- ByteBuffer
    [<-- SerialManager : A()
end

@enduml
