{
  "sha1": "1cinv2gidn0bggxxrnrky6x53bu3r7k",
  "insertion": {
    "when": "2024-05-25T14:26:51.435Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
allow_mixing
class foo1{
+ int Temp
}
rectangle "foo2" {
rectangle "foo3"
}
foo2 --> foo1::Temp
@enduml
