{
  "sha1": "asxlc37gz4vmo3vnze8epgnqv35mfqs",
  "insertion": {
    "when": "2024-05-30T20:48:21.946Z",
    "url": "https://forum.plantuml.net/13886/plantuml-generating-invalid-example-plantuml-written-beside",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Bob -> Alice : hello
alt [[https://www.plantuml.com]]
note over Bob: [[https://www.google.com]]
else [[https://www.plantuml.com]]
note over Bob: [[https://www.google.com]]
end
@enduml
