{
  "sha1": "p00a0f0x5k3tvy92k3jw4x7xg54fyv1",
  "insertion": {
    "when": "2024-06-04T17:28:40.506Z",
    "url": "https://github.com/plantuml/plantuml/issues/230",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
mainframe This is a frame
Alice->Bob : Hello
@enduml
