{
  "sha1": "il01vbunsoztps5vbr76h9pxmto8qs7",
  "insertion": {
    "when": "2025-09-25T19:50:52.714Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
* R
    * Line 1
        * L11
        * L12
    * Line 2
        * L21
        * L22
@endwbs
