{
  "sha1": "a42va3i6swrfk07uv5q9tj6vrwqkqww",
  "insertion": {
    "when": "2024-05-30T20:48:21.710Z",
    "url": "https://github.com/plantuml/plantuml/issues/1423",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!theme cerulean
<style>
.continuous {
  FontColor red
}
</style>

:test;
:action1; <<continuous>>
:action2; <<continuous>>
:action3; <<continuous>>

@enduml
