{
  "sha1": "qgnayu1zl6kcxiw7qe2t8ug4qt9uvs8",
  "insertion": {
    "when": "2024-06-04T17:28:42.417Z",
    "url": "https://forum.plantuml.net/16307/is-there-a-way-to-have-more-than-one-character-in-connectors",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:foo2;
("Basic routine")
end

("Basic routine")
:foo5;
end

@enduml
