{
  "sha1": "d1a8knt41cmypngbx6omnkhvu7y0ohv",
  "insertion": {
    "when": "2024-06-01T09:03:02.376Z",
    "url": "https://forum.plantuml.net/6699/please-provide-macros-insert-current-number-total-number-pages?show=10976#c10976",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
footer This is %page% of %lastpage%
Alice --> Bob : A1
newpage
Alice --> Bob : A2
newpage
Alice --> Bob : A3
newpage
Alice --> Bob : A4
@enduml
