{
  "sha1": "d1p9uydpp3ocaao356lbri4erxw5119",
  "insertion": {
    "when": "2024-06-01T09:03:02.410Z",
    "url": "http://forum.plantuml.net/8598/skinparam-rectangle-not-working-in-activity-beta",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam  rectangle {
    RoundCorner 25
    BackgroundColor red
    BorderColor blue
}
hide stereotype
rectangle outerAction {
:innerAction;
}
@enduml
