{
  "sha1": "hb4vpaax7snyitg04ifm85z27la77m6",
  "insertion": {
    "when": "2024-06-03T18:59:29.390Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

(*) --> "this activity
	is <b>very</b> long
 and defined on several lines
that contains many <i>text</i>"

--> "Another activity"

-left-> "This one"

@enduml
