{
  "sha1": "oc88s0dr1vey704kjw5v8y1ck9qstwk",
  "insertion": {
    "when": "2024-06-06T17:24:18.694Z",
    "url": "https://github.com/plantuml/plantuml/pull/1790",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
'Issue #1494
'skinparam style strictuml

Actor Mallory as m
Actor Bob as b
Actor Alice as a

activate b
b ->> a --++ : Hi Alice!
a ->> b --++ : Bye Bob!

b ->> a ++ : Bye Alice!
& b ->> m --++ : Bye Alice!

deactivate a
deactivate m
@enduml
