{
  "sha1": "jc8dp7gndrxb2pw8v8mvan62w9g3qkz",
  "insertion": {
    "when": "2024-06-03T18:59:31.719Z",
    "url": "https://github.com/plantuml/plantuml/issues/1465#issuecomment-1597648143",
    "user": "plantuml@gmail.com"
  }
}
@startuml
binary "A" as a
@0
a is low
note top of a : note top
@1
a is high
@2
a is low
note bottom of a : note bottom
@enduml
