{
  "sha1": "npdcardeve7i28i3zc9of2mf7l5g6pj",
  "insertion": {
    "when": "2024-06-04T17:28:38.901Z",
    "user": "plantuml@gmail.com"
  }
}
@startregex
(\[\[[%s]*[%g]([^%g]+)[%g](?:[%s]*\{([^{}]*)\})?(?:[%s]([^%s\{\}\[\]][^\[\]]*))?[%s]*\]\]|\[\[[%s]*\{(.*)\}[%s]*\]\]|\[\[[%s]*\{([^{}]*)\}[%s]*([^\[%s\{\}\[\]][^\[\]]*)[%s]*\]\]|\[\[[%s]*([^\s%g{}\[\]]+?)[%s]*\{(.+)\}[%s]*\]\]|\[\[[%s]*([^%s%g\[\]]+?)(?:[%s]*\{([^{}]*)\})?(?:[%s]([^%s\{\}\[\]][^\[\]]*))?[%s]*\]\])?
@endregex
