{
  "sha1": "8h7u1ydnyhq057yxb5nev29jpvpj61g",
  "insertion": {
    "when": "2024-05-30T20:48:21.766Z",
    "url": "https://forum.plantuml.net/16912/backward-in-repeat-loop-not-possible-to-set-color",
    "user": "plantuml@gmail.com"
  }
}
@startuml

repeat  
:Review Activity; <<task>> <<#LightGreen>>

backward  :Rework; <<task>>

repeat while (active Remarks) is (Yes) not (No)

@enduml
