{
  "sha1": "qjkmi2y0ryb85o1skxdcbu2k73vdu4q",
  "insertion": {
    "when": "2024-06-04T17:28:42.502Z",
    "url": "http://forum.plantuml.net/8264/formatting-state-actions-sometimes-doesnt-work",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state Active {
Active: entry / HAL_CAN_Init(...) %n()%tab() HAL_CAN_Start(...) %n()%tab() HAL_CAN_ActivateNotification(...)
Active: exit / HAL_CAN_DeactivateNotification(...) %n()%tab() HAL_CAN_Stop(...) %n()%tab() HAL_CAN_DeInit(...)
Active: SEND_MSG (msg, mailbox) / \
%n()%tab() HAL_CAN_AbortTxRequest(...) \
%n()%tab() HAL_CAN_AddTxMessage(...)
Active: RX_MSG (msg) / \
}
@enduml
