{
  "sha1": "qjkvnabzcbt07j937a66t02vpdw2iwb",
  "insertion": {
    "when": "2024-06-04T17:28:42.509Z",
    "url": "http://forum.plantuml.net/8751/inconsistent-placements-legend-title-across-diagram-types",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title my title
legend top
  This is the legend
  on several lines
end legend

Alice -> Bob : hello

@enduml
