https://github.com/plantuml/plantuml/issues/2518
@startuml
+class A {
}
@enduml

https://github.com/plantuml/plantuml/issues/2518
@startuml
+ class A {
}
@enduml

https://github.com/plantuml/plantuml/issues/2518
@startuml
+class A {}
@enduml

https://github.com/plantuml/plantuml/issues/2518
@startuml
+ class A {}
@enduml

https://github.com/plantuml/plantuml/issues/2518
@startuml
+class A
@enduml

https://github.com/plantuml/plantuml/issues/2518
@startuml
+ class A
@enduml
