https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap
@startmindmap
*  
** Not empty
** 
@endmindmap

https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap
@startmindmap
*  
**_ Not empty
**_ 
@endmindmap

https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap
@startmindmap
+  
++ Not empty
++ 
@endmindmap

https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap
@startmindmap
+  
++_ Not empty
++_ 
@endmindmap

https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap
@startmindmap
-  
-- Not empty
-- 
@endmindmap