https://github.com/plantuml/plantuml/pull/2452
@startmindmap
* 
	* 
		* 
		* 
	* 
@endmindmap

https://github.com/plantuml/plantuml/pull/2452
@startmindmap
*
	*
		*
		*
	*
@endmindmap

https://github.com/plantuml/plantuml/pull/2452
@startmindmap
* 
** 
** 
*** 
*** 
**** 
**** 
*** 
@endmindmap

https://github.com/plantuml/plantuml/pull/2452
@startmindmap
*
**
**
***
***
****
****
***
@endmindmap

https://github.com/plantuml/plantuml/pull/2452
@startmindmap
+ 
++ 
++ 
+++ 
+++ 
++++ 
++++ 
+++ 
@endmindmap

https://github.com/plantuml/plantuml/pull/2452
@startmindmap
+
++
++
+++
+++
++++
++++
+++
@endmindmap