https://forum.plantuml.net/18266/defining-a-theme-for-embedded-diagram-breaks-it
@startuml

component a {
}

note top of a
==theme don't fail==
{{
!theme crt-amber
User->System: test
}}
end note
@enduml

https://forum.plantuml.net/18266/defining-a-theme-for-embedded-diagram-breaks-it
@startuml

component a {
}

note top of a: \n==theme fail==\n{{\n!theme crt-amber\nUser->System: test\n}}\n

@enduml
