{
  "sha1": "34de4hd180yfpljyutojaysyxrjg9he",
  "insertion": {
    "when": "2026-01-25T20:40:06.703Z",
    "url": "https://github.com/plantuml/plantuml/issues/279",
    "user": "plantuml@gmail.com"
  }
}
@startuml
A -> C
create B
A -> B
A <- B
A <- B
destroy B
A -> C
A -> B **
B --> A
A -> B !!
A -> C
@enduml
