{
  "sha1": "r1opg0g5y3mmgjgqel6mcpqxr1p9qqk",
  "insertion": {
    "when": "2024-06-04T17:28:43.234Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam defaultTextAlignment center
skinparam minClassWidth 200
component foo
component barwhichisverylongandoutbreakthelimitgivenbythedefaultvalue
node node [
foo1
====
foo2
]
artifact artifact
@enduml
