{
  "sha1": "iwws675rylx0zrkpppiwfqa9fz1gvp4",
  "insertion": {
    "when": "2024-05-30T20:48:19.654Z",
    "url": "http://alphadoc.plantuml.com/doc/dokuwiki/en/nwdiag",
    "user": "plantuml@gmail.com"
  },
  "humhash": "fipago-01-vuzi220"
}
@startnwdiag
nwdiag {
    internet [ shape = cloud];
    internet -- router;

    network proxy {
        router;
        app;
    }

    network default {
    	app;
        db;
    }
}
@endnwdiag
