{
  "sha1": "scwwt4yczk9i3tsjcsqg8a9cb6jox6u",
  "insertion": {
    "when": "2024-06-04T17:28:44.985Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "sadape-74-fiba424"
}
@startuml
(*) --> "toto"
@enduml
