{
  "sha1": "mximssrkp25jbaad2t3w33rz3103fq8",
  "insertion": {
    "when": "2024-06-03T18:59:29.894Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Development 0.1] lasts 9 days
[Production 0.1] starts at [Development 0.1]'s end
[Production 0.1] starts at [Development 0.1]'s end and ends at [Production 0.2]'s start
[Development 0.2] starts at [Development 0.1]'s end and lasts 6 days
[Production 0.2] starts at [Development 0.2]'s end 
@endgantt
