{
  "sha1": "mxl2n2uqi5r234asvcl6nbrlwsm18e1",
  "insertion": {
    "when": "2024-05-30T20:48:21.566Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:Ready;
:next(o); <<procedure>>
:Receiving;
split
 :nak(i); <<input>>
 :ack(o); <<output>>
split again
 :ack(i); <<input>>
 :next(o)
 on several line; <<procedure>>
 :i := i + 1; <<task>>
 :ack(o); <<input>>
split again
 :err(i); <<output>>
 :nak(o); <<input>>
split again
 :foo; <<save>>
split again
 :i > 5; <<continuous>>
stop
end split
:-;
@enduml
