{
  "sha1": "lfqfzppqr8lx5t5kcr7vp7kizigmncw",
  "insertion": {
    "when": "2024-06-03T18:59:34.079Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package p1{
}

package p2 <<Rectangle>>{
class c1
}

package p3{
}

p1 -> p2 : works
p1 -|> p2 : don't work

p1 -|> p3 : works
@enduml
