{
  "sha1": "lfywdi03t13invagev8fj5rjzunympu",
  "insertion": {
    "when": "2024-06-03T18:59:34.093Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

[*] --> State1

State1 --> [*]

State1 -> State2

State2 --> [*]
State1 : This is a string
@enduml
