{
  "sha1": "3783q1wqv76lamas8mlup2r9in8h9a0",
  "insertion": {
    "when": "2025-10-01T18:22:58.461Z",
    "user": "The-Lum"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***[#green]<_:L21 a
L21 b;
***(l2)<_:L22 a
L22 b;

l2 -> l1
@endwbs
