{
  "sha1": "9ks9k9foxv7cq7apc6qxit0rq4kiplz",
  "insertion": {
    "when": "2024-05-30T20:48:21.706Z",
    "url": "https://forum.plantuml.net/15159/wbs-missing-link-and-missing-box",
    "user": "plantuml@gmail.com"
  }
}
@startwbs 
+ root
 + level 1%n()right%n()wrong upper link
  + level 2%n()right right
   + level 3%n()right right right
   - level 3%n()right right left
  - level 2%n()right left
   + level 3%n()right left right
    + level 4%n()right left right right
    - level 4%n()right left right left
   - level 3%n()right left left
    + level 4%n()right left right right
    - level 4%n()right left right left
 + level 1%n()left%n()This is missing
@endwbs
