{
  "sha1": "p1kirryx6b8jtif0jn7ieiy6qevtdi4",
  "insertion": {
    "when": "2024-06-04T17:28:40.569Z",
    "url": "https://github.com/plantuml/plantuml/issues/1007",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma useVerticalIf on
|LaneA|
start
:Activity1;
|LaneB|
if (Conditional) then (yes)
 |Lane C|
 :Activity2;
(No) elseif (Conditional)
 |Lane D|
 :Activity3;
else (No)
 |Lane E|
 :Activity4;
endif
stop
@enduml
