{
  "sha1": "q1qef0vvhkgtb63fj1sjrg1pdym35q3",
  "insertion": {
    "when": "2024-06-04T17:28:41.998Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "givumi-837-kexixe"
}
@startuml
A -> B
== test ==
A -> B
====
A -> B

@enduml
