{
  "sha1": "o18bamb2x0uz7b0u06azlicharkzv0z",
  "insertion": {
    "when": "2024-06-04T17:28:39.227Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'skinparam linetype ortho
(*top) --> "onCreate()"
"onCreate()" --> "onStart()"
"onStart()" --> if "In foreground?" then
--> [YES: Activity%n()becomes visible] "onResume()"
else
--> [NO: Activity%n()no longer visible] "onStop()"
endif
"onResume()" --> [Activity interacts with user] "onPause()"
"onPause()" --> "onStop()"
"onStop()" -*-> [Process is killed, user navigates back to activity] "onCreate()"
"onStop()" -*-> [Activity comes%n()to foreground] "onRestart()"
"onRestart()" -right-> "onStart()"
"onStop()" --> "onDestroy"
"onDestroy" --> (*)
@enduml
