{
  "sha1": "3lnmgpsouuc5hwiyshmb82mceocnutf",
  "insertion": {
    "when": "2024-05-30T20:48:20.298Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "poluve-80-mire025"
}
@startuml
package Toto {
  class Toto
}
@enduml
