{
  "sha1": "siz3sy9sd8nfof7pl6oy7ply0izi9nq",
  "insertion": {
    "when": "2024-06-04T17:28:45.151Z",
    "url": "https://github.com/plantuml/plantuml/issues/863",
    "user": "plantuml@gmail.com"
  }
}
@startuml

state A as "A on several lines\nwith\na lot of text" {
  X : aaa
}
state B {
  Z : ccc
}
X -> Z
X <- Z
@enduml
