{
  "sha1": "ed3r2aedom2eucmred54r04nnmu52se",
  "insertion": {
    "when": "2024-06-01T09:03:04.264Z",
    "url": "https://forum.plantuml.net/11491/backgroundcolor-transparent-doesnt-empty-group-deployement?show=11491#q11491",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam BackgroundColor transparent

component A #aliceblue {
   component "A.1.KO" {
   }
   
   component A.4 {
      [A4.1]
   }
}
[a]
@enduml
