{
  "sha1": "6gnq04dnf00k50gqwtnqwjrj4jyfnl1",
  "insertion": {
    "when": "2024-05-30T20:48:20.954Z",
    "url": "http://alphadoc.plantuml.com/doc/dokuwiki/en/nwdiag",
    "user": "plantuml@gmail.com"
  }
}
@startuml
nwdiag {

    network aa {
        router;
        app;
    }


    network bb {
    	app;
        db;
    }
    
    group {
      color = "pink";
      app;
      db;
    }

}
@enduml
