{
  "sha1": "1qi41b8j2zv79twc8jm8cglcbbue9ll",
  "insertion": {
    "when": "2024-05-30T20:48:19.762Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2
!procedure msg($source, $destination)
$source --> $destination
!endprocedure

!procedure init_class($name)
class $name {
addCommonMethod()
}
!endprocedure


!procedure addCommonMethod()
  toString()
  hashCode()
!endprocedure


init_class("foo1")
init_class("foo2")
msg("foo1", "foo2")
@enduml
