{
  "sha1": "5zp18d1w8kyg72uhwf9sh48idclxe2t",
  "insertion": {
    "when": "2024-05-30T20:48:20.838Z",
    "url": "https://forum.plantuml.net/14729/consistency-arrow-syntax-between-state-deployment-diagrams",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state a
state b
a -l-> b
@enduml
