{
  "sha1": "5zvx604ab8u9iv85l8we78cy6gvqw6t",
  "insertion": {
    "when": "2024-05-30T20:48:20.842Z",
    "url": "https://forum.plantuml.net/9178/empty-packages-do-not-respect-skinparams",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam package {
  FontColor green
  FontSize 60
  BorderStyle dashed
}

package pack1
package pack3

pack1 --> pack3
@enduml
