{
  "sha1": "c1saos2ohqveyminm7dbtojlv6ir2ij",
  "insertion": {
    "when": "2024-06-01T09:03:00.771Z",
    "url": "https://github.com/plantuml/plantuml/issues/1039",
    "user": "plantuml@gmail.com"
  }
}
@startyaml


compile:
  extends: .sbt-compile-cross

test mario-domain:
  extends: .sbt-test-cross

@endyaml
