{
  "sha1": "mz0h64zi4c0a4m5midlr52uyvcw57p3",
  "insertion": {
    "when": "2024-06-03T18:59:29.852Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:initiate switch() ; <<#01DF01>>
:VerifierRecevabiliteCHF(); <<#01DF01>>
if (PCE connu) then (non)
:statut 022;
stop
else (oui)
endif
if (Validee) then (non)
:statut 023;
stop
endif 
while (Besoin RdV)
:statut 045;
if (Date disponible) then (oui)
:envoi heures du creneau;
if (Confirmation) then (oui)
:AccepterRdV(); <<#01DF01>>
:Statut 063;
Stop
else (non)
endif
else (non)
:envoi de liste de disponibilites;
while (changement de liste)
:demanderPrecSuiv(); <<#01DF01>>
:recuper nouvelle liste;
endwhile (liste OK)
endif
:ProposerDatePlage(); <<#01DF01>>
endwhile (Pas de RdV)
:Statut 050;
stop
@enduml
