{
  "sha1": "ijgadbv1xjp3a88n7qic6prn23jkpsx",
  "insertion": {
    "when": "2024-06-03T18:59:30.800Z",
    "url": "https://github.com/plantuml/plantuml/issues/951#issuecomment-1339828969",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Foo {
method()
}
class Bar
class Qux

Foo::method --> Bar:
Foo::method --> Bar: drawing
(Foo, Bar) --> Qux
@enduml
