{
  "sha1": "ksgjp62xf0piuvfq3bi1sejvycofk07",
  "insertion": {
    "when": "2024-06-03T18:59:33.311Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
ignorenewpage

Bob -> Alice : hello

newpage

Bob -> Alice : hello2
create Dog
Alice --> Dog : creation
Bob -> Alice : hello3

newpage
Bob -> Alice : hello4
@enduml
