{
  "sha1": "lnezmaak05gboznnvhx8t4828px1lpu",
  "insertion": {
    "when": "2024-06-03T18:59:34.333Z",
    "url": "http://forum.plantuml.net/8228/activation-after-group-end-does-not-work",
    "user": "plantuml@gmail.com"
  }
}
@startuml

participant A
participant B


activate A
A -> B: Request
deactivate A
opt condition
B -> B : Request
end

activate A
A -> B: Request
B -> A : Response
deactivate A

@enduml
