{
  "sha1": "tcdj5feyqrjfqsbyesbs5cuf8lqn7p1",
  "insertion": {
    "when": "2024-06-04T17:28:46.068Z",
    "url": "https://github.com/plantuml/plantuml/issues/1702",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
.a {
  LineThickness 3
  Linecolor red
}
</style>

card a
a -> b <<a>>
@enduml
