{
  "sha1": "q47wxsnygxd4vzmfxv4prdm3xrxdtz7",
  "insertion": {
    "when": "2024-06-04T17:28:42.032Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
salt
{
[X] checkbox|[] checkbox
() radio
(X) radio
This is a text|[This is my button]|This is another text
"A field"|"Another long Field"|[A button]
}
@enduml
