{
  "sha1": "qighgre7cy95srjttkk0ema4m0ftbhi",
  "insertion": {
    "when": "2024-06-04T17:28:42.487Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

fork
:A1;
:A2;
:A3;
Fork again
:B1;
:B2;
End fork

@enduml
