{
  "sha1": "etbx4jhdfqu764803s40d9qkxaviblo",
  "insertion": {
    "when": "2024-06-01T09:03:05.071Z",
    "url": "https://github.com/plantuml/plantuml/pull/450",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam ActivityEndColor red
skinparam ActivityStartColor red
skinparam BackgroundColor grey
skinparam Shadowing false

start
end
stop

@enduml
