{
  "sha1": "ql6znc95nw817ol1v7lokoylwf81cmw",
  "insertion": {
    "when": "2026-04-05T09:46:55.213Z",
    "url": "https://github.com/plantuml/plantuml/issues/2518",
    "user": "plantuml@gmail.com"
  }
}
@startuml
+class A {
}
@enduml
