{
  "sha1": "qlban9if0fwd41sm55bsi1qc9vq4fzo",
  "insertion": {
    "when": "2024-06-04T17:28:42.563Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
component C1 {
  component A
  interface I
  A -() I
}

component C2 {
  component U
  I )-- U
}
@enduml
