{
  "sha1": "hrjsoyvrtq1ou4nhypfwxv5xcgo2dkq",
  "insertion": {
    "when": "2024-05-30T20:48:22.102Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:Action; <<procedure>> <<#lightblue>>
-[#blue]-> callback;
if () then (OK)
-[#black]->
else if () then (ERROR)
  -[#red]->
   :ERROR; <<#lightpink>> <<task>>
   stop
else (timeout)
  -[#green]->
   :TIMEOUT; <<task>> <<#lightpink>> 
   stop
endif
-[#yellow]->
end
@enduml
