{
  "sha1": "ave6gfoegyvr5monua0yga0uoxk4usc",
  "insertion": {
    "when": "2025-11-29T11:55:56.741Z",
    "url": "https://forum.plantuml.net/14494/is-it-possible-to-color-the-days-in-the-default-gantt-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19

[A] lasts 2 days
[B] lasts 2 weeks
[C] lasts 2 months

@endgantt
