{
  "sha1": "elilno4k4ko3e3ylg7f0kmuw15nch9d",
  "insertion": {
    "when": "2024-06-01T09:03:04.639Z",
    "url": "https://github.com/plantuml/plantuml/issues/1123",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
* long plain text
**: **first**
<latex> \int_{0}^{\infty} \left( \sum_{i = 0}^{n} \right) {\rm d}x </latex>
;
**: **second**
<latex>
    \int_{0}^{\infty} \left( 
        \sum_{i = 0}^{n} 
    \right) {\rm d}x 
</latex>;
@endmindmap
