{
  "sha1": "fotn5zxmd08xqodo4rgmfqk025j8anl",
  "insertion": {
    "when": "2024-06-01T09:03:06.452Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=5105/notes-in-activity-diagrams",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
note
    first note on start
    **should point to start**
end note
note
    second note on start
    **should point to first note**
end note
stop
@enduml
