{
  "sha1": "q887msa1nzz0fwnjmv7rnqztbsnyiz9",
  "insertion": {
    "when": "2024-06-04T17:28:43.513Z",
    "url": "https://forum.plantuml.net/15606/activity-arrow-label-overlap-on-some-activity-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!t="this is t1%n()this is t2%n()this is t3%n()"
!z="this is z1%n()this is z2%n()this is z3%n()"

:end;
repeat
  :read data;
  :generate diagrams;
->t;
repeat while (foo) is (z)
stop
@enduml
