{
  "sha1": "r02tdkbwkienxw3evubvt6qmcl6owum",
  "insertion": {
    "when": "2024-06-04T17:28:43.142Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class R1
class R2
A--B
(A,B) .. R1
R2 .. (A,B)
@enduml
