{
  "sha1": "r04vfo4ezkocq9bewwjlwpb65utvnqx",
  "insertion": {
    "when": "2024-06-04T17:28:43.155Z",
    "url": "https://github.com/plantuml/plantuml/issues/1190",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam ArrowHeadColor none

start
:Foo;
partition "Backend" {
fork
  partition "Before" {
    :action A;
  }
fork again
  partition "After" {
    :action B;
  }
end fork
}

stop
@enduml
