{
  "sha1": "r0aq6fqe342evhf7ijxqbo8l0ews4we",
  "insertion": {
    "when": "2024-06-04T17:28:43.177Z",
    "url": "https://forum.plantuml.net/11052/remove-unlinked-components?show=11133#c11133",
    "user": "plantuml@gmail.com"
  }
}
@startuml
together t{
}
class foo
remove @unlinked
@enduml
