{
  "sha1": "84nyidj7303zqgrqe4j2nja0fw4d08a",
  "insertion": {
    "when": "2024-05-30T20:48:21.338Z",
    "url": "https://github.com/plantuml/plantuml/issues/134",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam noteTextAlignment left
Alice->Bob:m1
Bob->Charlie:m2
note across
this left
on several lines
end note
Bob->Alice
@enduml
