{
  "sha1": "i0gxhjk6wmbnbl9dgjybtcy2y0t0kf",
  "insertion": {
    "when": "2024-06-03T18:59:30.210Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam sequenceParticipantBorderThickness 0.5
' skinparam sequenceBoundaryBorderThickness .7
skinparam sequenceLifeLineBorderThickness 3
skinparam sequenceActorBorderThickness .1
skinparam sequenceDividerBorderThickness .3

Bob -> Alice : hello1
actor Foo1
boundary Foo2
control Foo3
entity Foo4
== First point ==
Bob -> Alice : hello2
alt foo
Bob -> Alice : hello3
end


@enduml
