{
  "sha1": "8y0k370731ku32628px2zd29ctrsbxy",
  "insertion": {
    "when": "2024-11-19T12:22:17.320Z",
    "url": "https://github.com/plantuml/plantuml/issues/1654",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
'printscale weekly
printscale daily zoom 2
saturday are closed
sunday are closed
Project starts the 2024-01-08
[Task1] on {Alice} requires 5 days
[Task2] on {Bob:50%} requires 2 days
then [Task3] on {Alice:50%} requires 1 days
@endgantt
