{
  "sha1": "8yw6mnd3gsw8q57gt90b7xjz5lxn708",
  "insertion": {
    "when": "2024-05-30T20:48:21.758Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:<color:zzyellow>toto; <<#blue>>
@enduml
