{
  "sha1": "7m6oaxixh79zwfswlu3u7mqmf8wwrnz",
  "insertion": {
    "when": "2024-05-30T20:48:21.238Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

if (condition?) then (yes)
  :yes;
else (no)
  :no;
  note right
    any very very long text
  end note
endif
stop

legend
this is the legend
endlegend

@enduml
