{
  "sha1": "airub4ffbgdfca1qzl0eebpp4yw6hsp",
  "insertion": {
    "when": "2024-06-03T18:59:35.095Z",
    "url": "https://forum.plantuml.net/16473/putting-plantuml-gantt-chart-deliverable-milestone-diamond?show=16473#q16473",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] lasts 1 weeks
then [Prototype completed]  lasts 4 days
[End Prototype completed] happens at [Prototype completed]'s end
then [Test prototype] lasts 5 days
[End Test prototype] happens at [Test prototype]'s end

[Prototype completed] is deleted
[End Prototype completed] is deleted
@endgantt
