{
  "sha1": "7ghr3xrparhfh91iz87scw8hvc0bu5j",
  "insertion": {
    "when": "2024-05-30T20:48:21.198Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
group body {
cheese color=BurlyWood  radius=100 start=270 end=360 position=70,100
cheese color=BurlyWood  radius=50 start=90 end=270 position=50,50
rectangle color=BurlyWood  dimension=20,100 position=50,0
}
rectangle color=black dimension=2,2
body position=10,10 rotation=15 scale=0.5
@endcute
