{
  "sha1": "mf2z6w3lqztgz7783ik0xi8cl44r3oy",
  "insertion": {
    "when": "2024-06-03T18:59:35.174Z",
    "url": "http://plantuml.com/paypal",
    "user": "plantuml@gmail.com"
  }
}
@startuml
digraph structs {
    struct1 [shape=record, label="<f0> left|<f1> middle|<f2> right"];
    struct2 [shape=record, label="<f0> one|<f1> two"];
    struct3 [shape=record, label="<here> a | { b | { c | d | e } | f } | g | h"];
    struct1:f1 -> struct2:f0;
    struct1:f2 -> struct3:here;
}
@enduml
