{
  "sha1": "mfoc5184q9fbmcw9q6mjzu7a1qking8",
  "insertion": {
    "when": "2024-06-03T18:59:35.189Z",
    "url": "http://forum.plantuml.net/8025/elseif-skinparam-doesnt-seem-to-use-the-activitydiamond",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam activity {
   BackgroundColor #00538D
   BorderColor #00538D
   BorderThickness 1
   BorderRoundCorner 1
   ArrowColor #8CC63E
   FontName Helvetica
   FontColor White
   DiamondBackgroundColor #00538D
   DiamondBorderColor #00538D
   DiamondFontName Helvetica
   DiamondFontColor White
}
title If else elseif example
if (If Text) then (yes)
:Do Something;
else (No)
endif
if (Option A) then 
:A Thing>
elseif (Option B)
:B Thing>
elseif (Option C)
:C thing>
endif
@enduml
