{
  "sha1": "dgegpwpuv3hld8oaptt2pgpvj45v5rb",
  "insertion": {
    "when": "2024-06-01T09:03:02.962Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'skin net.sourceforge.plantuml.skin.bluemodern.BlueModern
opt toto
Bob->Alice : coucou%n()it%n()me
activate Alice
Alice->Alice: well
else sinon
Alice-->Bob: ok
end
deactivate Alice
@enduml
