{
  "sha1": "dgsok6t1w454ru7662psgm5z2v2bk9j",
  "insertion": {
    "when": "2024-06-01T09:03:04.967Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] lasts 13 days
[Test prototype] ends at [Prototype design]'s end
[Test prototype] lasts 4 days
@endgantt
