{
  "sha1": "350u9gww77heoenqj4ig5vi24zp3cut",
  "insertion": {
    "when": "2024-05-30T20:48:20.182Z",
    "url": "https://forum.plantuml.net/11344/no-text-spacing-with-fork-activity-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
fork
-> Have something that is long%n()written here as an%n()example;
fork
-> This is more%n()text that is%n()too long for the arrow;
:something;
fork again
:something else;
endfork
-> showing more text that is%n()too long once again%n()in this%n()particular%n()scenario%n()where this happens;
:final state of%n()this fork;
-> Have something that is long%n()written here as an%n()example;
fork
-> This is more%n()text that is%n()too long for the arrow;
:something;
fork again
:something else;
endfork
-> This is more%n()long%n()text but notice%n()how it fits%n()because it's after the%n()endfork;
endfork
@enduml
