{
  "sha1": "358v1m3sp7nmokfm6hq9mnqkx1hazai",
  "insertion": {
    "when": "2024-05-30T20:48:20.186Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Design phase/Prototype design] lasts 3 weeks
[Design phase/Test prototype] starts at [Design phase/Prototype design]'s end and lasts 2 weeks
[Design phase/Prototype completed] happens at [Design phase/Test prototype]'s end
[Production phase/Setup assembly line] lasts 2 weeks and starts at [Design phase/Prototype completed]'s end
[Production phase/Hire assemblers] lasts 1 week and ends at [Design phase/Prototype completed]'s end
[Production phase/Assemble first batch] lasts 3 days and starts at [Production phase/Hire assemblers]'s end
@endgantt
