{
  "sha1": "h9qyr98ja5mc8ey42ln3ll0ycf85m46",
  "insertion": {
    "when": "2024-06-03T18:59:29.341Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
cheese color=red radius=100 position=100,100 start=15 end=90
@endcute
