{
  "sha1": "h9xbjzfhdnn94fnq6pngi2uefdtl4zb",
  "insertion": {
    "when": "2024-06-03T18:59:29.348Z",
    "url": "https://github.com/plantuml/plantuml/issues/1008",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!theme plain

state ForkTest <<fork>>
state JoinTest <<join>>
[*] --> ForkTest
ForkTest --> State1
ForkTest --> State2
State1 --> JoinTest
State2 --> JoinTest
JoinTest --> [*]
@enduml
