{
  "sha1": "bfbzl3lkp5mrpuf4tik237esrli431t",
  "insertion": {
    "when": "2024-05-30T20:48:22.082Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (level1) then
if (level2) then
if (level3) then
if (level4) then
if (level5) then
if (level6) then
if (level7) then
endif
endif
endif
endif
endif
endif
endif
stop
@enduml
