{
  "sha1": "mws36frnqxg0eq42v9oi29bq4f99p1q",
  "insertion": {
    "when": "2024-06-03T18:59:35.847Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
cheese color=red radius=100 position=100,100 start=0 end=15
@endcute
