{
  "sha1": "lj0gzdqirzjrcqxks8e4apr27w73jvs",
  "insertion": {
    "when": "2026-03-01T18:18:07.495Z",
    "url": "https://github.com/plantuml/plantuml/issues/589",
    "user": "plantuml@gmail.com"
  }
}
@startuml
partition
a->b
end

group
a->c
end group
@enduml
