{
  "sha1": "ljvvgv6z8qs2bho7z4jjien571zfc37",
  "insertion": {
    "when": "2024-06-03T18:59:34.215Z",
    "url": "https://github.com/plantuml/plantuml/issues/376",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts the 5th of december 2018
saturday are closed
sunday are closed
2018/12/29 is opened
[Prototype design] lasts 17 days
[Prototype design] pauses on 2018/12/13
[Prototype design] pauses on 2018/12/14
[Prototype design] pauses on monday
[Test prototype] starts at [Prototype design]'s end and lasts 2 weeks
@endgantt
