{
  "sha1": "8adxzlo8rnc6g045biq4h4pyirh9i9q",
  "insertion": {
    "when": "2024-05-30T20:48:21.374Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
autonumber

Bob -> Alice : hello1%n()this%n()message
Bob -> Alice : hello2
Bob -> Bob : hello3
Bob -> Alice : hello4
Bob -> Alice : hello5
Bob -> Alice : hello6

@enduml
