{
  "sha1": "8aitp3wg1tdudegud115609zvk3ij13",
  "insertion": {
    "when": "2024-05-30T20:48:21.122Z",
    "url": "https://forum.plantuml.net/11250/backward-for-while-confusing-arrow-layout-on-continuation",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start

while(a)is(b)
   :do something;
   backward:test;
endwhile

:Confusing layout
The arrows look
to cross each other; <<output>> <<#FF8080>>

while(a)is(b)
   :do something;
   :test;
endwhile

:Correct
arrow layout; <<output>> <<#80FF80>>
@enduml
