{
  "sha1": "l1r85gbive6jpxhkznl1dmm4qhvegpm",
  "insertion": {
    "when": "2024-06-03T18:59:33.576Z",
    "url": "https://github.com/plantuml/plantuml/issues/1216#issuecomment-1355336618",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
component {
    BackgroundColor #red
}
</style>

component C1
@enduml
