{
  "sha1": "iilv148pj5vw8zz46mt7pc79b7njhqz",
  "insertion": {
    "when": "2024-06-03T18:59:30.758Z",
    "url": "https://github.com/plantuml/plantuml/issues/1394",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
stateDiagram {
	start {
	    BackgroundColor #palegreen
	    LineColor #pink
	    LineThickness 2.5
	}
	end {
	    BackgroundColor #palegreen
	    LineColor #green
	    LineThickness 2.5
	}
}
</style>

[*] --> State1
State1 --> [*]
@enduml
