{
  "sha1": "sg0ayo7zcmw6d8vdlq5uo39zx70981i",
  "insertion": {
    "when": "2024-06-04T17:28:45.064Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
title Styling example
<style>
root {
  FontColor blue
}
</style>
Alice -> Bob : hello
@enduml
