{
  "sha1": "r2lvwslaad95wi3eslw1m102o5lqyua",
  "insertion": {
    "when": "2024-06-04T17:28:43.300Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
<style>
wbsDiagram {
  node {
    Padding 5
    Margin 15
    BackGroundColor white
  }

  .europeStyle * {
	  node {
	    FontColor red
	  }
  }

  .europeStyle {
	  node {
	    FontSize 20
	  }
  }

}
</style>

* World
** Europe <<europeStyle>>
*** England
*** Germany
*** Spain
@endwbs
