{
  "sha1": "14f4fq7d82iax5a765dozamayiconiq",
  "insertion": {
    "when": "2024-05-30T20:48:19.562Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam iconPrivateColor #C82930
skinparam iconPrivateBackgroundColor #F24D5C
skinparam iconProtectedColor #B38D22
skinparam iconProtectedBackgroundColor #FECF6C
skinparam iconPackageColor #1963A0
skinparam iconPackageBackgroundColor #4177AF
skinparam iconPublicColor #038048
skinparam iconPublicBackgroundColor #84BE84

class classe1 {
  -field1
  ~field2
   field3
  #field4
  +field5

  -method1()
  ~method2()
   method3()
  #method4()
  +method5()
}

@enduml
