{
  "sha1": "frenvbczgqwijl5g2czwvolaom9jc86",
  "insertion": {
    "when": "2024-06-01T09:03:06.561Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
triangle points=(0,0,5):(10,100,50):(234,35,40) color=red
@endcute
