{
  "sha1": "frulck7n2j1bflf12emg3f96a0di8sp",
  "insertion": {
    "when": "2024-06-01T09:03:06.569Z",
    "url": "http://forum.plantuml.net/7287/change-classfontcolor-dynamically-between-class-boxes",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam classFontColor automatic
skinparam classHeaderBackgroundColor #444

class classA {
testMethodCode()        
}

class classB #fff {
testMethodCode()       
}
@enduml
