{
  "sha1": "6bvxbo7ssc5anzl2pzt86sb2pqpxuik",
  "insertion": {
    "when": "2024-05-30T20:48:20.926Z",
    "url": "https://forum.plantuml.net/16261/error-when-using-map-and-portin-portout-in-a-component",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'allowmixing

Package "Attribute Mapper" as attribute_mapper #ff9999 {
    portin "Maps Callbacks" as maps_callbacks
    portout "Maps Eval" as maps_evaluations
    component "Mapper engine" as mapper_engine {
    map "Mappings" as maps #acffa0 {
      Rule 1 => r'1 =  2 * r'2
      Rule 2 => d'2 =  d'1 / 2
      Rule 3 => r'3 =  r'4 + r'2
    }

  }
}
@enduml
