{
  "sha1": "3h7nie4jc8pby2hz5fzwa47v3wb9t50",
  "insertion": {
    "when": "2024-05-30T20:48:20.266Z",
    "url": "http://alphadoc.plantuml.com/doc/asciidoc/en/style-evolution",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
' style enclosure declaration
<style>
    ' scope to sequenceDiagram elements
    sequenceDiagram {   

     ' scope to actor element types
      actor { 
        FontColor Blue 
      }
     
     ' define a new style, using CSS class syntax
     .myStyle {
        FontColor Red
     }

    ' define a new style, using CSS class syntax
     .number1 {
        BackgroundColor #GoldenRod
        RoundCorner 20
        ShowStereotype true
     }

        ' define a new style, using CSS class syntax
     .number2 {
        BackgroundColor  #Green
        RoundCorner 20
     }
    }
} 
</style> 

' printed in blue
actor Bob 
' this will now be printed in Red 
actor Sally <<myStyle>>
participant Test <<Too>>
participant Test1 <<number1>>
participant Test2 <<number2>>
@enduml
