{
  "sha1": "ldo9rxzit1hxvzccmhjss3uwkf8p6l4",
  "insertion": {
    "when": "2024-06-03T18:59:34.015Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|AAAAAAAAAAAAAAAAAAAAAAAAA|
start
:a;
:long;
|B|
:b;
@enduml
