{
  "sha1": "kp2jbjymbe6m0kktet3vf7j8hlj8w1e",
  "insertion": {
    "when": "2024-06-03T18:59:33.215Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!define table(x) class x << (T,mistyrose) >>  
table('"m3.Table1" <generic here>')
table('"m3.Table2" <generic here too>')
m3.Table1 -> m3.Table2
@enduml
