{
  "sha1": "kp827d9y7ybwi92zaplydslgnw6c2ea",
  "insertion": {
    "when": "2024-06-03T18:59:33.222Z",
    "url": "https://github.com/plantuml/plantuml-server/issues/167#issuecomment-754719353",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam lengthAdjust none
autonumber "<b>[000]"
participant BusFMS as "FMS CAN"
participant FMSSrv as "FMStoIP\nserivce"
collections clients
clients -> FMSSrv: C1 addpng(P1,ES)
hnote over clients: dt max 1s
FMSSrv -> clients: FMS<rt=2250, P1(no-value, rt=0)>
note right FMSSrv: <b>Not</b> decided how to send no data.
@enduml
