{
  "sha1": "qqapzsftsrl2s1mruzzqqey9p48m2p",
  "insertion": {
    "when": "2024-06-04T17:28:42.756Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
actor Alice
participant Bob
box "This is the Solar system" #LightBlue
participant P
end box

participant Sun

Alice -> Bob
Bob -> P : a very long message for my dummy test
P -> Sun
@enduml
