{
  "sha1": "g92ezpmct6t89viecz8md8wmionb7mb",
  "insertion": {
    "when": "2024-06-01T09:03:07.411Z",
    "url": "https://forum.plantuml.net/14819/the-combination-while-note-break-statements-does-draw-figure",
    "user": "plantuml@gmail.com"
  }
}
@startuml
while(int i=0;i<100;i++)
   if ( conf ) then (true)
    note right
       if statement
    end note
    :finalize;
    break
   endif
end while
@enduml
