{
  "sha1": "g9elqxe8sczwijh6g3tyv91lchr8mie",
  "insertion": {
    "when": "2024-06-01T09:03:07.433Z",
    "url": "https://forum.plantuml.net/12159/gantt-diagram-no-style-entry-for-legend",
    "user": "plantuml@gmail.com"
  }
}
@startgantt

<style>
	legend {
		FontColor blue
		FontSize 15
        FontStyle italic
		LineColor Orange
	}
</style>

legend
hypothesis
 * Hyp 1
 * Hyp 2
end legend

project starts 2021-07-01

[Task] lasts 20 days

@endgantt
