{
  "sha1": "m21ak9c15x0mvkxv7umytam5w6pk5in",
  "insertion": {
    "when": "2024-06-03T18:59:34.753Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
sprite $serving jar:archimate/serving
skinparam rectangle {
roundCorner 25
}
sprite $process jar:archimate/process
rectangle " "  as A <<$process>>
rectangle " "  as B <<$serving>>
A -> B
legend left
<$serving> :serving
endlegend
@enduml
