{
  "sha1": "9r4zxnn8vxegt7aiq9ahxh07s73fjoj",
  "insertion": {
    "when": "2024-05-30T20:48:21.754Z",
    "url": "https://forum.plantuml.net/15475/betastyle-for-timingdiagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
timingDiagram {
  document {
    BackGroundColor SandyBrown
  }
 constraintArrow {
  LineStyle 2-1
  LineThickness 1
  LineColor Blue
 }

 .mystyle{
   LineStyle 3-3
   BackGroundColor yellow
   LineThickness 5
   LineColor red
 }
}
</style>
robust "Web Browser"  as WB <<mystyle>>
concise "Web User" <<mystyle>> as WU 


WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}

@WU
0 is Waiting
+500 is ok
@200 <-> @+150 : {150 ms}
@enduml
