{
  "sha1": "9r9s8hrhzqhckbjw5pib4qlzm20ck7h",
  "insertion": {
    "when": "2024-05-30T20:48:21.754Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (foo) then (ok3)
:f1;
(additional text) elseif (foo2) then (ok2)
:f2;
else (notok)
:f3;
endif
@enduml
