{
  "sha1": "e1kcscbpir9uj9enx7xc6rh47rvz38o",
  "insertion": {
    "when": "2025-10-01T18:22:58.800Z",
    "user": "The-Lum"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***<_[#green](z):L21 a
L21 b;
***<[#pink](l2):L22 a
L22 b;

l2 -> l1
@endwbs
