{
  "sha1": "hi4ohqa394f4mxtvpe2qv3wdrj1p3rm",
  "insertion": {
    "when": "2024-06-03T18:59:29.595Z",
    "url": "https://github.com/plantuml/plantuml/issues/470",
    "user": "plantuml@gmail.com"
  }
}
@startuml
hide members
class Foo {
	bar
}
note left of Foo::bar
This is some bar.
endnote
@enduml
