{
  "sha1": "hihgz6dopv15kmh1lp0h72191cetmzq",
  "insertion": {
    "when": "2024-06-03T18:59:29.609Z",
    "url": "https://github.com/plantuml/plantuml/issues/134",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam noteTextAlignment right
note as N1
👑 right
Keep Calm
and
Align Right
end note
@enduml
