{
  "sha1": "hdkdn8jbzbwp7zjuesfdropfuc0k06c",
  "insertion": {
    "when": "2024-06-03T18:59:29.481Z",
    "url": "https://github.com/plantuml/plantuml/issues/1214",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!theme cerulean

box "S/W"
participant driver

end box

box "NIC H/W"
participant dma_arb
end box

== Receive Pkt ==
driver -> dma_arb: test

@enduml
