{
  "sha1": "ms8hqankkyipe8yqs2pcpk4bgf2bjcx",
  "insertion": {
    "when": "2024-06-03T18:59:35.588Z",
    "url": "https://forum.plantuml.net/13376/cannot-use-symbols-at-the-beginning-of-keys-in-yaml",
    "user": "plantuml@gmail.com"
  }
}
@startyaml
あruit: Apple
size: Large
color: Red
@endyaml
