{
  "sha1": "msnj5t8ir4gp798uyddzdw65dldfobd",
  "insertion": {
    "when": "2024-06-03T18:59:35.609Z",
    "user": "plantuml@gmail.com"
  }
}
@startproject
close sunday
close saturday
FOO1$begin := 13-APR-2011
FOO1$work := 1
FOO1$duration := 7

FOO2$begin := FOO1$completed
FOO2$work := 1
FOO2$duration := 7

@endproject
