{
  "sha1": "trfgojbspjux7xmz1yvfg13r9oob2v0",
  "insertion": {
    "when": "2024-06-04T17:28:46.652Z",
    "url": "http://forum.plantuml.net/7675/teoz-box-around-participants",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true

box "QuiteLongNameforBoxWhichIsVeryLong0"
participant a0
participant b0
participant c0
end box

box "QuiteLongNameforBoxWhichIsVeryLong1"
participant a1
participant b1
participant c1
end box

participant z
@enduml
