{
  "sha1": "trnhtch53hoe00rt3hu3pzokolpgexs",
  "insertion": {
    "when": "2024-06-04T17:28:46.659Z",
    "url": "https://avono-support.atlassian.net/browse/PUML-434",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam defaultFontSize 30
scale max 1000 width
allow_mixing

'together {
	package "[[link to confluence page]]" as abc{
		package "Example1" as def{ } 
		package "Example2" as ghj { } 
		component [abc-service]
	}
	package "[[link/to/another/page page]]" as page{
		package "subpack" as sub_package{ } 
	}
'}


@enduml
