{
  "sha1": "k8ffl5yszncfexyjpsxcvc1y2mhrxhs",
  "insertion": {
    "when": "2024-06-03T18:59:32.726Z",
    "user": "plantuml@gmail.com"
  }
}
@startsalt
{
{T
+Region        | Population
+ World        | 7.13 billion
++ America     | 964 million
+++ Canada     | 35 million
+++ USA        | 319 million
++++ NYC       | 8 million
++++ Boston    | 617 thousand
+++ Mexico     | 117 million
++ Europe      | 601 million
+++ Italy      | 61 million
+++ Germany    | 82 million
++++ Berlin    | 3 million
++ Africa      | 1 billion
}
}
@endsalt
