{
  "sha1": "k8pu52wo9kizpzeevr7u541suatujjr",
  "insertion": {
    "when": "2024-06-03T18:59:32.733Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
if(beginning of
the day)
:say hello!;
endif
:foo;
repeat
:Hello world!;
repeatwhile(bool1 is True
AND something
AND bool2 is False)
@enduml
