{
  "sha1": "pgogd6s6azdxohcpus0onrvbmiij6ew",
  "insertion": {
    "when": "2024-06-03T18:59:31.004Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days
[Test prototype] ends 3 days before [Prototype design]'s end
@endgantt
