{
  "sha1": "blz02c6f60sa3i2mg052h7jsnel6pdv",
  "insertion": {
    "when": "2024-05-30T20:48:22.118Z",
    "url": "http://forum.plantuml.net/8945/skinparam-wrapwidth-brake-line-incorrectly",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam wrapWidth 300
a -> b : init
note over a 
long text1 long text2 long text3 long text4 long text5 long text6 long text7 long text8 long text9 long text10 long text11 long text12 long text13 long text14 long text15 long text16 long text17 long text18 long text19 long text20 long text21 long text22 long text23
end note
a <- b : ack
note over a 
long text1 long text2 long text3 long text4 long text5 long text6 <color #red>long</color> text7 long text8 long text9 long text10 long text11 long text12 <u>long</u> text13 long text14 long text15 long text16 long text17 long text18 long text19 long text20 long text21 long text22 long text23
end note
@enduml
