{
  "sha1": "nu5mfinm8onzgayuiq5hch5vaajgak1",
  "insertion": {
    "when": "2024-06-04T17:28:39.051Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam CircledCharacterRadius 6
class Toto
@enduml
