{
  "sha1": "o0gqhodw8yjwuu7lyurx9loc13uqof3",
  "insertion": {
    "when": "2024-06-04T17:28:39.219Z",
    "url": "https://github.com/plantuml/plantuml/issues/855",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
repeat
  :Do something;
  backward: first statement is overridden;
  backward: second statement replaces first statement;
repeat while (you want to)
end
@enduml
