{
  "sha1": "e68163o9zupitbtlj8set7fd0xhhlsz",
  "insertion": {
    "when": "2025-10-01T18:22:56.758Z",
    "url": "https://github.com/plantuml/plantuml/issues/2363",
    "user": "The-Lum"
  }
}
@startwbs
* Root
** C1
**(c2) C2
***(c22)< C22

c22 -> c2 #red
@endwbs
