{
  "sha1": "e6zxy9me1hrghae3spmyvmccg7bq8ck",
  "insertion": {
    "when": "2024-06-04T17:28:46.644Z",
    "url": "https://github.com/plantuml/plantuml/issues/1534",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
.test  {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
}
.save {
  FontColor navy
  BackGroundColor Cyan
}
</style>

:multiple\nlines\nusing\nbackslash-n; <<test>>
:multiple\nlines\nusing\nbackslash-n; <<test>>
:multiple
lines
using
new lines; <<test>>

:multiple\nlines\nusing\nbackslash-n; <<save>>
:multiple
lines
using
new lines; <<save>>
@enduml
