{
  "sha1": "8c7tonvswrzcbp3m61qrjjr5vame5gp",
  "insertion": {
    "when": "2024-05-30T20:48:21.386Z",
    "url": "https://forum.plantuml.net/9741/define-%40append-broken",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!define fileServer <color:green><&folder>ho-itd-pbrcs05</color>
@pause
@append start
@append :===initialization
@append #create fileServer ]
@append end
@enduml
