{
  "sha1": "8cfxn6fgqd10atf2lzeeschj2gm2ml7",
  "insertion": {
    "when": "2024-05-30T20:48:21.390Z",
    "url": "https://forum.plantuml.net/18397/gantt-how-handle-resource-starts-terminates-specific-date",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
project starts on 2023-12-01
[Task1] on {Alice} lasts 20 days
{Alice} is off before 2023-12-04
@endgantt
