{
  "sha1": "lm052arush1g86z8h1cg9nay2suay8k",
  "insertion": {
    "when": "2024-06-04T17:28:41.157Z",
    "url": "https://forum.plantuml.net/11674/practical-gantt-chart-improvements",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days and 1 week
[Test prototype] starts 1 week and 2 days after [Prototype design]'s end
@endgantt
