{
  "sha1": "fuxd8indv3elq73woygs8qor870l748",
  "insertion": {
    "when": "2024-06-01T09:03:06.749Z",
    "url": "https://forum.plantuml.net/13655/hide-empty-descriptions-removes-inline-style-state-diagram?show=16487#c16487",
    "user": "plantuml@gmail.com"
  }
}
@startuml
hide empty description
state "Dashed 1" as State_1 ##[dashed]
State_1 : description
state "Dashed 2" as State_2 ##[dashed]

state "Dashed 3" as State_3 #line.dashed
State_3 : description
state "Dashed 4" as State_4 #line.dashed
@enduml
