{
  "sha1": "3vs5126u4ia45mqvxxc19hh2wrwkfed",
  "insertion": {
    "when": "2024-05-30T20:48:20.370Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:Registration in the system;
:Entering your username; <<input>>
repeat:Entering a password; <<input>>
:Re-entering your password; <<input>>
backward:Passwords don't match;
note right:Error
repeat while (Passwords match?) is (No) not (Yes)
:Sending data to the server; <<output>>
:Waiting for a response from the server for a certain amount of time;
if(The server responds?) then (No)
:Displaying the message: server is not responding;
:Return to the registration screen;
else (Yes)
:Response analysis;
if(Got an error?) then (Yes)
:Displaying an error message;
:Return to Eran registration;
else(No)
if(Is your username busy?) then (Yes)
:Displaying a message: This username is busy;
:Return to the registration screen;
else(No)
:Displaying a message: you have successfully registered;
endif
endif
endif
stop
@enduml
