{
  "sha1": "9m0cj0ybuamyo7gcuak1wapn8a95h77",
  "insertion": {
    "when": "2024-05-30T20:48:21.718Z",
    "url": "https://github.com/plantuml/plantuml/issues/863",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state state_1
state state_6
state state_7 {
[*] --> state_2
}

[*] --> state_1
state_1 --> state_7 : next
state_7 --> state_6 : next
@enduml
