{
  "sha1": "nxutobnmaai3hwo57ei15527m7ljiqe",
  "insertion": {
    "when": "2024-06-04T17:28:39.159Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam CircledCharacterRadius 9
class Toto
@enduml
