{
  "sha1": "pumofvfkd6abnbgz4f7gv3nma08bz61",
  "insertion": {
    "when": "2024-06-04T17:28:41.748Z",
    "url": "http://forum.plantuml.net/8940/promise-representation-in-sequence-diagram?show=9067#a9067",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Entity Observer
Entity Observable
Entity Promise
activate Observer
create Observable
Observer -> Observable : run
activate Observable
create Promise
Observable -> Promise :deffer
Observable --> Observer : return promise
deactivate Observer
Observable -> Promise : resolve
deactivate Observable
Promise -> Observer : then
activate Observer
Observer -> Observer : processAsync
destroy Observable
@enduml
