{
  "sha1": "puqbgysvyvuvzzvna8rgj1ufuajge5n",
  "insertion": {
    "when": "2024-06-04T17:28:41.761Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
activate Z1
 
Z1 --> Z2 : A1
activate Z1
loop
    Z1 -> Z2 : A2
end
deactivate Z1
Z1 -> Z2 : A3

@enduml
