{
  "sha1": "phpy6cabq3t7oizd6dzc980oz6fkcve",
  "insertion": {
    "when": "2024-06-04T17:28:41.206Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
'Feet
stick color=black position=40,45 dimension=5,15
stick color=black position=50,45 dimension=5,15
stick color=black position=35,55 dimension=25,5
'Noze
stick color=crimson position=10,20 dimension=15,10
'Queue
group queue {
 rectangle color=green position=0,4 dimension=5,5
 rectangle color=green position=0,8 dimension=10,5
}
queue position=33,9 rotation=-55
'Body
triangle color=#FF0000 points=(20,0,20):(20,45,20):(90,45,15)
circle color=white position=30,18 radius=5
@endcute
