{
  "sha1": "5lmjwon3955oguna3dxzi9w3mt3hj24",
  "insertion": {
    "when": "2024-05-30T20:48:20.770Z",
    "url": "https://forum.plantuml.net/11528/gantt-diagram-add-memos-or-explanations-to-tasks",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[task01] lasts 15 days
note bottom
  memo1 ...
  memo2 ...
  explanations1 ...
  explanations2 ...
end note

[task01] -> [task02]

@endgantt
