{
  "sha1": "pc8g2l3uvkk46uablvthdv82xhilmw5",
  "insertion": {
    "when": "2024-06-04T17:28:40.969Z",
    "url": "http://forum.plantuml.net/8612/teoz-wrong-note-position-after-array?show=9115#c9115",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
participant Bob
participant Alice
participant Ken
participant David
Bob -> Alice : hello1
& Alice -> Ken : hi1
& note right of David : Should be same level as "1"

@enduml
