{
  "sha1": "4yi71sgnqa2sja4he5wyds8ytbrakfs",
  "humhash": "melika-18-mire649",
  "insertion": {
    "when": "2026-07-25T16:32:32.632Z",
    "url": "https://github.com/plantuml/plantuml/issues/2789",
    "user": "plantuml@gmail.com"
  }
}
@startuml
A->B
opt
  B->C: test
  |||
  B->C: test
end
@enduml
