{
  "sha1": "1yabv45qmgslqkq1yqpxw3e5noie97d",
  "insertion": {
    "when": "2024-10-21T20:53:10.681Z",
    "url": "https://github.com/plantuml/plantuml/issues/1476",
    "user": "plantuml@gmail.com"
  }
}
@startuml
[*] --> StateA
state StateA {
}
state StateB {
}
StateA --> StateB
@enduml
