{
  "sha1": "qde8hc1ysy5rbgftmc2g8pau1qu8a11",
  "insertion": {
    "when": "2024-06-04T17:28:42.293Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

[*] --> NotShooting

state "Not Shooting State" as NotShooting {
  state "Idle mode" as Idle
  state "Configuring mode" as Configuring
  [*] --> Idle
  Idle --> Configuring : EvConfig
  Configuring --> Idle : EvConfig
}

@enduml
