{
  "sha1": "qdim3aqoifn6pr7ar544umxrbxbu0a4",
  "insertion": {
    "when": "2024-06-04T17:28:42.306Z",
    "url": "https://github.com/plantuml/plantuml/pull/109",
    "user": "plantuml@gmail.com"
  }
}
@startuml
robust "actor" as A

A is idle

@A
4 is sending
@3 <-> @4 : {foo}
@1 <-> @2 : BAR

@enduml
