{
  "sha1": "e995zls0z3zst8lc63jwdht87pgqvke",
  "insertion": {
    "when": "2024-06-01T09:03:04.135Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts the 5th of december 2018
saturday are closed
sunday are closed
2018/12/29 is opened
[Prototype design] lasts 17 days
[Prototype design] pauses on monday
[Test prototype] starts at [Prototype design]'s end and lasts 2 weeks
@endgantt
