{
  "sha1": "pqbegd165ldonducr27ijoh2zqgpown",
  "insertion": {
    "when": "2024-06-04T17:28:41.575Z",
    "url": "https://forum.plantuml.net/11803/improve-shape-of-node-element-deployement-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
scale 10
<style>
root {
LineThickness .5
}
</style>
frame frame
@enduml
