{
  "sha1": "69iyhlw8ye7q14f8f77pbry32i1ibdj",
  "insertion": {
    "when": "2025-10-16T19:18:49.867Z",
    "url": "https://github.com/plantuml/plantuml/issues/2386",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant ParticipantNumber1
participant ParticipantNumber2
participant ParticipantNumber3

ParticipantNumber1 -> ParticipantNumber1 : this is a very long message that is very long 
ParticipantNumber2 -> ParticipantNumber3 : foo2

@enduml
