{
  "sha1": "ar5f1gnogtnvcu1ubh1lyoa63rgdb6v",
  "insertion": {
    "when": "2024-05-30T20:48:21.938Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam activity {
/'BackgroundColor Yellow'/
BorderColor black
ArrowColor black
}
skinparam shadowing false
skinparam conditionStyle diamond
title conditionallyMoveSalary
start
floating note: 
:inputs: period, destPeriod, highestQuality\n'period' is the 'general regime' period\n'destPeriod' is the matching period of 'highestQuality';<<task>>
if (highestQuality IN (PILOT, FLIGHT_ATTENDANT) ??) then ([yes])
	if (period.quality == LABOURER ??) then ([no])
		if () then ([year < 2012])
			#7DC4FF:justify removal of period;
			note: salary is ignored because\nit should be included in\nspecial contribution salary
		else ([year >= 2012])
			:add salary from period to destPeriod;
		endif
		:remove period;
	elseif () then ([period.salary > 0])
	else ([period.salary == 0])
		:remove period;
		note: assimDays already moved\nto higher quality
	endif
else ([other highestQuality])
	if (period.salary == 0 ??) then ([yes])
		:remove period;
		note: assimDays already moved\nto higher quality
	else ([no])
	endif
endif
end
@enduml*/
