{
  "sha1": "arb38ke093lih1tgvh2qbjiasloa9cl",
  "insertion": {
    "when": "2024-05-30T20:48:21.938Z",
    "url": "https://forum.plantuml.net/16373/how-to-use-textcolor-for-rectangle",
    "user": "plantuml@gmail.com"
  }
}
@startuml
rectangle "My first Box" as box1 #text:red;line:red {
Bob -> Alice
}
@enduml
