{
  "sha1": "6iaya95lox2eth8nh2jp0cmngndiipl",
  "insertion": {
    "when": "2024-05-30T20:48:20.962Z",
    "url": "https://forum.plantuml.net/9638/incoming-message-bug-in-txt",
    "user": "plantuml@gmail.com"
  }
}
@startuml
[-> Bob : hello
@enduml
