{
  "sha1": "ov4lcj16vvx0id5hp4idrpbt4hvs5ms",
  "insertion": {
    "when": "2024-06-04T17:28:40.344Z",
    "url": "https://forum.plantuml.net/14516/skinparam-shadowing-in-nwdiag",
    "user": "plantuml@gmail.com"
  }
}
@startnwdiag
<style>
root {
 shadowing 0
}
</style>
nwdiag {
  network dc {
    server;
    internet;
  }
  internet [shape = cloud];
}

@endnwdiag
