{
  "sha1": "f8c8pw30dxyyryvzrb55eis12389r9y",
  "insertion": {
    "when": "2024-06-01T09:03:05.711Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=6423/can-i-set-arrow-thickness-on-a-component-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam arrowThickness 0.4
class c1
c1 --> c2
c1 -[thickness=5]-> c4
@enduml
