{
  "sha1": "f8vfymhq0e74bjjt41xy80p531ved5",
  "insertion": {
    "when": "2024-06-01T09:03:05.771Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam LegendBackgroundColor #lightyellow  
skinparam LegendBorderThickness 4

legend bottom
<b>REQUIRED ITEMS</b>

<#blue,#red>|=  Step  |=  Date  |=  Name  |=  Status  |=  Link  |
<#green>|  1.1  |  TBD  |  [[https://www.asdasd.com/apps/documents/items/1965 ABC]]  |<color:black>  <b>Unknown  |   |
endlegend

center footer %n()Last Updated:  February 15, 2018  -  12:40 pm  (EST)
@enduml
