{
  "sha1": "ca7kh0neovqva69gc7xdcmisuehhw4x",
  "insertion": {
    "when": "2024-06-01T09:03:01.127Z",
    "url": "http://forum.plantuml.net/9405/stereotype-note-over-multiple-participants-is-crashing",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
<style>
note {
  fontColor red
}
</style>
participant A
participant B
note over A, B : test
@enduml
