{
  "sha1": "casfqf0og2md6hcav5w3hhrf56tnt6",
  "insertion": {
    "when": "2024-06-01T09:03:01.152Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|swinlane1|
start
if (foo) then
  |swinlane2|
  :f1;
endif
|swinlane1|
:f001;
|swinlane2|
:f2;
if (test2) then
|swinlane1|
  :t1;
else
|swinlane2|
  :t2;
endif
|swinlane1|
:f3;
@enduml
