{
  "sha1": "2yzda6qvr1cujnuw2x6bqe5zx0wrqf7",
  "insertion": {
    "when": "2024-06-20T20:26:36.939Z",
    "url": "https://github.com/plantuml/plantuml/issues/1824",
    "user": "The-Lum"
  }
}
@startcreole
<math>
a^2
-
4ab
</math>
@endcreole
