{
  "sha1": "lunpcxb8dx8zv2iq6afn26zp9pqbrxu",
  "insertion": {
    "when": "2024-05-30T20:48:21.250Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19

<style>
timeline {
    BackGroundColor Grey
    FontName Helvetica
    FontSize 20
    FontColor Blue
}
</style>

[Prototype design] as [TASK1] lasts 38 days
[TASK1] is colored in Lavender/LightBlue
[Prototype completed] happens at [TASK1]'s end

@endgantt
