{
  "sha1": "70nww4ffjbs1k859qyzgargcn6hu3mz",
  "insertion": {
    "when": "2024-05-30T20:48:21.094Z",
    "url": "https://github.com/plantuml/plantuml/issues/1224#issuecomment-1362055648",
    "user": "plantuml@gmail.com"
  }
}
@startuml
nwdiag {
  network Sample_front {
    address = "192.168.10.0/24"
    color = "blue"

    test_address [address = " .1,  .5", color = "#aaffaa"]
    test_color [address = ".2", color = "lightblue"]
    test_description [address = ".3", description = "<color:green>Description #3 ", color = "#00000000"]
    test_shape [address = ".4", shape = "node", color = "transparent"]
  }
}
@enduml
