{
  "sha1": "i61zuws1k0aarv04br7wrvljynkg9h8",
  "insertion": {
    "when": "2024-06-03T18:59:30.380Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
sprite $strategy-value-stream jar:archimate/strategy-value-stream
skinparam rectangle {
	roundCorner 25
}
rectangle "Strategy stream"  as SS <<$archimate/strategy-value-stream>>

legend left
<$strategy-value-stream>:strategy-value-stream
endlegend

@enduml
