{
  "sha1": "i6vbx4nl722aj12ymtrbk46q9k19ook",
  "insertion": {
    "when": "2026-03-17T18:09:30.929Z",
    "url": "https://github.com/plantuml/plantuml/issues/2586",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
.mystyle {
  linecolor: blue
  linethickness: 3
}
</style>

json n0 42
json n1 true
n0 -> n1 <<mystyle>> : label
@enduml
