{
  "sha1": "d3hc1ozgjern82jpxftz6w42oilcr4e",
  "insertion": {
    "when": "2024-06-01T09:03:02.465Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

(*) --> "toto"
note left
  this is
  a long
  <b>note</b>
 end note
--> "titi"
note on link: this is a note

@enduml
