{
  "sha1": "d3yum3pqvair1sqwxicei3zz3rpd4kn",
  "insertion": {
    "when": "2024-06-01T09:03:02.473Z",
    "url": "https://forum.plantuml.net/11052/remove-unlinked-components?show=11133#c11133",
    "user": "plantuml@gmail.com"
  }
}
@startuml
together {
}
class foo
remove @unlinked
@enduml
