{
  "sha1": "r96pbcsfv9uz4skilgy1vowr6kehvqb",
  "insertion": {
    "when": "2024-06-04T17:28:43.475Z",
    "url": "http://forum.plantuml.net/7859/partition-are-compacted-distributed-over-multiple-swinlane",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|p1|
start
partition testP {
:on p1;
|p2|
:on p3;
note right
this is a long text note to have much bigger size on p3
end note 
}
@enduml
