{
  "sha1": "r9h5sqok0zqpjxyi0ly1jcjg9rimjzf",
  "insertion": {
    "when": "2026-02-03T22:38:56.204Z",
    "url": "https://github.com/plantuml/plantuml/pull/2499",
    "user": "plantuml@gmail.com"
  }
}
@startuml
clock "Clock" as clk with period 1
binary "Enable" as EN

@0
EN is low

@2
EN is high

@3
EN is low
@enduml
