{
  "sha1": "eq7nmdiesz8ki3mchzved90lypap2ts",
  "insertion": {
    "when": "2024-06-01T09:03:04.918Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!definelong SEND_TO_b(from,message)
  from -> b : MYPROT:%n()##message
!enddefinelong
 
!define SEND_FROM_a_TO_b(message) SEND_TO_b(a,message)
 
SEND_TO_b(a,Hello)    'Works fine
'Does not work
SEND_FROM_a_TO_b(Hi)
@enduml
