{
  "sha1": "eqr5pz7tvv3l2c8uhahftnirwddpi0z",
  "insertion": {
    "when": "2024-06-01T09:03:04.967Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] lasts 13 days
[Test prototype] ends at [Prototype design]'s end
[Test prototype] lasts 4 days
@endgantt
