{
  "sha1": "8ud2f2dd5fg1hg1lqb0u4q1jb7nipt",
  "insertion": {
    "when": "2024-05-30T20:48:21.526Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
User << Human >>
:Main Database: as MySql << Application >>
(Start) << One Shot >>
(Use the application) as (Use) << Main >>

User -> (Start)
User --> (Use)

MySql --> (Use)

@enduml
