{
  "sha1": "5sprl5gbhoy5ficzz55anvwxtptb8i1",
  "insertion": {
    "when": "2024-05-30T20:48:20.798Z",
    "url": "http://forum.plantuml.net/9333/why-queue-a-as-a-notation-fails",
    "user": "plantuml@gmail.com"
  }
}
@startuml
queue "name" as code {

}
@enduml
