{
  "sha1": "mc8wcb2ahd8q93tn51hvq3mzovossij",
  "insertion": {
    "when": "2024-06-03T18:59:35.081Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam componentStyle uml2
node "System%n()Controller%n()box"
database "%n()PostgreSQL%n()database%n()" as DB
@enduml
