{
  "sha1": "7qgm220idz0ulo0bsgpzmd4m0d2cbwi",
  "insertion": {
    "when": "2024-05-30T20:48:21.258Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

        class PragmaStringMultiTest {
            {field} + p1 
            __
            {method} + myMethod
        }
        note left of PragmaStringMultiTest
            This note corrupts the link
            between PragmaStringMultiTest
            and MyItem. Remove the note
            and the link will be OK.
        end note

        class MyItem {
            {field} + MyProp 
            __
            {method} + MyItem 
        }

    MyItem "1" -left- PragmaStringMultiTest
@enduml
