{
  "sha1": "7qqd1tbfeshosvyoj33l7u5tx31jdxl",
  "insertion": {
    "when": "2024-05-30T20:48:21.262Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
partition "Iteration (Over each day of the week)"
(*) --> "Lookup last time temporal processing ran" as A1
end partition

partition cspTemporalProcessor_GetScheduledPaymentsToProcess #LightSkyBlue
A1 --> "Lookup scheduled payments to process" as A2
note right: Parameters and result set
end partition
@enduml
