{
  "sha1": "spl9iafexcv08itkuglvnrcjos1h0ua",
  "insertion": {
    "when": "2024-06-04T17:28:45.319Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
namespace classic.collections {
  java.lang.Object <|-- ArrayList
}

namespace net.sourceforge.plantuml {
  class ArrayList
  classic.collections.ArrayList <|-- ArrayList
}
@enduml
