{
  "sha1": "efq79n14vf2eir6c3b5vxphjvzghb53",
  "insertion": {
    "when": "2024-06-01T09:03:04.356Z",
    "url": "http://forum.plantuml.net/7172/componentbordercolor-does-not-work-for-all-notations",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam backgroundColor lightBlue
skinparam componentBorderColor red
component 1 {
}
[2] as Comp2
component 3 {
[4] as Comp4
}

@enduml
