{
  "sha1": "rgr7x1zivwpkdyc62zmew8jpb7bn0tq",
  "insertion": {
    "when": "2024-06-04T17:28:43.813Z",
    "url": "http://forum.plantuml.net/8368/hidden-not-working-with-arrow-direction-component-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package AAAA {
   component C1
   component S1
   component S2
   C1 -left- S1
   C1 -[hidden]- S2
'Remove next line comment
S1 -[hidden]left- S2
}
@enduml
