{
  "sha1": "180wr5tl3vhngagket03n3dy3vo4fgp",
  "insertion": {
    "when": "2024-05-30T20:48:19.594Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Bob -> Alice : hello
create Dog
Alice -> Dog : create
note right : this is right and very very long
Alice -> Toto : hello
@enduml
