{
  "sha1": "4rgeaq9lpig374q0pvyjs7di2qf4629",
  "insertion": {
    "when": "2026-03-01T21:49:11.488Z",
    "url": "https://github.com/plantuml/plantuml/issues/589",
    "user": "plantuml@gmail.com"
  }
}
@startuml
partition p
a->b
end

group
a->c
end group
@enduml
