{
  "sha1": "t1xuvezh4i1msqvn2ez2fiks2p0cxhd",
  "insertion": {
    "when": "2024-06-04T17:28:45.705Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=1831/border-thickness&show=5059#c5059",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam diagramBorderRoundCorner 15
skinparam diagramBorderColor black
title My Title
Bob -> Alice : hello
@enduml
