{
  "sha1": "mncuxkcmje4rjdwxh122ougjnih0zvp",
  "insertion": {
    "when": "2024-06-03T18:59:35.445Z",
    "url": "https://gist.github.com/rxaviers/7360908",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Alice -> Bob : <#0:2630:><#F00:2630:>
Alice -> Bob : <#F00:recycle:>
@enduml
