{
  "sha1": "ylvt3ihocwdm8n63sgwhwzv2nn8ro8",
  "insertion": {
    "when": "2024-06-04T17:28:47.008Z",
    "user": "plantuml@gmail.com"
  }
}
@startsalt
{
{# This is my title }
{* File | Edit | Source
Edit|Copy
Edit|Paste
Edit|Cut
}
1
2
3
4
5
6
7
}
@endsalt
