{
  "sha1": "no12t2w45v0gt8ksjqmwj9x5pttunl2",
  "insertion": {
    "when": "2024-05-30T20:48:19.922Z",
    "url": "https://forum.plantuml.net/14458/nwdiag-issue-other-internal-networks-with-the-layout-engine",
    "user": "plantuml@gmail.com"
  },
  "humhash": "tipibu-04-cufe371"
}
@startnwdiag
nwdiag {
  network LAN2 {
     switch;
  }
  switch -- equip;
  equip [address = "e3"];
}
@endnwdiag
