{
  "sha1": "94l0ex7o91rjqwplz0nr0nhhiliwyg3",
  "insertion": {
    "when": "2024-05-30T20:48:20.470Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:start2 on; <<#AAAAAA;line:blue;text:red>>
@enduml
