{
  "sha1": "94rj22ubiclp5gkm1qllo65olwk29v6",
  "insertion": {
    "when": "2024-09-09T15:24:34.392Z",
    "url": "https://forum.plantuml.net/13066",
    "user": "The-Lum"
  }
}
@startjson
[
"\\\\",
"\\n",
"\\r",
"\\t"
]
@endjson
