{
  "sha1": "ogef1jtf5pt0mc6puxnyabdkp4q9t64",
  "insertion": {
    "when": "2025-06-11T17:10:47.474Z",
    "url": "https://github.com/plantuml/plantuml/pull/2229",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
start {
    LineColor #red
    LineThickness 5
}
stop {
    LineColor #green
    LineThickness 5
}
end {
    LineColor #blue
    LineThickness 5
}
</style>
start
stop
end
@enduml
