{
  "sha1": "cdsyuap2e94klguapxfecsufzmrz66k",
  "insertion": {
    "when": "2024-06-01T09:03:01.309Z",
    "url": "https://github.com/plantuml/plantuml/issues/62",
    "user": "plantuml@gmail.com"
  }
}
@startuml
salt
{
{#
A | B
C | D
}
}
@enduml
