{
  "sha1": "cdugjgsja8avwgqc9lyh2x2nhf5ro5y",
  "insertion": {
    "when": "2024-06-01T09:03:01.316Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Alice -> Bob : message 1
Alice -> Bob : message 2
newpage
Alice -> Bob : message 3
Alice -> Bob : message 4
newpage A title for the%n()last page
Alice -> Bob : message 5
Alice -> Bob : message 6
@enduml
