{
  "sha1": "kyeg841hnzsrkys5nf185s2kitkjj0i",
  "insertion": {
    "when": "2024-06-03T18:59:33.478Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma layout smetana

(*) --> if "" then
 ->[cas1] cas1
else
 -->[cas2] cas2
endif

-left->[cas3] azerty

@enduml
