{
  "sha1": "l96w0rojejj2950bsp3d16a3qzld29z",
  "insertion": {
    "when": "2024-06-03T18:59:33.884Z",
    "url": "https://github.com/plantuml/plantuml/issues/193",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start

:And so it begins;

if (Testing las arrow of\na Switch-case activity\nit breaks when this \nelement gets 3 lines or more) then (Yes)
elseif (Testing las arrow of\na Switch-case activity\nit breaks when this \nelement gets 3 lines or more) then (Yes)
else (No)
	:**Show Error**;
	end
endif

:And there is no\nactivities for the YES branches;

stop
@enduml
