{
  "sha1": "l24hsozm1z8lxww6or3aq63hmitg64a",
  "insertion": {
    "when": "2024-06-03T18:59:33.597Z",
    "url": "https://forum.plantuml.net/14529/activity-style-allow-style-diamond-internal-label-external?show=14744#c14744",
    "user": "plantuml@gmail.com"
  }
}
@startuml
scale 1.5
<style>
activityDiagram {
  diamond {
    FontColor green
  }
}
</style>
switch (x)
case (a)
   :1;
case (b)
   :2;
case (c)
   :3;
case (d)
   :4;
endswitch
@enduml
