{
  "sha1": "l2nx7kjedwzu6yews3xun8bhvov8rro",
  "insertion": {
    "when": "2024-06-03T18:59:33.625Z",
    "url": "http://blockdiag.com/en/nwdiag/nwdiag-examples.html",
    "user": "plantuml@gmail.com"
  }
}
@startuml
nwdiag {
  network Sample_front {
    address = "192.168.10.0/24";
      web01 [address = ".1"];
      web02 [address = ".2"];
  }
  network Sample_back {
    address = "192.168.20.0/24";
    web01 [address = ".1"];
    web02 [address = ".2"];
    db01 [address = ".101"];
    db02 [address = ".102"];
  }
}
@enduml
