{
  "sha1": "claxqyys62nbnausunsgxbhe1dxxcqk",
  "insertion": {
    "when": "2024-06-01T09:03:01.635Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
group coif {
rectangle position=(45,0) dimension=(56,50) color=#0093C7 curve=20
}
group body {
rectangle position=(110,0) dimension=(60,93) color=#00BAEE curve=30
triangle position=0,0 points=(130,0^20)~0.1~(130,93^1)~0.1~(0,93^30)~3~ color=#00BAEE
circle position=(142,27) color=white radius=13 
}
group wing {
cheese color=#0093C7  radius=100 start=90 end=180 position=(100,100)
cheese color=#0093C7  position=(100,150) radius=50 start=270 end=90
}
group feet {
stick color=#FD8150 position=(10,0) dimension=(5,15)
stick color=#FD8150 position=(20,0) dimension=(5,15)
stick color=#FD8150 position=(2,10) dimension=(30,5)
}
group noz {
triangle position=(0,0) points=0,0:(100,70,60):(0,70) color=#FF7645
}
noz position=(165,50) scale=0.5
coif position=(55,10) scale=1
feet position=(80,110) scale=2.5
body position=(0,30)
wing position=(80,44) scale=0.35
@endcute
