{
  "sha1": "sei2mf3jh8j8anlizmxrwfd1jiwuasc",
  "insertion": {
    "when": "2024-06-04T17:28:45.037Z",
    "url": "https://github.com/plantuml/plantuml/issues/104#issuecomment-1368253645",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
element {
  MaximumWidth 100
}
</style>

:this is a very long long long long long activity description;
@enduml
