{
  "sha1": "fi2o7ywizbe3jva94atb7gsguwyixrf",
  "insertion": {
    "when": "2024-06-01T09:03:06.179Z",
    "url": "http://www.redblobgames.com/grids/hexagons/",
    "user": "plantuml@gmail.com"
  }
}
@startuml
colors
@enduml
