{
  "sha1": "fio6xq2xahhizuyhzecilpxlz8lt0e9",
  "insertion": {
    "when": "2024-06-01T09:03:06.200Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2
!ijk = 'foo'
Alice -> Bob : You should see foo and not bar
!if ijk == 'bar'
Alice -> Bob : bar
!elseif ijk == 'foo'
Alice -> Bob : foo
!endif
Alice -> Bob : B
@enduml
