{
  "sha1": "thfbicmnhe3o8z3mljakxzgiznqy2xx",
  "insertion": {
    "when": "2024-06-04T17:28:46.235Z",
    "url": "https://forum.plantuml.net/11895/embed-sub-diagrams-all-type-especially-mindmap-type-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] lasts 3 days
[Test prototype] starts at [Prototype design]'s end
[Test prototype] lasts 4 days

legend
{{wbs
* root
** level1
** level1
}}
{{mindmap
* root
** level1
** level1
}}
{{salt
{
  Login    | "MyName   "
  Password | "****     "
  [Cancel] | [  OK   ]
}
}}
end legend
@endgantt
