{
  "sha1": "mpl0md9nt07dbl2cyvda5nx9nh8makm",
  "insertion": {
    "when": "2024-06-03T18:59:35.489Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
rectangle position=70,0 dimension=50,130 color=#00E087 curve=10
'triangle position=10,60 points=(100,0):(100,50):(0,50) color=#00C377
@endcute
