{
  "sha1": "lljl8llf5f310wqij4irk6kqszpevt8",
  "insertion": {
    "when": "2024-06-03T18:59:34.271Z",
    "url": "https://github.com/plantuml/plantuml/issues/624",
    "user": "plantuml@gmail.com"
  }
}
@startuml
p ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
@enduml
