{
  "sha1": "nc8uf2mrb2i6syowt9hfpschs72h6q6",
  "insertion": {
    "when": "2024-06-04T17:28:38.425Z",
    "url": "https://github.com/plantuml/plantuml/issues/867",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam Dpi 00
'https://plantuml.com/sequence-diagram

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response
@enduml
