{
  "sha1": "m44et1wfibpfqios0jpw33ve0ulngmq",
  "insertion": {
    "when": "2024-06-03T18:59:34.859Z",
    "url": "https://github.com/plantuml/plantuml/issues/1405",
    "user": "plantuml@gmail.com"
  }
}
@startuml
note as n
    my note
end note

note as X.n
    my enother note
end note
@enduml
