{
  "sha1": "kg39mj0dhsmmuskju9n9ex9b6zdr9q7",
  "insertion": {
    "when": "2024-06-03T18:59:32.957Z",
    "url": "https://forum.plantuml.net/14407/differences-between-png-outputs-circles-json-yaml-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startjson
[
  [],
  [[]],
  []
]
@endjson
