{
  "sha1": "kgdswojcdqjx61qqvulnrg3oikghebz",
  "insertion": {
    "when": "2024-06-03T18:59:32.964Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Bob -> Alice : hello

create Other
Alice -> Other : new

create control String
Alice -> String
note right : You can also put notes!

Alice --> Bob : ok
@enduml
