{
  "sha1": "h8zmj9ntd3z9yxsxz3f5lq2lmjqv3nl",
  "insertion": {
    "when": "2024-06-03T18:59:29.292Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

Alice -> Bob : hello
Alice ->o Bob : hello
Alice ->>o Bob : hello
Alice -\o Bob : hello
Alice -/o Bob : hello
Alice -\\o Bob : hello
Alice -//o Bob : hello

Alice o<-- Bob : ok
@enduml
