{
  "sha1": "euspsukxqg2qoz0xf38u9qv3tj1c4jw",
  "insertion": {
    "when": "2024-06-01T09:03:05.127Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

Import o-- Cycle : est compose de plusieurs
Cycle --> "1" Vehicule
Cycle --> "1" Pneumatique
Import --> "1" Vehicule
Import --> "1" Pneumatique
Analyse --> Rapport : Peut generer
Rapport o-- Cycle : Porte sur

@enduml
