{
  "sha1": "qxhl6cdb2eebwu81nevskkwp4t4i1cg",
  "insertion": {
    "when": "2024-06-04T17:28:43.042Z",
    "url": "https://forum.plantuml.net/16397/add-qualified-associations-to-class-diagrams?show=16642#c16642",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma svek_trace on
class class1
class class2

class1 [Qualifier] *-- class2
@enduml
