{
  "sha1": "qxr3ka9i8igr13l10czkgbnla4l4i3k",
  "insertion": {
    "when": "2024-06-04T17:28:43.057Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
repeat
    :Do something;
    if(Decide something) then (Yes with a very long comment which may cause an issue)
        :Repeat something;
    else (No)
        :Finish something;
        end
    endif
repeat while
@enduml
