{
  "sha1": "f0lzauvn7xc8zq2wvlmljpav1kfj55h",
  "insertion": {
    "when": "2024-06-01T09:03:05.353Z",
    "url": "https://github.com/plantuml/plantuml/issues/242",
    "user": "plantuml@gmail.com"
  }
}
@startuml
artifact Foo1 {
  folder Foo2
}

folder Foo3 {
  artifact Foo4
}

frame Foo5 {
  database Foo6
}

cloud vpc {
  node ec2 {
	stack stack
  }
}
@enduml
