{
  "sha1": "5csmgcexyuer2kuv7o4d7mednhy5mcm",
  "insertion": {
    "when": "2025-04-07T15:00:17.509Z",
    "url": "https://github.com/plantuml/plantuml/pull/2139",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:begin;
:object2; <<object>>
:end;
@enduml
