{
  "sha1": "wzs2z30eq8dh4ip04w6mwqn35vgl7r",
  "insertion": {
    "when": "2024-06-04T17:28:46.936Z",
    "url": "https://github.com/plantuml/plantuml/issues/1465#issuecomment-1597648143",
    "user": "plantuml@gmail.com"
  }
}
@startuml
binary "A" as a
@0
a is low
@1
a is high
@2
a is low
@enduml
