{
  "sha1": "7l50n8gmb7b6nyhsmccd4psoo0ivrkv",
  "insertion": {
    "when": "2024-06-01T09:03:07.547Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|Fournisseur|
start
:initiate switch() ; <<#01DF01>>
:VerifierRecevabiliteCHF(); <<#01DF01>>
|Web Service|
if (PCE connu) then (non)
|Fournisseur|
:statut 022;
stop
else (oui)
|Web Service|
endif
if (Validee) then (non)
|Fournisseur|
:statut 023;
stop
endif 
|Web Service|
while (Besoin RdV)
|Fournisseur|
:statut 045;
|Web Service|
if (Date disponible) then (oui)
:envoi heures du creneau;
|Fournisseur|
if (Confirmation) then (oui)
:AccepterRdV(); <<#01DF01>>
:Statut 063;
Stop
else (non)
endif
else (non)
|Web Service|
:envoi de liste de disponibilites;
|Fournisseur|
while (changement de liste)
:demanderPrecSuiv(); <<#01DF01>>
|Web Service|
:recuper nouvelle liste;
endwhile (liste OK)
endif
|Fournisseur|
:ProposerDatePlage(); <<#01DF01>>
endwhile (Pas de RdV)
:Statut 050;
stop
@enduml
