{
  "sha1": "imy6w5nty9wnfqik0c2q74dchxwz4s6",
  "insertion": {
    "when": "2024-06-20T20:28:15.894Z",
    "url": "https://github.com/plantuml/plantuml/pull/1827",
    "user": "The-Lum"
  }
}
@startcreole
<math>a^2 newline a^3</math>
@endcreole
