{
  "sha1": "6dj0f7i2zsgyqz6yzj5nrzqavxclju8",
  "insertion": {
    "when": "2024-05-30T20:48:20.930Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
 skinparam stateBackgroundColor<<Acacia>> green
  skinparam stateBackgroundColor<<Midge>> red
  skinparam stateBackgroundColor<<Weavil>> orange

 [*] --> ma

  state "midgeAdult" as ma <<Midge>> #green {
  	state Foo1 <<Weavil>>
    [*] --> Foo1
  } 
  
  [*] --> Foo1
  
@enduml
