{
  "sha1": "7tzgzy18017k5qywdcr8b52z0htxa0j",
  "humhash": "xosuri-16-dete303",
  "insertion": {
    "when": "2026-07-25T16:32:32.634Z",
    "url": "https://github.com/plantuml/plantuml/issues/2788",
    "user": "plantuml@gmail.com"
  }
}
@startuml
x -> x: start
group test
a -> b: 1
c -> c: 2
end
d -> d: next
@enduml
