{
  "sha1": "1dordjglf2b1apkaiaqldrj11tj7e6v",
  "insertion": {
    "when": "2024-05-30T20:48:19.650Z",
    "url": "https://forum.plantuml.net/15458/default-line-colors-are-not-supported-anymore",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam arrow {
    Color green
    FontColor green
}

skinparam arrow<<orangeText>> {
    Color ;text:orange;line.dotted
}

skinparam arrow<<orangeLine>> {
    Color orange;line.dashed
}

skinparam arrow<<origGreen>> {
    Color ;line.dashed
}


rectangle "==A" <<person>> as a
rectangle "==S" <<system>> as s
rectangle "==E" <<external_system>> as e

a -->> s <<orangeText>> : **orange text**
s -->> e <<orangeLine>> : **orange line**
a -->> e <<origGreen>> : **origGreen**
@enduml
