{
  "sha1": "jayyd15pb0gdyw7zjy7b1lz9qloa3km",
  "insertion": {
    "when": "2024-06-03T18:59:31.663Z",
    "url": "https://forum.plantuml.net/14554/style-state-allow-fontcolor-style-on-state",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
root {
  FontColor green
}
state {
  FontColor red
  BackGroundColor yellow
  LineColor violet
}
</style>
title How to change fontcolor by style?
state A {
  state B {
  }
  state C {
    state c : state c
  }
  c --> b
}
 
state S1 : state S1
state S2

@enduml
