{
  "sha1": "gq1hbnfzsf3lhbt5dpvhv29v2ssz7iq",
  "insertion": {
    "when": "2026-03-17T18:09:30.922Z",
    "url": "https://github.com/plantuml/plantuml/issues/2518",
    "user": "plantuml@gmail.com"
  }
}
@startuml
+ class A {}
@enduml
