{
  "sha1": "gqrjdjq6c9j0wz6kto7yi72ptpbnh30",
  "insertion": {
    "when": "2024-06-01T09:03:08.189Z",
    "url": "https://forum.plantuml.net/14976/style-deployment-diagram-cant-get-style-to-work",
    "user": "plantuml@gmail.com"
  }
}
@startuml
hide stereotype
<style>
document {
    BackgroundColor LightGreen
}

interface {
  BackGroundColor #ff3311
  Shadowing 0
}
</style>
circle test
package {
    circle ME100 <<failedval>>
    circle ART213
    ME100 -d-> ART213
}
@enduml
