{
  "sha1": "b5kd4u1p66lij6fuo1e9j5ybi2zgj5s",
  "insertion": {
    "when": "2025-12-05T20:00:28.836Z",
    "url": "https://github.com/plantuml/plantuml/pull/2452",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
*
	*
		*
		*
	*
@endmindmap
