{
  "sha1": "sumugvtjjkr4g00ko1x9kwmobkrgl24",
  "insertion": {
    "when": "2024-06-04T17:28:45.486Z",
    "url": "https://forum.plantuml.net/12022/nwdiag-diagram-networks-broken-observe-cloud-plantuml-version",
    "user": "plantuml@gmail.com"
  }
}
@startuml
nwdiag {
  inet [shape = cloud];
  inet -- router;

  network {
    router;
    web01;
    web02;
  }
}
@enduml
