{
  "sha1": "kv5i1oinipj9yp2vh3es4dd02ko4uu7",
  "insertion": {
    "when": "2024-06-03T18:59:33.392Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam topurl http://www.google.com

participant Bob [[/search]]
participant Alice [[http://www.sf.net{This is alice}]]
Bob -> Alice : ok

@enduml
