{
  "sha1": "kvkwnrbnp3rb74c5rbq8tltc39e0uee",
  "insertion": {
    "when": "2024-05-30T20:48:20.474Z",
    "url": "https://forum.plantuml.net/12177/change-color-of-salt-button-to-represent-disabled-status",
    "user": "plantuml@gmail.com"
  },
  "humhash": "jukuta-370-dolepu"
}
@startsalt
skinparam Handwritten  true
{^
My Label | ^Dropdown item    ^ 
[My Button] | *
[<color:#9a9a9a>My Button] | *
. | . 
. | . 
}
@endsalt
