{
  "sha1": "je97u2bugs8rapl2c2mv7ik8h304ptq",
  "insertion": {
    "when": "2024-06-03T18:59:31.782Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2

!function id($text)
!return $text
!endfunction

!function id($text1, $text2)
!return $text1 + $text2
!endfunction

!function id($text1, $text2)
!return $text1 + $text2
!endfunction


alice -> bob : id("aa")
alice -> bob : id("ab", "cd")
@enduml
