{
  "sha1": "b6fcdvanpxk8ou2swnpa6k9c6qboehr",
  "insertion": {
    "when": "2024-05-30T20:48:22.026Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
usecase "Modeliser\nles\nprojets" as UC1
component compo <<testable>>
interface inter
actor "Le Fameux Toto" as toto
note top of compo: ceci est un grand composant
note bottom of toto: Cet acteur\nest essentiel
toto --> UC1
compo-->compo : essai
@enduml
