{
  "sha1": "8npipd7pne1wv1f2bezr6qvp6fr9f3y",
  "insertion": {
    "when": "2024-05-30T20:48:21.470Z",
    "url": "https://forum.plantuml.net/11109/preprocessor-vlookup-macro?show=11132#c11132",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!$data={"partlen": "2", "game": "GamePlantuml", "participants": [
{"name": "XYZ" ,"as": "xyz", "team": "A"},
{"name": "RST" ,"as": "rst", "team": "B"},
{"name": "UVW" ,"as": "uvw", "team": "B"}],
"color": {"A": "red", "B": "blue"}
}

:a;
!foreach $part in $data.participants
  :$part.name as $part.as;
  :1 access to json: [$data.color.A, $data.color.B] $part.team -> $data.color of $part.team;
  :2 access to json: [$data.color.A, $data.color.B] $part.team -> $data.color[$part.team];
  !$c=$data.color[$part.team]
  :3 access to json, **with var**: $part.team -> $c;
!endfor
:b;
@enduml
