{
  "sha1": "tqflbypgxv84z3guwhohe6h4w85uh48",
  "insertion": {
    "when": "2024-06-04T17:28:46.614Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
cheese color=red radius=100 position=100,100 start=15 end=195
@endcute
