{
  "sha1": "em9d9dgncsr1j7vjg5rharj69eovvzl",
  "insertion": {
    "when": "2024-06-01T09:03:04.690Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "vunumo-43-buli848"
}
@startregex
A(?<=abc)BC(?<!not)DE
@endregex
