{
  "sha1": "5douvig9b6t1nerkiy6wzr5vtkppghg",
  "insertion": {
    "when": "2024-06-04T17:28:43.624Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] requires 15 days
[Test prototype] requires 10 days

[Prototype design] ends D+14
[Test prototype] ends D+24
@endgantt
