{
  "sha1": "jrak3ybb8jog2wf2gnyyjmdxjh9ianq",
  "insertion": {
    "when": "2024-06-03T18:59:32.132Z",
    "url": "https://github.com/plantuml/plantuml/issues/1538",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
.color {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>

repeat
  :Generate diagrams1; <<save>> <<color>>
backward:Log context2; <<save>> <<color>>
repeat while (more data?) is (yes)



@enduml
