{
  "sha1": "ou2q67y9yyds7yuh40vh3h4ikhqjqeo",
  "insertion": {
    "when": "2024-06-01T09:03:05.193Z",
    "url": "https://forum.plantuml.net/11892/scale-not-honoured-in-gantt-chart",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2020-07-01
scale 200 width
[Prototype design] lasts 15 days
[Test prototype] lasts 10 days

[Prototype design] starts 2020-07-01
[Test prototype] starts 2020-07-16
@endgantt
