{
  "sha1": "n8o31y4xar7lw2mcbb7c545yqbvdmf9",
  "insertion": {
    "when": "2024-08-28T16:43:33.561Z",
    "url": "https://github.com/plantuml/plantuml/issues/1871",
    "user": "plantuml@gmail.com"
  }
}
@startuml

alice->bob:ok
note right
    title
    ----
    content
end note


@enduml
