{
  "sha1": "ba3dogcjnmu35avjhyr9wcaoenrp646",
  "insertion": {
    "when": "2024-05-30T20:48:22.050Z",
    "url": "https://forum.plantuml.net/11130/is-there-a-compact-timing-diagram?show=11287#c11287",
    "user": "plantuml@gmail.com"
  }
}
@startuml
compact robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Waiting
WB is Idle

@200
WB is Proc.

@300
WB is Waiting

@500
WU is ok

@700
WB is Idle

@enduml
