{
  "sha1": "2m9qi0s2ogemqo1s9ewqh159zsxg9r7",
  "insertion": {
    "when": "2024-05-30T20:48:20.046Z",
    "url": "https://forum.plantuml.net/11192/json-structures-inside-a-function",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!$data={"participants" :[ 
{"id": "cm" ,"label": "customer master","desc": "manages customers"},
{"id": "tm" ,"label": "transaction manager","desc": "manages transactions"},
{"id": "am" ,"label": "account master","desc": "manages accounts"}
]
}


!unquoted function $lookup($id)
!foreach $part in $data.participants
  !if $part.id == $id
    !return "id=" + $part.id + " \nlabel=" + $part.label + " \ndesc=" + $part.desc + ";" 
  !endif
!endfor
!return "not found"
!endfunction

!$desc = $lookup("cm")
:$desc;
@enduml
