{
  "sha1": "2mrw716v4nzn29pc80im466yg3vth8k",
  "insertion": {
    "when": "2025-04-02T08:20:37.947Z",
    "url": "https://github.com/plantuml/plantuml/pull/2036",
    "user": "plantuml@gmail.com"
  }
}
@startregex  
language de
useDescriptiveNames true

\b\B  
@endregex  
