{
  "sha1": "jb3a2wzpm1v4011zoi3sfng9bx6s9jf",
  "insertion": {
    "when": "2024-06-03T18:59:31.677Z",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
top to bottom direction
top side

* count with a very long name
** 100
*** 101
*** 102
** 200
@endmindmap
