{
  "sha1": "jbd9cd8ceaxovnl5u6g49r687axrm62",
  "insertion": {
    "when": "2024-06-03T18:59:31.691Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'(*) --> ===B1===
[*] --> ===B1===
===B1=== --> Independant
===B1=== --> Etudiant
@enduml
