{
  "sha1": "jbuyq84f6yducwqgg74ylyaqw4njcrm",
  "insertion": {
    "when": "2024-06-03T18:59:31.705Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

scale 500 width
frame parameters{
  (beta) as "<latex>\beta</latex>"
  (alpha) as "<latex>\alpha</latex>"
}
beta -> alpha : relationship

@enduml
