{
  "sha1": "ji7bn9a1208carn63mppnn85bv71k2g",
  "insertion": {
    "when": "2024-06-03T18:59:31.929Z",
    "url": "https://github.com/plantuml/plantuml/issues/62",
    "user": "plantuml@gmail.com"
  }
}
@startsalt
{
{*
A | B
C | *
}
}
@endsalt
