{
  "sha1": "j6ad8oqryjb902s9s7mn9jm7g984zt0",
  "insertion": {
    "when": "2024-06-03T18:59:31.530Z",
    "url": "http://forum.plantuml.net/7710/teoz-and-%26-within-groups-is-not-working",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
group friends
Bob -> Alice : Secret
Alice -> Stacy : Rumors
end
@enduml
