{
  "sha1": "59apybz4eeoiyrz24htioooqi8bgsjt",
  "insertion": {
    "when": "2024-05-30T20:48:20.690Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days
[Test prototype] starts 3 days after [Prototype design]'s end
[Prototype design] is colored in Chocolate 
[Test prototype] is colored in Coral/Green 
@endgantt
