{
  "sha1": "59js8c77034oz5rlrg80q7zofrj2oag",
  "insertion": {
    "when": "2024-05-30T20:48:20.694Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days
[Test prototype] ends 3 days after [Prototype design]'s end
@endgantt
