{
  "sha1": "1a80tgpm0n8elylhn5xfahvnltx4u0b",
  "insertion": {
    "when": "2024-06-01T09:03:03.011Z",
    "url": "https://forum.plantuml.net/9741/define-%40append-broken",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!define fileServer <color:green><&folder>ho-itd-pbrcs05</color>
@pause
@a start
@a :===initialization
@a #create fileServer ; <<task>>
@a end
@enduml
