{
  "sha1": "s1cjid39swm995rb04dvig68jbs6faa",
  "insertion": {
    "when": "2024-06-04T17:28:44.552Z",
    "url": "https://forum.plantuml.net/17150/namespace-with-slashes-in-the-name",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set namespaceSeparator /
namespace  a/b/c {
   class "Object" as js/Object
}
@enduml
