{
  "sha1": "s1dccwb8n4q7j2ipos23snl37h1j3bt",
  "insertion": {
    "when": "2024-06-04T17:28:44.560Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2

skinparam guillemet false
!definelong COMP_TEXTGENCOMP(name)
[name] << Comp >>
interface Ifc << IfcTyoe >> AS name##Ifc
name##Ifc - [name]
!enddefinelong
COMP_TEXTGENCOMP(dummy)
 
@enduml
