{
  "sha1": "s1tofodj2hx16uzowbinblydkd6xkzb",
  "insertion": {
    "when": "2024-06-04T17:28:44.590Z",
    "url": "https://forum.plantuml.net/16644/style-allow-all-style-for-json-object?show=16712#c16712",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
json {
  BackGroundColor aliceblue
  LineColor blue
  LineThickness 2.0
  LineStyle 3
  FontColor blue
  FontSize 15
  FontStyle italic
  Margin 50
  Padding 100
}
</style>

json JSON {
  "text": "Lorem ipsum dolor sit amet, ...",
  "name": "component c1",
  "color": ["normal", "green", "red"],
  "visible": true,
  "user" : { "age": 23, "name": "John", "array": [1, 2, 3]},
  "version": "<b>version"
}
@enduml
