{
  "sha1": "sjgrrvo9sycw9kcyakwtabwrjsan7dh",
  "insertion": {
    "when": "2024-06-04T17:28:45.164Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

!definelong RAISE_ALARM(part,alarmname,message)
rnote over part
  <b>ALARM:</b> <&flag> alarmname
  MSG = message
end note
!enddefinelong

!definelong RAISE_ALARM2(part,alarmname,message)
rnote over part : <b>ALARM:</b> <&flag> alarmname%n()MSG = message
!enddefinelong

Bob->Alice : hello
RAISE_ALARM(Bob,ShoudNotHappenError,What is <b>this</b>?%n()Newlines are treated differently!)
rnote over Bob : example1
rnote over Bob : example2%n()line2
rnote over Bob
example3%n()line3
end note
RAISE_ALARM2(Bob,ShoudNotHappenError,What is <b>this</b>?%n()Newlines are treated differently!)

@enduml
