{
  "sha1": "pkc23c6o8cjxdtm3scx7jo8xv9ulfg0",
  "insertion": {
    "when": "2024-06-04T17:28:41.307Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    skinparam colorArrowSeparationSpace 2
    start
    -[#red;#blue;#green;#orange]-> Red:1\nBlue:\nGreen:3\nYellow:4;
    :do a;
   -[#red;#blue;#green;#orange]-> label;    
    if (test) then
       -[#green;#orange]->
        :do b;
       -[#green;#orange]->        
    else
        -[#red;#blue]->
        :do c;
         -[#red;#blue,dotted]->
    endif
    -[#red;#blue,dashed]->
    while(a)
       -[#red;#blue,dashed]->
       :something}
       -[#red;#blue,dashed]->   
    endwhile
  
   -[#red;#blue,dashed]->

   repeat
        -[#red;#blue,dashed]->
       :something}
       -[#red;#blue,dashed]->
   repeat while(a)is(b)
@enduml
