{
  "sha1": "f5i8a8zm1bf5acwadrsjy9swl12v4lf",
  "insertion": {
    "when": "2024-06-01T09:03:05.545Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
"Main Admin" as Admin
"Use the application" as (Use)

User -> (Start)
User --> (Use)

Admin ---> (Use)

note right of Admin : This is an example.

note "This note is connected\nto several objects." as N2
(Start) .. N2
N2 .. (Use)

@enduml
