{
  "sha1": "f5w8r4tv9jx0v3p3da8eh13hiy70k6g",
  "insertion": {
    "when": "2024-06-01T09:03:05.566Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
group body {
cheese color=green radius=100,0 start=5,15 end=90,5 position=70,100
}
rectangle color=black dimension=2,2
body position=10,10
@endcute
