{
  "sha1": "9yfghrwakoi868zhphipx3bkjq7hej9",
  "insertion": {
    "when": "2024-05-30T20:48:21.790Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
participant Customer_P2Y
participant DAW_P2Y
participant Customer_RMN
participant DAW_RMN

activate Customer_P2Y #red
activate Customer_RMN #FFBBBB
Customer_P2Y -> DAW_P2Y: Besoin_P2Y
& Customer_RMN -> DAW_RMN: Besoin_RMN

deactivate Customer_P2Y
deactivate Customer_RMN
@enduml
