{
  "sha1": "cq74qo21l0uclm9vaiu9lw7d2p7dp21",
  "insertion": {
    "when": "2024-06-01T09:03:01.885Z",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
caption figure 1
title My super title

* count
** 100
*** 101
*** 102
** 200

left side

** A
*** AA
*** AB
** B

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
