{
  "sha1": "jxwcs2ls4otm47agcx7o5qx3ffg5dir",
  "insertion": {
    "when": "2024-06-04T17:28:42.181Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:previous
 action; <<continuous>>
  while (repeat\nforever)
    :do it
    again;
  endwhile
  ->exit
  path;
  detach
  end
@enduml
