{
  "sha1": "if4nog7e8oz4qozx4xi43p81qeyip8",
  "insertion": {
    "when": "2024-11-23T15:35:39.081Z",
    "url": "https://forum.plantuml.net/19039/how-to-insert-newline-into-the-diagram-using-preprocessor",
    "user": "The-Lum"
  }
}
@startsalt
!function $myfunc()
  !$n = 4
  !$row = 0
  !$res = ""
  !while $row < $n
    !$column = 0
    !while $column < $n
      !$res = $res + "| "+ $row + "," + $column
      !$column = $column + 1
    !endwhile
    !$res = $res + %newline()
    !$row = $row + 1
  !endwhile
  !return $res
!end function

{#
$myfunc()
}
@endsalt
