{
  "sha1": "d9kcw0bx039ggvx6tobv8dzwh2ww9rr",
  "insertion": {
    "when": "2024-06-01T09:03:02.702Z",
    "url": "https://forum.plantuml.net/9774/conditional-drawing-of-box-participants-sequence-diagram?show=9802#c9802",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!$foo = { "name": "John", "age" : 30 }
Alice -> Bob : Do you know $foo.name ?
@enduml
