{
  "sha1": "g1gwe2um7srwy8xk5qcwf13xm4sfmm3",
  "insertion": {
    "when": "2024-06-01T09:03:07.006Z",
    "url": "https://github.com/plantuml/plantuml/issues/863",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma layout smetana

state state_7 {
[*] --> s
}


@enduml
