{
  "sha1": "7y3p070i4ruxue3p5o1e5h0gfqj27ug",
  "insertion": {
    "when": "2024-05-30T20:48:21.302Z",
    "url": "https://forum.plantuml.net/4957/why-not-to-support-nested-boxes-in-sequence-diagrams?show=4957#q4957",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
box "component"
    participant a
end box
  box "subcomponent"
    participant b
  end box
@enduml
