{
  "sha1": "dac73s386i6gd5jzxl0g0fcupk2hn1z",
  "insertion": {
    "when": "2024-06-01T09:03:04.624Z",
    "url": "https://forum.plantuml.net/14516/skinparam-shadowing-in-nwdiag",
    "user": "plantuml@gmail.com"
  },
  "humhash": "sixoxu-07-neba246"
}
@startnwdiag
nwdiag {
  network dc {
    server;
    internet;
  }
  internet [shape = cloud];
}

@endnwdiag
