{
  "sha1": "lk727o358r2lp0mcya6gkr9atpsp2cg",
  "insertion": {
    "when": "2026-03-08T21:21:03.330Z",
    "url": "https://github.com/plantuml/plantuml/issues/2586",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
.mystyle {
  linecolor: blue
  linethickness: 3
}
</style>

map n0 {
}
map n1 {
}
n0 -> n1 <<mystyle>> : label
@enduml
