{
  "sha1": "5j8xz9a63fgzhykyjj1xcd3kcylksnz",
  "insertion": {
    "when": "2024-05-30T20:48:20.750Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Foo1
class Foo2
hide Foo1
class Foo3
Foo2 *-- Foo3
hide Foo3
@enduml
