{
  "sha1": "intrh4qj65mvqgg3rq268y6631nnp8o",
  "insertion": {
    "when": "2024-06-03T18:59:30.986Z",
    "url": "https://github.com/plantuml/plantuml/issues/104",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam wrapWidth 50


legend top
This is a very very very very very very very very very very very very very very long legend description
end legend


Alice->Bob: hello
Bob-->Alice: hello

note right
This is a very very very very very very very long note

WrapWidth doesn't work on sequence diagrams
end note
@enduml
