{
  "sha1": "ew8mwu2hpm3tkjtrmnmkn6he6qt1id6",
  "insertion": {
    "when": "2025-01-25T10:42:16.328Z",
    "url": "https://github.com/plantuml/plantuml/issues/1474",
    "user": "plantuml@gmail.com"
  }
}
@startuml
card "Foo%n()x%n()----%n()* y" as Foo {
  card Bar
}
@enduml
