{
  "sha1": "l7kdp9zvie8d4b7et7gwvskgvlox3od",
  "insertion": {
    "when": "2024-06-03T18:59:33.821Z",
    "url": "https://forum.plantuml.net/12415/gantt-issues-coloring-current-during-printscale-weekly-closed?show=13435#c13435",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
scale 2
printscale weekly
2020/10/26 to 2020/11/01 are colored in salmon
sunday are closed
saturday are closed

Project starts the 2020-10-15
[Prototype design] as [TASK1] lasts 25 days
[TASK1] is colored in Lavender/LightBlue
[Testing] lasts 5 days
[TASK1]->[Testing]


@endgantt
