{
  "sha1": "a79uveuxpt6z2qeyagj6xnak6gqvs0u",
  "insertion": {
    "when": "2024-05-30T20:48:21.834Z",
    "url": "https://github.com/plantuml/plantuml/issues/1212",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam lifelineStrategy solid

sys1 -> sys2: M1
sys1 <- sys2: M2
sys1 -> sys2: M3
sys1 <- sys2: M4
sys1 -> sys2: M5

@endum
