{
  "sha1": "4dldl790fql88pjaml5n851m0bsv06h",
  "insertion": {
    "when": "2024-05-30T20:48:20.478Z",
    "url": "https://forum.plantuml.net/16797/change-state-diagram-arrowhead-color",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
stateDiagram {
  arrow {
    LineColor blue
    HeadColor none
  }
}
</style>

state a
state b

a --> b

state c
state d

c <-- d

@enduml
