{
  "sha1": "u1rzlp567nlsg0qa6iz9iq78icj6ep",
  "insertion": {
    "when": "2024-06-04T17:28:46.842Z",
    "url": "https://github.com/plantuml/plantuml/issues/1538",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
.color {
  LineColor blue
  BackgroundColor lightCyan
  LineThickness 2
  ArrowThickness 0.5
  FontName Arial Narrow
  FontColor red
  FontSize 11
  FontStyle regular
}
</style>

split
:Only <<save>>;
repeat
  :Generate diagrams; <<save>>
backward:Log context; <<save>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>>
backward:Log
context; <<save>>
repeat while (more data?) is (yes)

split again
:<<save>> + <<color>>; <<color>>
repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log context; <<save>> <<color>>
repeat while (more data?) is (yes)

repeat
  :Generate diagrams; <<save>> <<color>>
backward:Log
context; <<save>> <<color>>
repeat while (more data?) is (yes)

end split
@enduml
