{
  "sha1": "dxh5lvwqv0e69krht1en84dkfriuvbm",
  "insertion": {
    "when": "2024-06-01T09:03:03.546Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
actor User
boundary API
database storage
User -> API
API -> storage
API <- storage
User <- API
@enduml
