{
  "sha1": "o6c04vjb2lkjrsynkzvnv0zip8dnzcm",
  "insertion": {
    "when": "2024-06-04T17:28:39.432Z",
    "url": "https://forum.plantuml.net/12550/differences-between-png-and-outputs-unicode-char-with-size",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma svgSize <U+1F610> XXXXX

test: text <U+1F610>
test_size25: text <size:25><U+1F610>
test_size75: text <size:75><U+1F610>
test_size100: text <size:100><U+1F610>
@enduml
