{
  "sha1": "jv68jxxjr63lzk6k0vrpku3o77nk3j1",
  "insertion": {
    "when": "2024-06-03T18:59:32.307Z",
    "url": "https://forum.plantuml.net/15606/activity-arrow-label-overlap-on-some-activity-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!t="this is t1%n()this is t2%n()this is t3%n()"

fork
->t;
  :action 1;
fork again
  :action 2;
end merge
@enduml
