{
  "sha1": "n62b6tnqwa91ytq42lnsd0cqyxbcu2h",
  "insertion": {
    "when": "2024-06-04T17:28:38.201Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
allow_mixing
!define MyBlue #6192d1
skinparam class {
  BackgroundColor white\MyBlue
}
skinparam database {
  BackgroundColor white\MyBlue
}
class dummy1 {
  foo1
}
database dummy2
@enduml
