{
  "sha1": "fvikc9o85qgocq0wt0keq59n2vhidjg",
  "insertion": {
    "when": "2024-06-01T09:03:06.783Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class dummy
toto1 ()-- dummy
toto2 ()-- dummy
toto3 ()-- dummy

dummy -() tutu1

dummy <|-- autre
@enduml
