{
  "sha1": "lz8wzxi3otb2j6mtledzb9ifn0qihyh",
  "insertion": {
    "when": "2024-06-03T18:59:34.676Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam classFontName Impact 
skinparam classFontColor red 

abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList

ArrayList : Object[] elementData
ArrayList : size()

enum TimeUnit
TimeUnit : DAYS
TimeUnit : HOURS
TimeUnit : MINUTES

@enduml
