{
  "sha1": "csx0n7qj4zmgahohlbjyu59isi7pvm9",
  "insertion": {
    "when": "2024-06-01T09:03:02.011Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start

:A\non\nseveral\nlines;
note left
note
end note

:b;
note right
this is a note which is longer
and on
several lines
but without overscan
it allow some tests
end note

:c;

@enduml
