{
  "sha1": "gm9eldr4m5343ftryuuhu6pcw7we31h",
  "humhash": "fovozu-56-tiri796",
  "insertion": {
    "when": "2026-05-15T21:03:26.213Z",
    "url": "https://github.com/plantuml/plantuml/issues/2276",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
D+13 to D+15 are colored in blue

[Var. A] as [A] lasts 9 days
[Var. B] as [B] lasts 5 days
[C] lasts 10 days
[B] starts at [A]'s end
[A] is colored in Fuchsia/FireBrick
[B] is colored in GreenYellow/Green
[C] starts at D+16


D+10 is colored in gold
D+11 is colored in orange
D+8 is colored in red
@endgantt
