{
  "sha1": "3nlfx8w7h47ibxjh2joy03nax505cbt",
  "insertion": {
    "when": "2024-05-30T20:48:20.302Z",
    "url": "https://forum.plantuml.net/10348/cannot-remove-shadow-sequence-diagrams-kind-participants",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam participant {
  Bordercolor none
  
  Shadowing false
}

skinparam actor {
  Bordercolor none
  
  Shadowing false
}

skinparam boundary {
  Bordercolor none
  
  Shadowing false
}

skinparam control {
  Bordercolor none
  
  Shadowing false
}

skinparam entity {
  Bordercolor none
  
  Shadowing false
}

skinparam database {
  Bordercolor none
  
  Shadowing false
}

skinparam collections {
  Bordercolor none
  
  Shadowing false
}

participant "participant%n()<size:30><&clock>" as participant
actor "actor%n()<size:30><&key>" as actor
boundary "boundary%n()<size:30><&beaker>" as boundary
control "control%n()<size:30><&bar-chart>" as control
entity "entity%n()<size:30><&circle-check>" as entity
database "database%n()<size:30><&envelope-closed>" as database
collections "collection%n()<size:30><&image>" as collections
@enduml
