{
  "sha1": "h74g8v8geqav8hepk19nmpmn2s27b10",
  "insertion": {
    "when": "2024-06-03T18:59:29.239Z",
    "url": "http://forum.plantuml.net/6865/define-without-arguments-interferes-with-define-arguments",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!define foo() called_foo1

!define foo(param) called_foo2 param

class house {
foo
foo(my_param)
}

@enduml
