{
  "sha1": "57zw9sk6bszotpg4midh2orh9zsocmq",
  "insertion": {
    "when": "2024-05-30T20:48:20.678Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
 title imagemap for Webserver appears top left from actor User
 actor User as u [[/wiki/index.php/User]]
 participant Webserver as w [["/wiki index.php Webserver"]]
 'url of u is [[/wiki/index.php/User]]
 'url of w is [[/wiki/index.php/Webserver]]


 u -> w: right
@enduml
