{
  "sha1": "sq6s9npo3ouasd811p2j40etxrlzupt",
  "insertion": {
    "when": "2024-06-04T17:28:45.341Z",
    "url": "https://github.com/plantuml/plantuml/issues/624",
    "user": "plantuml@gmail.com"
  }
}
@startuml
p ------------>
@enduml
