{
  "sha1": "ruq9vtbiyo23h7muzy1tp1wqh3f3tb2",
  "insertion": {
    "when": "2024-06-04T17:28:44.269Z",
    "url": "http://forum.plantuml.net/8933/box-title-syntax-error",
    "user": "plantuml@gmail.com"
  }
}
@startuml

box Internal Service #LightBlue
	participant Bob
	participant Alice
end box
participant Other

Bob -> Alice : hello
Alice -> Other : hello

@enduml
