{
  "sha1": "rutmeabro86y9i68mlf9gi6lt32w3nb",
  "insertion": {
    "when": "2024-06-04T17:28:44.275Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package "entities" {

A1 -> A2
A3 -> A2
A3 -> A2
}


@enduml
