{
  "sha1": "s0t96n6jek7z89yxg2qoan7r9joei5w",
  "insertion": {
    "when": "2024-06-04T17:28:44.524Z",
    "url": "https://github.com/plantuml/plantuml/issues/1334",
    "user": "plantuml@gmail.com"
  }
}
@startjson
{
    "a": true,
    "desc": "a",
    "addP": false,
    "addP1": false,
    "addP2": false,
    "addP3": false,
    "addP4": false,
    "addP5": false,
    "addP6": false,
    "allOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOfallOf": [
        "{ ... }",
        "{ ... }",
        "{ ... }"
    ]
}
@endjson
