{
  "sha1": "mktvbb9pfugsz63oyujau6828fmiwns",
  "insertion": {
    "when": "2024-06-03T18:59:35.368Z",
    "user": "plantuml@gmail.com"
  }
}
@startsalt
{
Superclass:  | "java.lang.Object " | [Browse...]
Do you want to add comments ? (Configure templates and default value <u>here</u>) | * | *
}
@endsalt
