{
  "sha1": "mkx8dwju9oxuvn1unh526ngoc60qm99",
  "insertion": {
    "when": "2024-06-03T18:59:35.375Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam classBorderThickness<<stereo>> 5
skinparam packageBorderThickness<<stereo>> 1.5
skinparam packageBorderThickness 0.5
class A <<stereo>>
class B
package p1 {
class C
}
package p2 <<stereo>> {
class D
}


@enduml
