{
  "sha1": "qews0thcuajjhwxxl4uei0yjh3fnmgv",
  "insertion": {
    "when": "2025-01-23T23:13:50.749Z",
    "url": "https://plantuml.com/newline",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!function $message()
  !return "Alice -> Bob : Hello" + %breakline() + "Bob -> Alice : Hi!"
!endfunction

$message()
@enduml
