{
  "sha1": "fstgpbi4ft6ws42mmriv9yblnqfsz09",
  "insertion": {
    "when": "2024-06-01T09:03:06.602Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (some test?) then
  :action1;
endif
:inter;
if (other test?) then (ok)
  :action2;
else (not ok)
  :action3;
endif
@enduml
