{
  "sha1": "cg1v4c0hauyfvmhbh1omvvg61y5frl6",
  "insertion": {
    "when": "2024-06-01T09:03:01.386Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
caller -> server : conReq
hnote over caller : idle
caller <- server : conConf
hnote over caller [[http://www.yahoo.com {"request":"hyperlink",\n"status":200} note]] : test
note over server [[http://www.yahoo.com {"request":"hyperlink",\n"status":200} note]] : test
rnote over server
 this is
 on several
 lines
endrnote
@enduml
