{
  "sha1": "9gjf9r6vy1gbev2ila7in4vcg4925mg",
  "insertion": {
    "when": "2024-05-30T20:48:21.578Z",
    "url": "https://forum.plantuml.net/15013/gantt-chart-with-style-renders-with-wrong-colors",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
<style>
ganttDiagram {
  task {
    BackGroundColor lightgreen
    LineColor black
    unstarted {
      BackGroundColor red
    }
  }
}
</style>

[Task1] lasts 10 days and is 50% complete
[Task2] lasts 20 days
@endgantt
