{
  "sha1": "exfvanlr9zit8ovrxsdet1za91ohywp",
  "insertion": {
    "when": "2024-06-04T17:28:42.398Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "kakupi-00-lano640"
}
@startnwdiag
nwdiag {
  network inet {
	  web01 [shape = cloud]
  }
}
@endnwdiag
