{
  "sha1": "9aubr9fohiqwhk9u49zcms0lxmjnhgj",
  "insertion": {
    "when": "2024-05-30T20:48:21.638Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=5394/formatting-when-forking-over-swimlanes",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|A|
|B|
|C|

|A|
start

fork
:No.1;

forkagain
|B|
:No.2;

forkagain
|C|
:No.3;
@enduml
