{
  "sha1": "gk1cahqqnembtr3hmouovqcvmhpcgyw",
  "insertion": {
    "when": "2024-06-01T09:03:07.903Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant Bob
participant Alice

note right of Alice: <u>underline</u>
note right of Alice: <b>bold</b>
note right of Alice: <i>italic</i>
note right of Alice: <s>strike</s>
note right of Alice: <b><i>boldItalic
note right of Alice: <b><i><u>boldItalicUnderline
@enduml
