{
  "sha1": "bikdfha41nd9cojb7onede28zjqkm8y",
  "insertion": {
    "when": "2026-03-08T21:21:39.589Z",
    "url": "https://github.com/plantuml/plantuml/issues/2518",
    "user": "plantuml@gmail.com"
  }
}
@startuml
+ class A
@enduml
