{
  "sha1": "ip2qpti8t5yhm6h11bght9ii4gqse2l",
  "insertion": {
    "when": "2024-06-03T18:59:31.043Z",
    "url": "https://forum.plantuml.net/15013/gantt-chart-with-style-renders-with-wrong-colors",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
<style>
ganttDiagram {
  task {
    BackGroundColor lightgreen
    LineColor black
  }
}
</style>

[Task1] lasts 10 days and is 50% complete
[Task2] lasts 20 days
@endgantt
