{
  "sha1": "aq9aqq1ucewhosakkz4ph8ban7slbiz",
  "insertion": {
    "when": "2024-05-30T20:48:20.414Z",
    "url": "https://forum.plantuml.net/10676/repeat-plus-colour",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:A;
repeat :foo; <<#red>>
:D; <<#blue>>
repeat while (C)
:D;
@enduml
