{
  "sha1": "7uafc8anrd8zcveioejy9rnb0pnrdxz",
  "insertion": {
    "when": "2024-05-30T20:48:21.278Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "zeveme-09-reki569"
}
@startuml
class Foo
@enduml
