{
  "sha1": "peyygp1e6x0fs0r38g99u8fckzj72i8",
  "insertion": {
    "when": "2024-06-04T17:28:41.098Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
triangle points=(100,0,10):(100,50,10):(0,50,10) color=#04BF79
'triangle points=(0,0,5):(10,100,50):(234,35,40) position=200,0 color=red
@endcute
