{
  "sha1": "hohh4idajnisg1b77r3gm5empuop91e",
  "insertion": {
    "when": "2024-06-03T18:59:29.803Z",
    "url": "https://forum.plantuml.net/8359/group-components-cant-be-set-transparent?show=8359#q8359",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam backgroundColor silver
'skinparam nodeBackgroundColor
skinparam cloudBackgroundColor transparent
skinparam databaseBackgroundColor yellow

node "Group mode node" {
  node simplenode
  node multilinenode[
    = Multi-line node
    More detail goesherea
  ]
}

cloud "Group mode cloud" {
  cloud simplecloud
  cloud multilinecloud[
    = Multi-line cloud
    More detail goes here
  ]
}

database "Group mode database" {
  database simpledatabase
  database multilinedatabase[
    = Multi-line database
    More detail goes here
  ]
}
@enduml
