{
  "sha1": "ez5wzwy4x5p15g5msrmu96fmgbk7d9q",
  "insertion": {
    "when": "2024-06-01T09:03:05.303Z",
    "url": "https://forum.plantuml.net/15788/where-can-i-find-the-archimate-sprites?show=15788",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam Shadowing false

!include <archimate/Archimate>

archimate #LightGreen "Social Media%n() Competency" as SMC <<strategy-resource>>
@enduml
