{
  "sha1": "ezkni6ahrtaudauzebvw22l9n6ts0hw",
  "insertion": {
    "when": "2024-10-13T12:20:31.227Z",
    "url": "https://forum.plantuml.net/9755/text-before-and-after-functions-discarded-the-preprocessor",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!unquoted function test($name) !return "class "+$name+" << (A, #FF00DD) >>"

test(test) {
    id: int4
    do_something(): void
}
@enduml
