{
  "sha1": "ezojm3cxcpfsn8yycx7o30h1iaom146",
  "insertion": {
    "when": "2024-06-04T17:28:40.848Z",
    "url": "https://forum.plantuml.net/7871/gantt-is-there-way-to-put-different-milesteine-the-same-line",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days and 1 week
[Test prototype] starts 1 week and 2 days after [Prototype design]'s end
[Test prototype] displays on same row as [Prototype design]
@endgantt
