{
  "sha1": "1hqwceh42wfow1uhpqbx8dm1rd0rpnx",
  "insertion": {
    "when": "2024-05-30T20:48:19.690Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam backgroundColor Gold/PapayaWhip
package Customer {
    Customer --{ CustomerRegionWarehouse
    CustomerRegionWarehouse }-- WarehouseInventory
    CustomerRegionWarehouse --> ItemWarehousePriority
    ItemWarehousePriority }-- Inventory
    Customer --{ MultiWarehouseOptions
    Customer --{ Order
    Customer --{ User
}

package Mall {
Inventory --{ MallInventoryReflectionQueue
    Mall --{ Customer
    Mall --{ MallInventoryReflectionQueue
}

package WarehouseItems {
    Shipment }-- Warehouse
    Item --{ ShipmentItem
    Item --{ Inventory
    Inventory }-- WarehouseInventory
    ShipmentItem }-- Warehouse
}

 

package Order {
    Order *-- Shipment
    Shipment .. ShipmentStatus
    Shipment *-- ShipmentItem
}

class ShipmentStatus <<enum>> {
    {field} Waiting Allocation
    {field} Waiting Backorder
    {field} Fulfilled (?)
}

 

class Order {
    {field} Buyer
    {field} Payment
    {field} TotalPrice
    {field} Mall

}

class Shipment {
    {field} Consignee
    {field} Date
    {field} DeliveryNo
    {field} DeliveryMethod
    {field} TotalPrice
    {field} Status : ShipmentStatus
}


class ShipmentItem {
    {field} Product
    {field} Quantity
    {field} Unit Price
}

 

class Warehouse {
    {field} Location
}

 

class Item {
    {field} Size
    {field} Color
    {field} Weight

}

note bottom: Attributes belong to other tables \nJust shown here for simplicity

class Inventory {
}

note right: Information about item stock management 

class WarehouseInventory {
    {field} Quantity
}

class CustomerRegionWarehouse {
    {field} Priority
}

class ItemWarehousePriority {
    {field} Priority
}

class MultiWarehouseOptions {
    {field} Options
}

class Customer {
    {field} Mall
}

class MallInventoryReflectionQueue {
    {field} Quantity
}
@enduml
