{
  "sha1": "4x3lmnk79idvjqr6uj9n608z3pcxi3n",
  "insertion": {
    "when": "2024-05-30T20:48:20.598Z",
    "url": "http://forum.plantuml.net/9031/do-you-plan-for-conditional-code-in-macros?show=9167#a9167",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2
!function bold($text)
!return "<b>"+ $text +"</b>"
!endfunction

Alice -> Bob : bold("foo")pour nous
@enduml
