{
  "sha1": "epjqubxd43g18pdldb9unc2qfemsnja",
  "insertion": {
    "when": "2024-06-01T09:03:04.895Z",
    "url": "https://github.com/plantuml/plantuml/issues/446#issuecomment-1369057034",
    "user": "plantuml@gmail.com"
  }
}
@startjson

skinparam dpi 600

#highlight "lastName"
#highlight "address" / "city"
#highlight "phoneNumbers" / "0" / "number"
{
  "firstName": "John",
  "lastName": "Smith",
  "isAlive": true,
  "age": 28,
  "address": {
    "streetAddress": "21 2nd Street",
    "city": "New York",
    "state": "NY",
    "postalCode": "10021-3100"
  },
  "phoneNumbers": [
    {
      "type": "home",
      "number": "212 555-1234"
    },
    {
      "type": "office",
      "number": "646 555-4567"
    }
  ],
  "children": [],
  "spouse": null
}
@endjson
