{
  "sha1": "epwztjcbaitjx8pclp3h6fjmn2hgat4",
  "insertion": {
    "when": "2025-12-05T20:00:28.837Z",
    "url": "https://github.com/plantuml/plantuml/pull/2452",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
* 
** 
** 
*** 
*** 
**** 
**** 
*** 
@endmindmap
