{
  "sha1": "oducneb3sgspkaxqis82v9yqukzpfez",
  "insertion": {
    "when": "2024-06-04T17:28:39.742Z",
    "url": "https://github.com/plantuml/plantuml/issues/1464#issuecomment-1596916553",
    "user": "plantuml@gmail.com"
  }
}
@startuml

allowmixing

<style>
package {
  FontColor green
  LineColor red
  Title {
    FontColor green
  }
  stereotype {
    FontColor blue
  }
}
</style>

package EmptyPackage <<something>>

package PackageWithThing <<something>> {
    class a
}

rectangle EmptyRectangle <<something>>

rectangle RectangleWithThing <<something>> {
    class b
}
@enduml
