{
  "sha1": "gfdjcsjjmuppag6gi1vqqqnc2xn0wiv",
  "insertion": {
    "when": "2024-05-30T20:48:21.454Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title Some_Title_Here
start

if ( #####)
	:**EVENT1**; <<continuous>>
	: #####; <<procedure>><<#lightblue>>
	-[#blue]-> callback received;
	if ( #####) then ( #####)
		: #####;
	else ( #####)
		: #####;
		if ( #####) then ( #####)
			: #####;
			if ( #####) then ( #####)
				: #####; <<procedure>><<#lightblue>>
				-[#blue]-> callback received;
				if ( #####) then ( #####)
					stop
				else ( #####)
					: #####;
				endif
			else ( #####)
			endif
			: #####;
			if ( #####) then ( #####)
				if ( #####) then ( #####)

					repeat
						if ( #####) then ( #####)
							: ##### = +1;
							: #####; <<procedure>>
							: #####;
						else ( #####)
							: #####; <<task>><<#lightpink>>
							stop
						endif
					repeat while ( #####?) 
					->_#####;

					if ( #####) then ( #####)
						: #####;
					else ( #####)
					endif
					: #####;
					if ( #####) then ( #####)
						: #####;
						: #####; <<procedure>><<#lightblue>>
						-[#blue]-> callback received;
						if ( #####) then ( #####)
							: #####;
							if ( #####) then ( #####)
								: #####;
							else ( #####)
							endif
						else ( #####)
						endif
					else ( #####)
						if ( #####) then ( #####)
						else ( #####)
							if ( #####) then ( #####)
								: #####; <<procedure>><<#lightblue>>
								-[#blue]-> callback received;
								if ( #####) then ( #####)
								else ( #####)
									if ( #####) then ( #####)
										: #####; <<procedure>><<#lightblue>>
										-[#blue]-> callback received;
										: #####; <<procedure>><<#lightblue>>
										-[#blue]-> callback received;
										if ( #####) then ( #####)
											: #####; <<task>><<#lightpink>>
											stop
										else ( #####)
										endif
									else ( #####)
										: #####; <<task>><<#lightpink>>
										stop
									endif
								endif
								: #####;
							else ( #####)
								if ( #####) then ( #####)
								else ( #####)
									: #####; <<procedure>><<#lightblue>>
									-[#blue]-> callback received;
									if ( #####) then ( #####)
										: #####; <<task>><<#lightpink>>
										stop
									else ( #####)
										: #####;
										: #####;
										: #####;
										: #####; <<task>><<#lightgreen>>
										stop
									endif
								endif
							endif
						endif
					endif
				else ( #####)
				endif
			else ( #####)
				end
			endif
		else ( #####)
			stop
		endif
	endif
	: #####; <<task>><<#lightgreen>>
	stop
else
	:**EVENT2**; <<continuous>>
	: #####; <<procedure>><<#lightblue>>
	-[#blue]-> callback received;
	: #####;
	: #####; <<procedure>><<#lightblue>>
	-[#blue]-> callback received;
	if ( #####) then ( #####)
		: #####; <<task>><<#lightpink>>
		stop
	endif

	if ( #####) then ( #####)
		if ( #####) then ( #####)
			: #####; <<task>><<#lightblue>>
			-[#blue]-> callback received;
			if ( #####) then ( #####)
				: #####; <<task>><<#lightpink>>
				stop
			else ( #####)
				: #####;
			endif
		else ( #####)
			: #####; <<task>><<#lightpink>>
			stop
		endif
	else ( #####)
		if ( #####) then ( #####)
			: #####;
			if ( #####) then ( #####)
				: #####; <<task>><<#lightpink>>
				stop
			else ( #####)
			endif
		else ( #####)
			: #####;
			if ( #####) then ( #####)
				: #####; <<task>><<#lightpink>>
				stop
			else ( #####)
				: #####;
			endif
		endif
	endif
	: #####;
	: #####; <<procedure>><<#lightblue>>
	-[#blue]-> callback received;
	if ( #####) then ( #####)
		: #####; <<task>><<#lightpink>>
		stop
	else ( #####)
	endif
	: #####;
	: #####; <<task>><<#lightgreen>>
	stop
endif

@enduml
