{
  "sha1": "11p0ncsn5kxzu3gt335tx3g05a7lp3a",
  "insertion": {
    "when": "2025-11-05T08:52:15.498Z",
    "url": "https://github.com/plantuml/plantuml/issues/2416",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!include <DomainStory/domainStory>

Boundary(System) {
Person(Alice)
Conversation(weather)
Person(Bob)
}
activity(1, Alice, talks about the, weather, with, Bob)
@enduml
