{
  "sha1": "3h065w2ly45q5307lljzj54umwi8frd",
  "insertion": {
    "when": "2024-05-30T20:48:20.266Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "derixi-63-jemi851"
}
@startebnf
scale 5
test = ['a'|'b'];
@endebnf
