{
  "sha1": "hy4hm1a1fa30hp8ht09do0trx8asjpe",
  "insertion": {
    "when": "2024-06-03T18:59:30.127Z",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
<style>
leafNode {
  FontSize 12
}
</style>
* Bidouille
** https://www.qwant.com/?r=FR&sr=fr&l=fr_fr&h=0&s=0&a=1&b=1&hc=1&smartNews=1&smartVideos=1&smartSocial=1&theme=0&i=1&client=brz-vivaldi&q=%s
*** https://www.qwant.com/?r=FR&sr=fr&l=fr_fr&h=0&s=0&a=1&b=1&hc=1&smartNews=1&smartVideos=1&smartSocial=1&theme=0&i=1&client=brz-vivaldi&q=%s
@endmindmap
