{
  "sha1": "hyhzkwy8wq2vhvfinxugr5hcoabxpkm",
  "insertion": {
    "when": "2024-06-03T18:59:30.141Z",
    "url": "https://github.com/plantuml/plantuml/issues/1253",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
classDiagram {
    RoundCorner 15
    .mystyle {
    	RoundCorner 5
        BackgroundColor cyan
        FontStyle Bold
        FontColor red
    }
}
</style>
class AliceMyStyle <<<mystyle>>>
class AliceMyStyleStereo <<mystyle>>
class Alice1

class AliceMyStyleEmpty <<<mystyle>>> {}
class AliceMyStyleStereoEmpty <<mystyle>> {}
class AliceMyStyleNewLine2 <<<mystyle>>> {
}
class AliceMyStyleStereoNewLine <<mystyle>> {
}
class AliceMyStyleProp3 <<<mystyle>>> {
  - prop1
}
class AliceMyStyleStereoProp <<mystyle>> {
  - prop1
}
@enduml
