{
  "sha1": "hyqm01b0ac8k416q2eqmc1cfmonqw6v",
  "insertion": {
    "when": "2024-06-03T18:59:30.159Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    alt
    A2->A1
    else
    A2->A1
@enduml
