{
  "sha1": "2fk6n9jx97qitzl9xnvc63p3753kyer",
  "insertion": {
    "when": "2024-05-30T20:48:19.978Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "tubepu-44-gigu535"
}
@startregex
A(?<tld>BCD)Z
@endregex
