{
  "sha1": "fo33dvzcxt9n1olcpamh02qp8752sju",
  "humhash": "noceji-99-zivu632",
  "insertion": {
    "when": "2026-08-25T17:32:07.154Z",
    "url": "https://github.com/plantuml/plantuml/issues/2791",
    "user": "plantuml@gmail.com"
  }
}
@startuml
a->b
box "Box A"
  participant a
endbox

a->a : msg
a<-a : long long long long long msg
a->c
@enduml
