{
  "sha1": "hpwid1dhcu1qkxzf3lxbewolqu5t3h4",
  "insertion": {
    "when": "2024-06-03T18:59:29.859Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam component {
  BackgroundColor BlanchedAlmond
  BackgroundColor<<A>> Red
}

skinparam interface {
    BackgroundColor LightBlue
    BackgroundColor<<A>> Blue
}


component comp1 <<A>>
interface inter1 <<A>>

inter1 --> [comp1]
inter2 --> [comp2]

@enduml  
