{
  "sha1": "74j0xhusktpq2xtt90welcmc43lk5lo",
  "insertion": {
    "when": "2024-05-30T20:48:21.118Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
@startuml
digraph unix {
nodesep=0.277778;
ranksep=0.555556;
remincross=true;
searchsize=500;
compound=true;
{rank=min;minPoint4; minPoint8; minPointA}
{rank=max;maxPoint4 ;maxPoint8; maxPointA}
subgraph cluster4 {style=solid;color="#000004";
{rank = source; sourceIn4 ;}
minPoint4->sourceIn4  [weight=999];
{rank = sink; sinkIn4 ;}
sinkIn4->maxPoint4  [weight=999];

sh0006;
sh0007 ;
sh0006->sh0007[arrowtail=none,arrowhead=open,color="#00000B"];
}
subgraph cluster8 {style=solid;color="#000008";
{rank = source; sourceIn8 ;}
minPoint8->sourceIn8  [weight=999];
{rank = sink; sinkIn8 ;}
sinkIn8->maxPoint8  [weight=999];
sh0010 ;
sh0007->sh0010[arrowtail=none,arrowhead=open,color="#00000F",minlen=1];
}
minPointA->maxPointA [minlen=6];

}
@enduml@enduml
