{
  "sha1": "bru5zbo7utoyz0ozai9y5lcvjgnucku",
  "insertion": {
    "when": "2024-05-30T20:48:22.146Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
'!preprocessorV2
!function bold($text)
!return "<b>"+ $text +"</b>"
!endfunction

Alice -> Bob : %call_user_func("bold", "foo") pour nous
@enduml
