{
  "sha1": "of5asi7jh2nrd5f80b05rpkb4rai7jt",
  "insertion": {
    "when": "2024-06-04T17:28:39.804Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant A as "This is A"
participant B as "This is B"
participant C as "This is C"
participant D as "This is D"
A -> B
B -> C
C -> D
note over A,C : i
@enduml
