{
  "sha1": "ofj1swotwql8dsi2dtllx2zwezigzrm",
  "insertion": {
    "when": "2024-06-04T17:28:39.817Z",
    "url": "https://forum.plantuml.net/16912/backward-in-repeat-loop-not-possible-to-set-color",
    "user": "plantuml@gmail.com"
  }
}
@startuml

repeat  
:Review Activity;<<task>><<#LightGreen>>

backward  :Rework;<<task>>

repeat while (active Remarks) is (Yes) not (No)

@enduml
