{
  "sha1": "3rbe9u6n1qwviliiwue5g9z81iqh919",
  "insertion": {
    "when": "2024-05-30T20:48:20.338Z",
    "url": "https://forum.plantuml.net/15544/stereotype-priorities-changed-compared-implementations",
    "user": "plantuml@gmail.com"
  }
}
@startuml
' here it works
    ' skinparam DefaultFontColor blue

    skinparam rectangle<<RedContainer>> {
        StereotypeFontColor red
        FontColor red
        BackgroundColor lightred
        BorderColor darkred
        RoundCorner 0
        DiagonalCorner 18
    }

    ' here it fails
    ' skinparam DefaultFontColor blue

    skinparam rectangle<<Default>> {
        StereotypeFontColor blue
        FontColor blue
    }

    rectangle "==red container" <<RedContainer>><<Default>> as rC
    rectangle "==default container" <<container>><<Default>> as r
@enduml
