{
  "sha1": "ftna15odizny5uyo4a1gxyzoqrfloep",
  "insertion": {
    "when": "2024-06-01T09:03:01.177Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] starts D+0
[Test prototype] starts D+15
[Prototype design] ends D+14
[Test prototype] ends D+24
@endgantt
