{
  "sha1": "1lcct0e45huc9m1flka3l6eqkp4gbxa",
  "insertion": {
    "when": "2024-05-30T20:48:19.726Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

title Mon Titre

Bob -> Alice : hello

left footer
this is a footer that is very very long but contains no information
endfooter

right header
this is a long
<b>header</b>
end header

@enduml
