{
  "sha1": "3umnzyhtzgs5zl2g0glkpjsfuvhz4k8",
  "insertion": {
    "when": "2024-05-30T20:48:20.642Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (?) then (1)
    :Something;
else (2)
	[[http://plantuml.com/sequence]] if (?) then (x) <<#ff8822>>
        stop
    else (y)
        stop
    endif
endif
stop
@enduml
