{
  "sha1": "czlm4genjgrjm7lq3apibroyozkmr5g",
  "insertion": {
    "when": "2024-08-28T16:43:33.549Z",
    "url": "https://github.com/plantuml/plantuml/issues/1550",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set separator .
!pragma useIntermediatePackages false

package foo1 {
  package foo2 {
    component foo3
  }
}

@enduml
