{
  "sha1": "8rix973acgzpq2483hj6rcneh3ibjw4",
  "insertion": {
    "when": "2024-05-30T20:48:21.506Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
swimlane P1
swimlane P2
swimlane P3

if (multiprocessor?) then (yes)
  fork in p1
  :Treatment 1; in P1
  fork again
    :Treatment 2;
  end fork
else (monoproc)
  :Treatment 1;
  :Treatment 2;
endif
@enduml
