{
  "sha1": "ob72lw1165rh9x5m8o84cfoy7mmzz37",
  "insertion": {
    "when": "2024-06-04T17:28:39.658Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam defaultTextAlignment center
[component title\n more component info] <<myStereotype>>
@enduml
