{
  "sha1": "ggqr9xqezn99t8xv1pb4fqv1fel9dyy",
  "insertion": {
    "when": "2024-06-01T09:03:07.744Z",
    "url": "http://forum.plantuml.net/9341/embedding-in-interface-note-fails",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title Embedding for interface note fails

        component "B" as B {
	}

	component "A" as A {		 
	}

	B <-[dashed]-> A: API\nDetails:\n{{\na->b:req\nb-->>a:resp\n}}\n
@enduml
