{
  "sha1": "gguifn954729s5y53rwlrntuh2ox5bk",
  "insertion": {
    "when": "2024-06-01T09:03:06.069Z",
    "url": "https://github.com/plantuml/plantuml/issues/1050",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
-- Architectural design--
[Create draft of architecture] lasts 10 days
then [Prepare construction documents] lasts 10 days
then [Agreement on architectural plan] lasts 1 day

-- Interior design--
then [Pre design] lasts 3 days
then [Furniture selection] lasts 3 days
[Equipement planning] lasts 3 days and starts after [Pre design]'s end

-- Construction phase--
[Building foundation] lasts 15 days and starts after [Agreement on architectural plan]'s end
then [Ground Floor building] lasts 10 days
then [Frist Floor building] lasts 10 days
then [Roof] lasts 10 days

@endgantt
