{
  "sha1": "bzyhyjxckrypkk0ydmrgfz8uo5do3w6",
  "insertion": {
    "when": "2024-05-30T20:48:22.193Z",
    "url": "https://forum.plantuml.net/11682/beta-style-cropped-output-images-when-style-functionality",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
diamond {
  LineColor black
}
</style>
start
if (Graphviz installed?) then (yes)
  :process all%n()diagrams;
else (no)
  :process only
  __sequence__ and __activity__ diagrams;
endif
stop
@enduml
