{
  "sha1": "m1t28hj2gxd6kgwq9vylahz1c4nxxkm",
  "insertion": {
    "when": "2024-06-03T18:59:34.739Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam interface {
backgroundColor RosyBrown
borderColor orange
}

() "Data Access" as DA

DA - [First Component] 
[First Component] ..> () HTTP : use
@enduml
