{
  "sha1": "orsoy29170w2uk73d0dm5yarpfs3d14",
  "insertion": {
    "when": "2024-06-04T17:28:40.171Z",
    "url": "https://github.com/plantuml/plantuml/issues/1334",
    "user": "plantuml@gmail.com"
  }
}
@startjson
{
    "a": true,
    "allOf": [
        "{ ... }",
        "{ ... }",
        "{ ... }"
    ]
}
@endjson
