{
  "sha1": "lvbr6t6emd02mingfdabhwxyhve40n9",
  "insertion": {
    "when": "2024-06-03T18:59:34.586Z",
    "url": "https://forum.plantuml.net/11283/lines-without-arrows?show=11302#c11302",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam ArrowColor orange
skinparam ArrowHeadColor none
:Qwerty;
:Asdfgh;
@enduml
