{
  "sha1": "ffgavff7j66ckgzwen4muhhbaq133zg",
  "insertion": {
    "when": "2024-06-01T09:03:06.088Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
 :GET(ressource, version, host)
 FROM host VIA connection1>
@enduml
