{
  "sha1": "pdvl7ino3egl20j9zplczu0y2uiug0d",
  "insertion": {
    "when": "2024-06-04T17:28:41.058Z",
    "url": "https://github.com/plantuml/plantuml/issues/134",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam noteTextAlignment left
note as N1
👑 left
Keep Calm
and
Align Left
end note
@enduml
