{
  "sha1": "o944kd1b62004pq1p6n4w1yza1457c0",
  "insertion": {
    "when": "2024-06-04T17:28:39.544Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:Hello;
if (test) then
	:Action1;
	:Action2;
endif
:Action3;
:Action4;

@enduml
