{
  "sha1": "mqvd4r47g6sbyl3fy3jhmnqyyua136i",
  "insertion": {
    "when": "2024-06-03T18:59:35.524Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam defaultFontName Helvetica
alice -> bob : hello
@enduml
