{
  "sha1": "pn5mrmc22udxxvxhiv7y1d29befqlpj",
  "insertion": {
    "when": "2024-06-04T17:28:41.464Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
Bob->Alice: coucou2
opt
Alice->Bob: ok0
newpage
Alice->Bob: ok1
else toto
Alice->Bob: ok2
end
@enduml
