{
  "sha1": "pnx77juu0wyk13gjziqx83z5ozg6x5w",
  "insertion": {
    "when": "2024-06-04T17:28:41.486Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Customer |o--o{ AccountParty
"Customer::AccountReconciliation" <|.. Object

hide empty members
@enduml
