{
  "sha1": "j8qh214e9qc3g72b4171sasu08pp39n",
  "insertion": {
    "when": "2024-06-03T18:59:31.999Z",
    "url": "https://github.com/plantuml/plantuml/issues/62",
    "user": "plantuml@gmail.com"
  },
  "humhash": "poceka-037-nokulo"
}
@startsalt
{
  Just plain text
}
@endsalt
