{
  "sha1": "pv15tjb5uiefedq19v4fyfozyb245ou",
  "insertion": {
    "when": "2024-06-04T17:28:41.768Z",
    "url": "https://github.com/plantuml/plantuml/issues/1332",
    "user": "plantuml@gmail.com"
  }
}
@startuml


a --> b : toto
note on link
This is not visible,
neither in smetana
nor ELK.
end note

@enduml
