{
  "sha1": "pvqfoxw42llguac8izumrf2ag13geyq",
  "insertion": {
    "when": "2025-10-16T19:14:53.815Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title Between min-max
analog "Analog" between 350.0 and 450.0 as A

@0
A is 350

@100
A is 450

@300
A is 350
@enduml
