{
  "sha1": "m8jr7w34uujmjtpcif3s0uz76nxt5gd",
  "insertion": {
    "when": "2024-06-03T18:59:34.990Z",
    "url": "https://forum.plantuml.net/17571/is-it-possible-to-set-gantt-tasks-to-be-incomplete-by-default?show=17571#q17571",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Task completion default to 0%

[Prototype design] lasts 13 days
[Test prototype 40] lasts 4 days

[Test prototype 40] starts at [Prototype design]'s end

[Prototype design] is colored in Red/Blue 
[Test prototype 40] is colored for completion from Fuchsia/FireBrick to GreenYellow/Green 

@endgantt
