{
  "sha1": "12w45qr5ktzncz6hgzwb8ag6cnlx8ts",
  "insertion": {
    "when": "2024-06-04T17:28:42.701Z",
    "url": "https://forum.plantuml.net/18011/is-is-possible-to-change-the-milestone-icon-from-a-diamond",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Test prototype] requires 10 days.
[Prototype completed] happens at [Test prototype]'s end.
It is displayed as <:innocent:>
'[Setup assembly line] requires 12 days.
'[Setup assembly line] starts at [Test prototype]'s end.
@endgantt
