{
  "sha1": "tu3v55ktiwkc9tpzqm9y1xlwm087pke",
  "insertion": {
    "when": "2024-06-04T17:28:46.768Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] as [TASK1] lasts 13 days
[TASK1] #Lavender/red
@endgantt
