{
  "sha1": "tul6wgpzjn34s8doognhtxhsnh4jpzy",
  "insertion": {
    "when": "2024-06-04T17:28:46.792Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package my_package{
    together {
    }
}
@enduml
