{
  "sha1": "lpssaot7c0laobndbrx4aivr1121yay",
  "insertion": {
    "when": "2024-06-04T17:28:46.768Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Prototype design] as [TASK1] lasts 13 days
[TASK1] #Lavender/red
@endgantt
