{
  "sha1": "f7wib6omusaf1dkpul394qvbroctb64",
  "insertion": {
    "when": "2024-06-01T09:03:05.693Z",
    "url": "https://github.com/plantuml/plantuml/issues/1316",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true

c -> c: First Page: One
c -> tc: First Page: Two
tc -> is: First Page: Three
is -> tc: First Page: Four
tc -> sc: First Page: Five
newpage

c -> c ++: Second Page: One
c -> tc: Second Page: Two
tc -> is: Second Page: Three
is -> tc: Second Page: Four
tc -> sc: Second Page: Five
c -> c --: deactivaton

@enduml
