{
  "sha1": "d9vn3g6zn99krthe12cgqiwssdj14g5",
  "insertion": {
    "when": "2024-06-01T09:03:02.713Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "katoju-58-deje525"
}
@startuml
!pragma svek_trace on
rectangle Rect {
A -> B
}
@enduml
