{
  "sha1": "h4te61fo35zc32ocyq325idu2e5m3fw",
  "insertion": {
    "when": "2024-06-03T18:59:29.151Z",
    "url": "http://forum.plantuml.net/7708/formatting-options-inside-%40startmath-%40endmath",
    "user": "plantuml@gmail.com"
  }
}
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
