{
  "sha1": "4tp9nm9gnrg7xnlhtr9s3b21lqz5xla",
  "insertion": {
    "when": "2024-05-30T20:48:20.570Z",
    "url": "https://forum.plantuml.net/18349/gantt-diagram-current-dates-window",
    "user": "plantuml@gmail.com"
  }
}
@startgantt

<style>
ganttDiagram {
  task {
    BackGroundColor GreenYellow
    LineColor Green 
  }
  
  .dev {
	  task {
	    BackGroundColor Chocolate
	    LineColor Tomato 
	  }
  }
  
}
</style>


[Prototype design] requires 20 days.
then [code prototype] <<dev>> requires 30 days.
then [Test prototype] requires 10 days.
it is 50% complete.

@endgantt
