{
  "sha1": "1bai6riaklg0nfwc1jv26dsqip2jsjh",
  "insertion": {
    "when": "2024-05-25T14:26:51.406Z",
    "url": "https://forum.plantuml.net/13473/crash-when-there-is-a-missing-label-on-timing-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
robust "Main Switch" as MainSwitch
MainSwitch is Off

@0  as :On
@5  as :Off

@:On
MainSwitch is On
@:Off
MainSwitch is Off

MainSwitch@:On <-> @:OffBad : tOn
@enduml
