{
  "sha1": "1bsq4y4r2djuh45yiv1bja3re7gzot4",
  "insertion": {
    "when": "2024-05-25T14:26:51.413Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
rotate
skinparam svek true
package A {
class B {
}
} 
C -right-* D
E *-- F
@enduml
