{
  "sha1": "rt9ww3zcc6l5xgrdfpo8yi5thro6hvj",
  "insertion": {
    "when": "2024-06-04T17:28:39.323Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

participant "Bob on%n()several lines" as Bob
actor Alice

Bob -> Alice : hello
note right of Alice
  this is a note
end note

Alice -> Bob : Is it ok%n()with a message that is%n()on several lines?

note right
  This other note
  should work
  on several lines
end note

== This is a separation ==

Bob -> Last : Yes it works!
Last -> Last : working in progress
note left : this is%n()another note

Last --> Last : working in progress
Last --> Bob : done

opt dummy comment
  Bob -> Last : Error%n()On%n()Several%n()Line
  Last --> Bob : None
else
  Last --> Bob : None
  Last -> Bob : None
else other
  Last -> Bob : None
  note over Alice, Last
    This is a long note
    over Alice and Last
  end note
  Last -> Bob : None
  Last -> Bob : None
end

@enduml
