{
  "sha1": "6kluhxygalc759b76n7w3uxfog9aifz",
  "insertion": {
    "when": "2024-05-30T20:48:20.974Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam layout circo

Package Mirrorix{

class CashFlow{
  method()
}
class Logger{
  method()
}
class Mute{
  method()
}
class Program{
  method()
}
class QtomCnx{
  method()
}
class SqlCnx{
  method()
}
class XmlNavigator{
  method()
}
Package Operations{
class Annonces{
  method()
}
class Annonces{
  method()
}
class MMDeals{
  method()
}
class FxDeals{
  method()
}
class PayInterco{
  method()
}
class FxHedge{
  method()
}
}
}
@enduml
