{
  "sha1": "rfa3lv75myo3qmy9sacb4yjpw5szrye",
  "insertion": {
    "when": "2024-06-04T17:28:43.722Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam state {
BorderColor<<comp>> Black
BackgroundColor<<comp>> Blue
BorderColor<<simple>> Black
BackgroundColor<<simple>> Green
}
state c<<simple>>
state d<<simple>>
c --> d : event
 
state "a_1" as a<<comp>> {
state x<<simple>>
state y<<simple>>
x --> y : ev
}
 
state "a_2" as b<<comp>> {
state w<<simple>>
state z<<simple>>
w --> z : ev2
}
 
a --> b : ev3
@enduml
