{
  "sha1": "rfzutohrccrd0rpq05pv68vfes1svl6",
  "insertion": {
    "when": "2024-06-04T17:28:43.757Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=1831/border-thickness&show=5082#c5082",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
<style>
  title {
    LineColor black
    LineThickness 1.5
  }
</style>
title My Title
Bob -> Alice : hello
@enduml
