{
  "sha1": "k77lrh9rac5skqje5a15ww82ukxxpu9",
  "insertion": {
    "when": "2024-06-03T18:59:32.684Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma svek_trace on
state myExit <<exitpoint>>
@enduml
