{
  "sha1": "k7uh8shi8vrwni5mpg0dcaxapu1bvuy",
  "insertion": {
    "when": "2024-06-03T18:59:32.698Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam defaultFontName "Liberation Mono"
interface FichierRejetPO
@enduml
