{
  "sha1": "k7umplh5qzr2awbca50ievzizx5adka",
  "insertion": {
    "when": "2024-06-03T18:59:32.705Z",
    "url": "https://forum.plantuml.net/17187/verticals-separators-gantt-chart-appear-certain-conditions",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2022-12-01

[task1] lasts 1 week
[task2] starts 20 days after [task1]'s end and lasts 3 days

Separator just at [task1]'s end
Separator just 2 days after [task1]'s end


@endgantt
