{
  "sha1": "grcsfxkfom09p4732elz0svu0alfu60",
  "insertion": {
    "when": "2024-06-01T09:03:08.225Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
document {
  BackgroundColor red
}
</style>

class foo1
class foo2

@enduml
