{
  "sha1": "jsxu85gf6avl8x29dakoa4zvdaxwoz8",
  "insertion": {
    "when": "2024-06-03T18:59:32.213Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma horizontalLineBetweenDifferentPackageAllowed
component AA_ok {
}
[BB_ok]
AA_ok -r-> BB_ok
component AA {
  [CC]
}
[BB]
AA -r-> BB
@enduml
