{
  "sha1": "i4idkmkn49mrnwqzde60ao4xk8xcdtb",
  "insertion": {
    "when": "2024-06-03T18:59:30.303Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:start1;
partition "go up the stairs" {
 :go up first step;
 :go up second step;
 if (tired) then(yes)
   :stop a bit;
 endif
 :go up last steps;
}
:start2;
@enduml
