{
  "sha1": "g8ony2brpomavh3autbs1xv8jmgapgx",
  "insertion": {
    "when": "2024-06-01T09:03:07.371Z",
    "url": "https://forum.plantuml.net/14362/styling-descendents-error-in-wbs-diagrams",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
<style>
wbsDiagram {
  .cyan * {
    BackgroundColor cyan
  }
  .gold * {
    BackgroundColor gold
  }
}
</style>

* Cyan <<cyan>>
** Gold2 <<gold>>
@endwbs
