{
  "sha1": "bmf9insn31u934sufsr1rhbs1x5x6n0",
  "insertion": {
    "when": "2024-05-30T20:48:22.122Z",
    "url": "https://forum.plantuml.net/14457/cropped-reference-on-sequence-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
scale 2
<style>
sequenceDiagram {
  reference {
    LineThickness 5
  }
}
</style>
ref over Alice, Bob : this is a reference%n()(normal style)
@enduml
