{
  "sha1": "kdt3er210k1ayyaj4bgtyh5e0yz3vts",
  "insertion": {
    "when": "2024-06-03T18:59:35.438Z",
    "url": "https://forum.plantuml.net/14104/sequence-diagram-incoming-outgoing-some-arrows-are-inverted",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title Long title to see cropped arrow
participant Alice as a
participant Bob   as b
== <color:red> KO ==
 [o<-x b : "" [o<-x""
 [o//- b : "" [o//-""
  [o/- b : ""  [o/-""
 [o\\- b : "" [o\\-""
  [o\- b : ""  [o\-""
 [o<<- b : "" [o<<-""
[x<->x b : ""[x<->x""
  [o<- b : ""  [o<-""
  [<-o b : ""  [<-o""
  [<-x b : ""  [<-x""
...
  [x<-o b : ""  [x<-o""
  [//-o b : ""  [//-o""
   [/-o b : ""   [/-o""
  [\\-o b : ""  [\\-o""
   [\-o b : ""   [\-o""
  [<<-o b : ""  [<<-o""
   [<-o b : ""   [<-o""
== <color:green> OK ==
[o<->o b : ""[o<->o""
  [<-> b : ""  [<->""
 [o<-o b : "" [o<-o""
...
  [x<- b : ""  [x<-""
  [//- b : ""  [//-""
   [/- b : ""   [/-""
  [\\- b : ""  [\\-""
   [\- b : ""   [\-""
  [<<- b : ""  [<<-""
   [<- b : ""   [<-""
@enduml
