{
  "sha1": "dc2vmlsudt7tc6oduapdoiq52gpyijj",
  "insertion": {
    "when": "2024-06-01T09:03:02.788Z",
    "url": "https://github.com/plantuml/plantuml/issues/307",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma svek_trace on
object London

map CapitalCity {
 UK *-> London
 USA => Washington
 Germany => Berlin
}
@enduml
