{
  "sha1": "54sw6y0usmjfca57vvybwtgg1lgxhd7",
  "insertion": {
    "when": "2025-04-07T07:55:21.742Z",
    "url": "https://github.com/plantuml/plantuml/issues/2144",
    "user": "plantuml@gmail.com"
  }
}
@startuml
binary "sample" as sample
concise "tx1" as tx1
hide time-axis

@sample
@20 
sample is high
+0.1 is low
+9.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low
+19.9 is high
+0.1 is low

@tx1
0 is {hidden}
+20 is START
+19 is D0
+19 is D1
+19 is D2
+19 is D3
+19 is D4
+19 is D5
+19 is D6
+19 is D7
+19 is STOP
+19 is {hidden}
@enduml
