{
  "sha1": "gbplxkyqg8n39v2dvbt2eyf8ohlv5z",
  "insertion": {
    "when": "2024-06-01T09:03:07.555Z",
    "url": "https://forum.plantuml.net/10864/fontcolor-for-enteties-in-class-diagrams",
    "user": "plantuml@gmail.com"
  }
}
@startuml
	skinparam class{
	AttributeFontColor gold
	BackgroundColor LightBlue
	FontColor Yellow
	BorderColor Green
	ArrowColor Purple
	ArrowFontColor Orange
}
class "ClassTitle1" as C1{
	-atribute1
	+atribute2
	~atribute3
	-method1()
	+method2()
	~method3()
}
class "ClassTitle2" as C2{
	-atribute1
	+atribute2
	~atribute3
	-method1()
	+method2()
	~method3()
}
C1 -> C2 : Relation
@enduml
