{
  "sha1": "1rlga3yiilb3h8pykb590fs2qihonxa",
  "insertion": {
    "when": "2024-05-30T20:48:19.770Z",
    "url": "https://forum.plantuml.net/14973/sequence-lifeline-color-missing-on-in-out-messages-with-teoz",
    "user": "plantuml@gmail.com"
  }
}
@startuml
[-> A ++ #ff0000 : No lifeline color with\n<b>!pragma teoz true</b>
A -> B ++ #00ff00
return
return
B ->] ++ #ff0000 : No lifeline color with\n<b>!pragma teoz true</b>
@enduml
