{
  "sha1": "njfj3jz4pagu4ty4zdftmnlxv8oyl0p",
  "insertion": {
    "when": "2024-06-04T17:28:38.713Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "fokiri-107-vimanu"
}
@startuml
autoactivate on
[-> Alice : request()
[<-- Alice : ok
@enduml
