{
  "sha1": "njszc3sycy56e4kv9d883av1m1e5ybr",
  "insertion": {
    "when": "2024-06-04T17:28:38.742Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
A "0" -- "1" B : "a" is "b"
Class01 "1" *-- "many" Class02 : "sourcerolename" contains "targetrolename"
@enduml
