{
  "sha1": "cxxy83xkeapfaegeex8uyg0hdma2m8d",
  "insertion": {
    "when": "2026-03-27T18:41:43.962Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "mufute-30-juja962"
}
@startwbs
* Project
**_
*** Task A
*** Task B long name
*** Task C
** Planning
*** Define scope
*** Set milestones
@endwbs
