{
  "sha1": "gldo50j05wbdwenohfcimko1xwmoqvl",
  "insertion": {
    "when": "2024-06-01T09:03:07.984Z",
    "url": "https://github.com/plantuml/plantuml/issues/1332",
    "user": "plantuml@gmail.com"
  }
}
@startuml

a --> b
note on link
This is not visible,
neither in smetana
nor ELK.
end note

@enduml
