{
  "sha1": "8banv9a7f20qxtgwbsf0zou22gjekyj",
  "insertion": {
    "when": "2024-05-30T20:48:21.382Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam useBetaStyle true


box
participant Bob 
end box
participant Alice
Bob->Alice: Hello! 

@enduml
