{
  "sha1": "8byzrdexg8w5gwpeeulvlt51lgsbdit",
  "insertion": {
    "when": "2024-05-30T20:48:21.386Z",
    "url": "https://forum.plantuml.net/11556/diagrams-backgroundcolor-transparent-nullpointerexception",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
<style>
mindmapDiagram {
  BackGroundColor transparent
}
</style>
* a
** a1
** a2
@endmindmap
