{
  "sha1": "fy70fahju0mmdlnutxa8bpigb9qxjlv",
  "insertion": {
    "when": "2024-06-01T09:03:06.859Z",
    "url": "https://forum.plantuml.net/15299/how-to-set-color-of-the-gantt-unstarted-task",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
<style>
ganttDiagram {
  task {
    BackGroundColor GreenYellow
    LineColor Green 
  }
  undone {
    BackGroundColor red
  }
}
</style>


[foo] lasts 21 days
[foo] is 40% completed
[bar] lasts 30 days and is 10% complete
@endgantt
