{
  "sha1": "dagr6fzlxu0kvs0opapblqdygxyw8v7",
  "insertion": {
    "when": "2024-06-01T09:03:02.729Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
 
|Author|
Start
repeat
repeat
if (New document?) then (yes)
:Create;
else (no)
:Update;
endif
->Document Draft;
 
|Reviewer|
:Review Document;
repeat while (Document agreed?) is (ok)
->Document Reviewed;
 
|Approver|
:Approve Document --> Update;
repeat while (Document approved?) is (ok)
->Document Verified;
 
|Owner|
:Archive;
->Document Archived;
 
stop
 
@enduml
