{
  "sha1": "gssqdetkpf9w31jp229d1s7mbrplgug",
  "insertion": {
    "when": "2024-05-30T20:48:21.934Z",
    "url": "https://forum.plantuml.net/9616/how-to-add-milestone-at-specific-day",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
[Sprint X] lasts 21 days
then [Sprint X UAT] lasts 7 days
[Sprint X Checkpoint] happens 7 days after [Sprint X]'s start
@endgantt
