{
  "sha1": "feu5759xdqy83mchq5u4dtqw2qi8vhy",
  "insertion": {
    "when": "2024-06-01T09:03:06.036Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
TITLE Title
START
IF()THEN([AAAAAAAAAAAAAAAAAAAA \nAAAAAAAAAAAAAAAAAA])
        :X;
    ELSEIF()THEN
        
        IF()THEN([CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC])
        :YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
        YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY;
        ELSE([EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEElse1])
            :ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ;
        ENDIF            
    ELSE([Else2])
    ENDIF
STOP
@enduml
