{
  "sha1": "88tkv8d5ulrguq45mepzgyohnkke1as",
  "insertion": {
    "when": "2026-03-17T20:18:03.388Z",
    "url": "https://github.com/plantuml/plantuml/issues/2518",
    "user": "plantuml@gmail.com"
  }
}
@startuml
+ class A {
}
@enduml
