{
  "sha1": "tijn2plegkzivbbfuti7eo76rnqd3rs",
  "insertion": {
    "when": "2024-06-04T17:28:46.262Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml 
autoactivate on
' See http://plantuml.sourceforge.net/sequence.html

Title LifeLine Activation

A -> B : message

B ->> C :Fire&Forget 
Note right: should be active for a little while

B -> B : self

B->C : message
C--> B: response

B --> A : response

@enduml
