{
  "sha1": "tim21cb97hwkfwuvg36cb53rggly6f0",
  "insertion": {
    "when": "2024-06-04T17:28:46.269Z",
    "url": "http://forum.plantuml.net/8434/sprites-are-not-interpreted-in-byperlink-display-text",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set separator none
!include <tupadr3/font-awesome/database>

title <$database>
rectangle "something\nclick the image:[[http://plantuml.com before <$database*0.31> after]]"
rectangle "something\nclick the image:[[http://plantuml.com before <$database> after]]"
rectangle "something\nclick the archimate image:[[http://plantuml.com before <&cloud> after]]"
@enduml
