{
  "sha1": "kjz9vftyu5r8utx88y3c38pn66ixsc6",
  "insertion": {
    "when": "2024-06-03T18:59:33.062Z",
    "url": "https://forum.plantuml.net/12159/gantt-diagram-no-style-entry-for-legend",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
	legend {
		FontColor blue
		FontSize 15
        FontStyle italic
		LineColor Orange
	}
</style>

legend
hypothesis
 * Hyp 1
 * Hyp 2
end legend

alice -> bob

@enduml
