{
  "sha1": "tl3j1au1zxf2eska1xdincbqnt8lwwn",
  "insertion": {
    "when": "2024-06-04T17:28:46.374Z",
    "url": "https://forum.plantuml.net/14340/color-of-arrow-in-timing-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
timingDiagram {
  document {
    BackGroundColor gold
  }
}
</style>
robust "Web Browser" as WB
concise "Web User" as WU

WB is Initializing
WU is Absent

@WB
0 is idle
+200 is Processing
+100 is Waiting
WB@0 <-> @50 : {50 ms lag}

@WU
0 is Waiting
+500 is ok
@200 <-> @+150 : {150 ms}
@enduml
