{
  "sha1": "tlrbkujwc7eesrxcr6jutvl00i2navc",
  "insertion": {
    "when": "2024-06-04T17:28:46.423Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

package bk2k_opengraph {
}

package gridelements {
}


bk2k_opengraph --|>  gridelements

@enduml
