{
  "sha1": "cr4yoadogahi3qlypxcjt4asnl92mnf",
  "insertion": {
    "when": "2024-06-01T09:03:01.938Z",
    "url": "https://forum.plantuml.net/13709/eclipse-layout-kernel?show=18389#a18389",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma layout elk

!include <osa2/Common>
!include <osa2/Hardware/all>
!include <osa2/Misc/all>
!include <osa2/Server/all>

osa_cloud(cloud, "cloud", "cloud") {
    osa_server(server, "Server VM", "Debian", "HestiaCP")
    osa_vpn(vpn, "Gateway VM", "Debian", "HestiaCP")
    osa_vpn(vpn2, "Gateway VM", "Debian", "HestiaCP")
}

@enduml
