{
  "sha1": "cnqyr1tdj60a8r5d2b1mdzre8gq65a3",
  "insertion": {
    "when": "2024-06-01T09:03:01.760Z",
    "url": "https://forum.plantuml.net/13888/preprocessing-expose-builtin-functions-reverse-function",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
!$title_color = "#033"
title {
  BackGroundColor $title_color
  FontColor %reverse_hsluv_color($title_color)
}
</style>
title
this is a title
endtitle
alice->bob
@enduml
