{
  "sha1": "jh6i4ppvf0fmavtv20m9egvb6kspn23",
  "insertion": {
    "when": "2024-06-03T18:59:31.887Z",
    "url": "http://forum.plantuml.net/9043/skinparam-handwritten-inherited-within-embedded-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam handwritten true


a->b
note right

{{
c->d
note right
     skinparam
     handwritten
     is not
     inherited
end note
}}
end note
@enduml
