{
  "sha1": "jhuozah0ctyj1udsy751jxhy61j2z24",
  "insertion": {
    "when": "2024-06-03T18:59:31.908Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

(*) --> "toto"
note left
  this is
  a long
  <b>note</b>
 end note

@enduml
