{
  "sha1": "sar4og7obrjmptxpjva2s1pwynm4ah",
  "insertion": {
    "when": "2024-06-04T17:28:39.444Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "bireva-46-dalu382"
}
@startsalt
  {+
  Random Walk segmentation
  ~~
  {+
  Define images
  Open image:  |  ^Original image ^
  Open seed:   |  ^Seed image     ^
  }
  }
@endsalt
