{
  "sha1": "onnov66l4cfexen4tcbbiezbkdlrhzo",
  "insertion": {
    "when": "2024-06-04T17:28:40.042Z",
    "url": "https://forum.plantuml.net/15360/ideas-for-2-new-json-builtins",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!$json_object = {
"name": "Mark McGwire", "hr": 65, "avg":  0.278,
"letters": ["a", "b", "c"]
}


rectangle %get_json_type($json_object)
rectangle %get_json_type($json_object.name)
rectangle %get_json_type($json_object.hr)

!if %get_json_type($json_object.letters)=="array"
rectangle %get_json_type($json_object.letters)
!endif

@enduml
