{
  "sha1": "22lcuwc0y2qh1r3sbt1h2a07k3ak4ae",
  "insertion": {
    "when": "2025-12-03T21:37:36.020Z",
    "url": "https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
+ Root
++_ Not empty
++_
'No space after -> Normal Error
@endmindmap
