{
  "sha1": "ge98mp5ilpkdfxoorbgoov126koz0xa",
  "insertion": {
    "when": "2025-12-03T21:33:23.541Z",
    "url": "https://forum.plantuml.net/20265/allow-empty-branch-in-mindmap",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
* Root
** Not empty
** 
@endmindmap
