{
  "sha1": "ppn5k3u8m9hs0ulj7xfxc9cjon19tca",
  "insertion": {
    "when": "2024-06-04T17:28:41.552Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

class simple {
}

package a {
    class SomeClass {
    }
}

package a.b {
    interface I1 {
        + Get(bits uint) uint
    }
    class c1 implements I1 {
        + Get(bits uint) uint
    }
    interface I2 extends I1 {
        + Put(data uint)
    }
    class c2 extends c1 implements I2 {
        + Put(data uint)
    }
}
@enduml
