{
  "sha1": "mrs4ujjb92w1wawvn7v0icu4p2cbuj",
  "insertion": {
    "when": "2024-06-03T18:59:35.567Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

WB is Before1
WU is Before2

@0
WU is Idle #red;line:white
WB is Idle

@100
WU -> WB : URL
WU is Waiting : some note
WB is Processing : some other note

@300
WB is Waiting
@enduml
