{
  "sha1": "bdi8wnmla5eyayo6czoik6kg4dt7ctg",
  "insertion": {
    "when": "2024-05-30T20:48:22.070Z",
    "url": "https://forum.plantuml.net/14145/plantuml-draw-odd-line?show=15972#c15972",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant A
participant B

A ->(10) B: text 10
B ->(10) A: text 10

@enduml
