{
  "sha1": "bdub5ea2zmqna2d0844dy0mizp7v13x",
  "insertion": {
    "when": "2024-05-30T20:48:22.074Z",
    "user": "plantuml@gmail.com"
  }
}
@startproject
close sunday
close saturday


LOT1/spec$begin := 13-APR-2011
LOT1/spec$work := 1
LOT1/spec$duration := 7

LOT1/real$begin := LOT1/spec$completed
LOT1/real$work := 1
LOT1/real$duration := 7

LOT2/spec$begin := LOT1$completed
LOT2/spec$work := 1
LOT2/spec$duration := 7

LOT2/real$begin := LOT2/spec$completed
LOT2/real$work := 1
LOT2/real$duration := 7

~DEV1$capacity := 1
~DEV2$capacity := 1


@endproject
