{
  "sha1": "a21hiffn0n17vf24xv0z6eh11i3qu2t",
  "insertion": {
    "when": "2024-05-30T20:48:21.806Z",
    "url": "https://github.com/plantuml/plantuml/issues/1348",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma layout smetana

class c
class a {
    int i
}

class z

note left of a::i
    This note will be purged
end note

note right of a
    This note will survive
end note

a <-- b
c <-- b

b --> d
b --> e

remove @unlinked

@enduml
