{
  "sha1": "61vht1geu5fiw7qqibwiz3cypzt53o8",
  "insertion": {
    "when": "2024-05-30T20:48:20.854Z",
    "url": "https://forum.plantuml.net/4696/notes-on-conditionnal-elements?show=18077#c18077",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (test?) then
:a;
else
:c;
endif
note: This note is on the if
stop
@enduml
