{
  "sha1": "eo3phxa34th4rgfnqdxupby4fi0rkjt",
  "insertion": {
    "when": "2024-06-01T09:03:04.799Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Foo {
field
method()
}

class Bar

Foo --> Bar : test

Foo --|> Bar2

@enduml
