{
  "sha1": "eo4xmnfmocjqk0lkeb31whjwcmyuxh6",
  "insertion": {
    "when": "2024-06-01T09:03:04.807Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state Check {
    Check: entry / lock()
    Check: exit / unlock()

    state ex <<exitpoint>>

    [*] --> LookupRecord
    LookupRecord --> ex: [found_record()]
    LookupRecord --> [*]: [default] /%n()unregister()
}
@enduml    
