{
  "sha1": "eok0jjxzmjvd5pawlgokcnpgfqiimab",
  "insertion": {
    "when": "2024-11-23T15:35:39.008Z",
    "url": "https://forum.plantuml.net/11343/activity-diagram-multi-line-and-n-management",
    "user": "The-Lum"
  }
}
@startuml
:Here is the line executed:
a  \n fprintf("hello\n", %s);
:Here is the line executed:a  \n fprintf("hello\n", %s);
@enduml
