{
  "sha1": "o788s9ef9d9pxy1g8dty9buiqfrezaw",
  "insertion": {
    "when": "2026-02-18T18:13:55.546Z",
    "url": "https://github.com/plantuml/plantuml/issues/1682",
    "user": "plantuml@gmail.com"
  }
}
@startuml
opt test
    ref over A, B
        SomeSequence
    end ref
end

note left 
Appears on the right side, not on the left even though "note left" is used.
end note
@enduml
