{
  "sha1": "md1wj7sc416w97rtna8zmbb58ele8jg",
  "insertion": {
    "when": "2024-06-03T18:59:35.088Z",
    "url": "http://forum.plantuml.net/7710/teoz-and-%26-within-groups-is-not-working",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
Bob -> Alice : Secret
Alice -> Stacy : Rumors
@enduml
