{
  "sha1": "hhphcma9ebu61nqyv2a546r2wqsht02",
  "insertion": {
    "when": "2024-06-03T18:59:29.581Z",
    "user": "plantuml@gmail.com"
  }
}
@startproject
close sunday
close saturday

LOT1/spec$begin := 13-APR-2011
LOT1/spec$work := 1
LOT1/spec$duration := 7

LOT1/real$begin := LOT1/spec$completed
LOT1/real$work := 1
LOT1/real$duration := 7

^FIN_LOT_1 := LOT1$completed

LOT2/spec$begin := ^FIN_LOT_1
LOT2/spec$work := 1
LOT2/spec$duration := 7

LOT2/realA$begin := LOT2/spec$completed
LOT2/realA$work := 1
LOT2/realA$duration := 7

LOT2/realB$begin := LOT2/spec$completed
LOT2/realB$work := 1
LOT2/realB$duration := 7

~DEV1$capacity := 1
~DEV2$capacity := 1

LOT1/spec : ~DEV1
LOT1/real : ~DEV2
LOT2/spec : ~DEV1
LOT2/realA : ~DEV2
LOT2/realB : ~DEV2

@endproject
