{
  "sha1": "hhybr3c056dj7xzx6bwivhcn6zgzmw7",
  "insertion": {
    "when": "2024-06-03T18:59:29.581Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!ijk = 'foo'
Alice -> Bob : You should see foo and not bar
!if ijk == 'foo1'
Alice -> Bob : foo1
!elseif ijk == 'bar'
Alice -> Bob : bar
!elseif
Alice -> Bob : foo
!endif
Alice -> Bob : B
@enduml
