{
  "sha1": "a5elbk1z6ai9ve1dagcp8qljwyt7qzj",
  "insertion": {
    "when": "2024-11-27T18:06:12.659Z",
    "url": "https://forum.plantuml.net/19243/unicode-u-005c-backslash-in-tooltip-text-causes-error",
    "user": "The-Lum"
  }
}
@startwbs
+ raw string literals \
 [["Example:\n\nconst char* msg1 = <U+0022><U+005C>nHello,world!<U+0022>;" TP]]
@endwbs
