{
  "sha1": "a5wccyxioxnzwt1yffqjcacqbvicxe1",
  "insertion": {
    "when": "2024-05-30T20:48:21.826Z",
    "url": "https://forum.plantuml.net/12124/order-mismatch-embedded-diagram-creole-deployment-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
rectangle r [
{{
file f1
}}
-- text between f1 and f2 --
{{
file f2
}}
{{
file f3
}}
]
@enduml
