{
  "sha1": "4txvm9bmeotrniqry5xqy18pbc9vsqg",
  "insertion": {
    "when": "2024-06-03T18:59:31.929Z",
    "url": "https://github.com/plantuml/plantuml/issues/62",
    "user": "plantuml@gmail.com"
  },
  "humhash": "lakari-33-mone874"
}
@startsalt
{
{*
A | B
C | *
}
}
@endsalt
