{
  "sha1": "3euxmc6c5v5v0a8y3hgafwn0sl6erh9",
  "insertion": {
    "when": "2024-06-01T09:03:05.560Z",
    "url": "http://alphadoc.plantuml.com/doc/dokuwiki/en/nwdiag-issues",
    "user": "plantuml@gmail.com"
  },
  "humhash": "temeca-88-zagi087"
}
@startnwdiag
nwdiag {
  a
  b
}
@endnwdiag
