{
  "sha1": "iox8pwg9vjlb926t26ob6t6y3nvir0j",
  "insertion": {
    "when": "2024-06-03T18:59:31.027Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
concise "LR" as LR
concise "ST" as ST

LR is AtPlace
ST is AtLoad

@LR
0 is Lowering
100 is Lowered
350 is Releasing
 
@ST
0 is AtLoad
200 is Moving
@enduml
