{
  "sha1": "1p0czqxi4u5gxlmpl5zefaxocbjpb19",
  "insertion": {
    "when": "2024-06-04T17:28:39.372Z",
    "url": "https://forum.plantuml.net/18128/gantt-diagram-vertical-separator-styling?show=18128#q18128",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
<style>
separator {
  LineColor red
}
verticalSeparator {
  LineColor green
}
</style>

[task1] lasts 1 week
[task2] starts 20 days after [task1]'s end and requires 3 days

Separator just at [task1]'s end
Separator just 2 days after [task1]'s end

-- separator title --

Separator just at [task2]'s start
Separator just 2 days before [task2]'s start
@endgantt
