{
  "sha1": "1pg5maai0nm07xgafz133nddbkk5wlh",
  "insertion": {
    "when": "2024-05-30T20:48:21.046Z",
    "url": "https://forum.plantuml.net/14494/is-it-possible-to-color-the-days-in-the-default-gantt-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2026-01-19
D+13 to D+15 are colored in blue

[Var. A] as [A] lasts 9 days
[Var. B] as [B] lasts 5 days
[C] lasts 10 days
[B] starts at [A]'s end
[A] is colored in Fuchsia/FireBrick
[B] is colored in GreenYellow/Green
[C] starts at D+16


D+10 is colored in gold
D+11 is colored in orange
D+8 is colored in red
-- note --
@endgantt
