{
  "sha1": "ap3ufphrhjimr5d5f75dx19qtg7g04g",
  "insertion": {
    "when": "2024-05-30T20:48:21.922Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
hide empty methods
hide circle

'skinparam linetype ortho

!define PK <size:12><&key></size><b>
!define FK <size:12><&link-intact></size><i>
!define PP <size:12><&caret-right></size>

class "<b> Some dict </b>" as d {
    PK ID      %tab()%tab() Integer
    PP Name    %tab() String
}

class "<b> Some entity </b>" as e {
    PK ID       %tab()%tab() Integer
    FK Type     %tab()%tab() Integer
    PP Some field %tab() JSON
}

e::Type }-- d::ID

@enduml
