{
  "sha1": "2oh7k7qzlnxy7n9ib6pvgg5cfcauxov",
  "insertion": {
    "when": "2024-05-30T20:48:20.058Z",
    "url": "https://forum.plantuml.net/14810/additional-text-for-elseif-missing-when-using-useverticalif",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma useVerticalIf on
start
if (foo) then (ok3)
  :f1;
(additional text) elseif (foo2) then (ok2)
  :f2;
else (notok)
  :f3;
endif
@enduml
