{
  "sha1": "cwm2m5q4femzpzo7u7ycp2xl7se31qk",
  "insertion": {
    "when": "2024-06-01T09:03:02.163Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
!theme silver
* 'Head'
** 'Branch One'
** 'Branch Two'
** 'Branch Three'
** 'Branch Five'
*** 'Subbranch Five-One'
@endwbs
