{
  "sha1": "i5w355h4s7k243g5ynv3b9b64u45boo",
  "insertion": {
    "when": "2024-06-03T18:59:30.359Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    class_1 -> class_2
    '...
    class_2 -> class_1

    newpage Second Page
    class_1 -> class_2
    'The following line causes swimlanes on first page to disappear
    ...
    class_2 -> class_1
@enduml
