{
  "sha1": "i5xx8imwhx7zcg3lgnltle4hl7yyelh",
  "insertion": {
    "when": "2024-06-03T18:59:30.373Z",
    "url": "https://github.com/plantuml/plantuml-stdlib/issues/63#issuecomment-1314774419",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!include <awslib10/AWSCommon>
!include <awslib10/General/User>

<style>

file {
   HorizontalAlignment left
   FontColor blue
}
</style>

User(user, "Trusted user", "")

file policy <<policy>>

user -- policy
@enduml
