{
  "sha1": "me7yk17w61vk1jujjya15b5ulsuwtq9",
  "insertion": {
    "when": "2024-11-23T15:35:39.159Z",
    "url": "https://forum.plantuml.net/6003/can-a-defined-constant-be-parsed-correctly-after-n",
    "user": "The-Lum"
  }
}
@startuml
!TEST=something
a[#blue]->b: test:%n()TEST
note right: The test is correct:%n()TEST
a-[#green]>b: test:%n() TEST
note left: The test is correct:%n() TEST
@enduml
