{
  "sha1": "mevps5pls426ig3aongq33krpqftb3a",
  "insertion": {
    "when": "2024-06-03T18:59:35.153Z",
    "url": "https://forum.plantuml.net/13560/gantt-issue-with-yearly-print-when-project-begin-beginning",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
projectscale yearly zoom 2
Project starts the 2020-07-01
[Prototype design] lasts 400 days
@endgantt
