{
  "sha1": "e21msntqznwv0njlzpg523fogscnwer",
  "insertion": {
    "when": "2024-06-01T09:03:03.763Z",
    "url": "https://forum.plantuml.net/12507/repeat-over-multiple-swimlanes-bugged",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|Developer|
start
repeat :Step1;
|Owner|
->yes1;
repeat while (Step 2) is (return)
->yes2;
|Developer|
:Step 3;
stop

@enduml
