{
  "sha1": "e2tutbh17mugjxvdu9ufokpe2onp9bz",
  "insertion": {
    "when": "2024-06-01T09:03:03.793Z",
    "url": "http://forum.plantuml.net/8242/set-background-color-of-latex-math-entries",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
while (yyyyyyyyyyyyyyyyyyyy)
:test;
endwhile
end
@enduml
