{
  "sha1": "9qnzzz7xkxq3k258uo9sil31csep5ea",
  "insertion": {
    "when": "2025-10-01T18:22:58.340Z",
    "user": "The-Lum"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***[#green]:L21 a
L21 b;
***(l2):L22 a
L22 b;

l2 -> l1
@endwbs
