{
  "sha1": "9qo1x8o6jvc52ksaabcgx1fg86v81uo",
  "insertion": {
    "when": "2025-10-01T18:22:57.927Z",
    "user": "The-Lum"
  }
}
@startwbs
* R
** Line 1
*** L11
** Line 2
***<_:L21 a
L21 b;
***_:L22 a
L22 b;
@endwbs
