{
  "sha1": "2w99667bs58kebu0c7yahmmzfiokcla",
  "insertion": {
    "when": "2025-10-16T19:14:53.917Z",
    "url": "https://github.com/plantuml/plantuml/pull/2382",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title Between min-max

analog "Analog" from 350.00 to 450.00 as A
A ticks every 50

@0
A is 350

@50
A is 360

@100
A is 450

@300
A is 350
@enduml
