{
  "sha1": "izl358riblexc8tpo0h871j1rlv4gkl",
  "insertion": {
    "when": "2024-06-03T18:59:31.350Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

box "Box1"
       participant A
end box

box "Box2 with a very long title END"
       participant B
end box

box "Box3"
       participant C
       participant D
end box

box "Box4 with a very long title that is even longer END"
       participant E
       participant F
end box

box "Box5 with a very long title that is even longer END"
       participant G
end box

'participant H

A->B

@enduml
