{
  "sha1": "izpwqte1aidajquxfte6tpm4imknjtz",
  "insertion": {
    "when": "2026-02-18T18:13:55.562Z",
    "url": "https://github.com/plantuml/plantuml/pull/2499",
    "user": "plantuml@gmail.com"
  }
}
@startuml
analog "Analog" between 350 and 450 as A

@0
A is 350

@100
A is 450

@300
A is 350
@enduml
