{
  "sha1": "e4esqhedzr25imwdn9whqae4tme73n",
  "insertion": {
    "when": "2024-10-25T11:14:05.670Z",
    "url": "https://github.com/plantuml/plantuml/issues/1484",
    "user": "The-Lum"
  }
}
@startuml
state S {
  state a
--
  state b {
    state c
  }
  c -> d
}
@enduml
