{
  "sha1": "jli52nh8gt7onc9o07aj8t4unknup0",
  "insertion": {
    "when": "2024-06-03T18:59:32.013Z",
    "url": "https://plantuml.com/fr/gantt-diagram#c5aeee17b294caf8",
    "user": "plantuml@gmail.com"
  }
}
@startgantt

-- test01 --

[task01] lasts 4 days
note bottom
'note left
memo1 ...
memo2 ...
explanations1 ...
explanations2 ...
end note

[task02] lasts 8 days
[task01] -> [task02]
note bottom
'note left
memo1 ...
memo2 ...
explanations1 ...
explanations2 ...
end note
-- test02 --

[<back:red>task03] as [t3] lasts 7 days
[t3] -> [<back:red>t4]
@endgantt
