{
  "sha1": "8561dlul3m481ybl5k019wn2509hdwl",
  "insertion": {
    "when": "2024-05-30T20:48:21.342Z",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
!theme aws-orange
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endmindmap
