{
  "sha1": "qvxvxfzbdh6kbeh8lvb89rfncu4hfpp",
  "insertion": {
    "when": "2024-06-04T17:28:42.968Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam UsecaseBorderThickness 0.5
usecase foo1
@enduml
