{
  "sha1": "rz6w8qin7184s0uaubiues2qjp11wnp",
  "insertion": {
    "when": "2024-06-04T17:28:44.453Z",
    "user": "plantuml@gmail.com"
  }
}
@startregex
\[\[[%s]*\{(.*)\}[%s]*\]\]|\[\[[%s]*\{([^{}]*)\}[%s]*([^\[%s\{\}\[\]][^\[\]]*)[%s]*\]\]|\[\[[%s]*([^\s%g{}\[\]]+?)[%s]*\{(.+)\}[%s]*\]\]|\[\[[%s]*([^%s%g\[\]]+?)(?:[%s]*\{([^{}]*)\})?(?:[%s]([^%s\{\}\[\]][^\[\]]*))?[%s]*\]\]
@endregex
