{
  "sha1": "8791c444vw2tyzyjtst4i9zplf4sx2l",
  "insertion": {
    "when": "2024-06-01T09:03:06.117Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package boo1.boo2 {
}

package foo1.foo2.foo3 {
class A
class B
}

boo1.boo2 +--- foo1.foo2.foo3

@enduml
