{
  "sha1": "pi0fs7lldsffh93ztd1jlbbunrynm59",
  "insertion": {
    "when": "2024-06-04T17:28:41.220Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "gerezu-38-kobe658"
}
@startuml

skinparam usecaseFontSize 8

"Main Admin" as Admin
"Use the application" as (Use)

User -> (Start)
User --> (Use) : A small label

Admin ---> (Use) : This is\nyet another\nlabel

@enduml
