{
  "sha1": "m3cgvwgoizm15e4r4j1oos5nlvryri0",
  "insertion": {
    "when": "2024-06-03T18:59:34.817Z",
    "url": "https://github.com/plantuml/plantuml/issues/79",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class A {
    - {abstract} test() : void
    - {static} m_instance : A
}
note left
this is **bold**
end note
@enduml
