{
  "sha1": "sslm8m2v39fvdxrt3e2yh1i1nxjwcyo",
  "insertion": {
    "when": "2024-06-04T17:28:45.411Z",
    "url": "https://forum.plantuml.net/13071/newline-in-state-diagrams-is-inconsistent?show=13073#c13073",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state s1 {

s1 : line1\n  line2\n    line3
state c
}
@enduml
