{
  "sha1": "cehemzv6fyq1ott8qpqsbxb9ajqe3c1",
  "insertion": {
    "when": "2025-09-25T19:50:52.739Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***<[#green] L21
***<(l2) L22

l2 -> l1
@endwbs
