{
  "sha1": "ceur1ff0d7be3xph35prpx7e550wm0f",
  "insertion": {
    "when": "2024-06-01T09:03:01.347Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

title this <b>title</b>zis quite defined on several lines
Bob -> Alice

@enduml
