{
  "sha1": "h3srqs181tgvolfq6mrjme1ofc0xkbk",
  "insertion": {
    "when": "2024-06-03T18:59:29.137Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
(*) --> "[[http://www.google.com/note1]]
This is
my activity"

note right
[[http://www.google.com/note2]]
example2
end note
@enduml
