{
  "sha1": "7bjem44qa3fbp2du1w84eog1vntfpu0",
  "insertion": {
    "when": "2024-05-30T20:48:21.974Z",
    "url": "http://forum.plantuml.net/8491/skinparam-from-command-line-breaks-salt-diagrams",
    "user": "plantuml@gmail.com"
  },
  "humhash": "baboxu-045-dekiko"
}
@startsalt
skinparam fixCircleLabelOverlapping true
{
Just plain text
[This is my button]
() Unchecked radio
(X) Checked radio
[] Unchecked box
[X] Checked box
"Enter text here "
^This is a droplist^
}
@endsalt
