{
  "sha1": "73wshkvxwmnjiymnft5tfjk1bi9ewyb",
  "insertion": {
    "when": "2025-10-13T18:09:46.580Z",
    "url": "https://github.com/plantuml/plantuml/pull/2376",
    "user": "The-Lum"
  }
}
@startuml
* A
** B
*** C
@enduml
