{
  "sha1": "25pt1rflewpy57qvv4js0vwg4remxtq",
  "insertion": {
    "when": "2024-05-30T20:48:19.906Z",
    "url": "https://forum.plantuml.net/13298/allow-style-on-wbs-boxless-node",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
<style>
wbsDiagram {
  FontColor blue
  FontStyle bold  
  FontSize 13

  element {
    BackGroundColor palegreen
    LineThickness 1.0
  }

  .red {
    FontColor red
    FontStyle bold  
    FontSize 13
    MaximumWidth 50
  }
}
</style>
+ the partner workpackage
++ blue
+++ blue workpackage
+++_ blue boxless workpackage 
++ red <<red>>
+++ red workpackage <<red>>
+++_ red boxless workpackage <<red>>

@endwbs
