{
  "sha1": "banrzgd4hehkkykqvysvyursu42ijcu",
  "humhash": "jucixo-62-pusu114",
  "insertion": {
    "when": "2026-05-15T21:03:26.241Z",
    "url": "https://github.com/plantuml/plantuml/issues/2685",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set separator ∷

package a∷d {
    class DDD
}

class a∷b∷C {}

a∷b∷C --|> a∷d∷DDD
@enduml
