{
  "sha1": "hs5ac3zv6uclermpafumkm85lo94tnz",
  "insertion": {
    "when": "2024-06-03T18:59:29.959Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam arrowThickness 4
class c1
class c2
class c3
c1 -[dotted]-> c2
c1 -[dashed,thickness=2]-> c3
@enduml
