{
  "sha1": "j7e61wbah0ptouls6pt5v8o4gplr6w5",
  "insertion": {
    "when": "2024-06-03T18:59:31.572Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set separator none
skinparam packageBorderColor #FF0000
package Pack1 {
[Comp1]
[Comp3]
[Comp4]
}
[Comp1] - [Comp2]
@enduml
