{
  "sha1": "ddr26f21qd2e4wtnss6qhfc6q96n7s",
  "insertion": {
    "when": "2024-06-01T09:03:02.870Z",
    "url": "https://github.com/plantuml/plantuml/issues/134",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
skinparam noteTextAlignment right
Alice->Bob:m1
Bob->Charlie:m2
note across
this right
on several lines
end note
Bob->Alice
@enduml
