{
  "sha1": "py9zxfnjy6zinmhflkchgqzn0o4lpl6",
  "insertion": {
    "when": "2024-06-04T17:28:41.869Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:er>
:<< Automobile >>
Pinto;
stop
@enduml
