{
  "sha1": "o522s2321lt1vcc9g5etqs9jyqwajm9",
  "insertion": {
    "when": "2024-06-03T18:59:35.025Z",
    "url": "https://github.com/plantuml/plantuml/issues/104#issuecomment-1368253645",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Project starts 2026-01-19
<style>
element {
  MaximumWidth 100
}
</style>

class foo1 {
this is a very long description for class
}

note left
this is a very long long long long long description for note
end note

@enduml
