{
  "sha1": "o5lbbfbocd8x5u7kni8883l99usjpg8",
  "insertion": {
    "when": "2024-06-04T17:28:39.399Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Alice -> Bob : hello%n()on%n()several%n()lines
note left
	this note on one line
endnote
activate Bob
Bob --> Alice : ok
@enduml
