{
  "sha1": "80tog6jl4jto4movc6hxdpt7jyujnwc",
  "humhash": "tunolu-94-kure415",
  "insertion": {
    "when": "2026-07-25T16:32:32.602Z",
    "url": "https://github.com/plantuml/plantuml/issues/2789",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
A->B
opt
  B->C: test
  |||
  B->C: test
end
@enduml
