{
  "sha1": "d2562rw0y1arg9znefl13g2chdmxavg",
  "insertion": {
    "when": "2024-06-01T09:03:02.425Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:foo5;
-[#hotpink]->
while (some test) is (true)
  -[#gold]->
  :foo6;
  -[#green]->
  :foo7;
  -[#black]->
endwhile (false)
-[#greenyellow]->
:foo8;
@enduml
