{
  "sha1": "d2ewr9q5vc8obxlp3oi4ujn1atu1zlt",
  "insertion": {
    "when": "2024-06-01T09:03:02.433Z",
    "url": "https://forum.plantuml.net/17926/sprite-transparent-only-jar-defined-sprites-are-working",
    "user": "plantuml@gmail.com"
  }
}
@startuml
sprite Netw jar:archimate/network

sprite $printer [15x15/8z] NOtH3W0W208HxFz_kMAhj7lHWpa1XC716sz0Pq4MVPEWfBHIuxP3L6kbTcizR8tAhzaqFvXwvFfPEqm0

skinparam backgroundcolor blue
skinparam rectanglebackgroundcolor red/yellow

rectangle "Netw via jar <$Netw> printer via code <$printer>" as netw {
[D] -> [E]: "Netw via jar <$Netw> printer via code <$printer>"
}
@enduml
