{
  "sha1": "2zcjl246vbkbiqwra31f1u5tb21rd5p",
  "insertion": {
    "when": "2024-05-30T20:48:20.134Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Bob -> Alice : hello
note left
  this is a note
  {{
    object o1 {
      foo
    }
    o1 --> o2
  }}
  On the end
end note
@enduml
