{
  "sha1": "ntrujymcbbrxye9yui4c9h8xo0lubx7",
  "insertion": {
    "when": "2024-06-04T17:28:39Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
set separator none
state foo1 {
  state foo2
}
state foo3
foo2 --> foo3

state foo4
foo1 --> foo4
@enduml
