{
  "sha1": "d6iyi0je29bnubaqeli9d88xymzx13z",
  "insertion": {
    "when": "2024-06-01T09:03:02.574Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=5438/plantuml-crashes-with-this-example",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam monochrome true
start
:Text ;
repeat
:Text 0;
   if (condition A) then (yes)
      :Text 1;
   elseif (condition B) then (yes)
       :Text 2;
   else (no)
:Text 3;
   endif
:Text 5;
if (condition B ? ) then (yes)
  :Text 6;
else (no)
  break
endif
repeat while (condition C ? )is (yes) not (no)
->
 :Text 8;
stop
@enduml
