{
  "sha1": "d6p5h7r52ly9gbmz57j1z6at3bk2jxb",
  "insertion": {
    "when": "2024-05-30T20:48:20.694Z",
    "url": "https://forum.plantuml.net/10676/repeat-plus-colour?show=10746#c10746",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam activity {
  BackgroundColor<<MyGreen>> LightGreen
}
:A;
repeat:B; <<MyGreen>>
repeat while (C) 
@enduml
