{
  "sha1": "d6qkyjqlvc1s6c2zej8rlzlkbmyjuki",
  "insertion": {
    "when": "2024-06-01T09:03:02.584Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class cl1
class cl2
cl1 --> cl2 #red;text:blue : foo3

note left of cl2 #blue;line.bold:purple;text:777 : some info

note right of cl1 #blue;line.bold:purple;text:FF0
  some other info2
end note

@enduml
