{
  "sha1": "6x6c30ywuwki7bev8jk67g1ta2n3mz1",
  "insertion": {
    "when": "2025-11-03T18:33:05.170Z",
    "url": "https://github.com/plantuml/plantuml/pull/2404",
    "user": "plantuml@gmail.com"
  }
}
@startuml test
start
:L0
{{
start
:L1;
stop
}}
;
stop
@enduml
