{
  "sha1": "6xomu6nkzcss6wcysk6lj9icckl1mz1",
  "insertion": {
    "when": "2024-05-30T20:48:21.074Z",
    "url": "https://github.com/plantuml/plantuml/issues/180",
    "user": "plantuml@gmail.com"
  }
}
@startuml

start

:Step One;
partition "Paths OK?" {
    note
        Arrow comments
        are quite tight.
    end note
	switch (Test a variable)
		case (case 1)
			:Select One;
		case (case 2)
			:Select Two;
		case (case 3)
			:Select Three;
		case (case 4)
			:Select Four;
	endswitch
}

partition "Not always" {
    note
        But it still breaks
        under some conditions:
        
        (Also, I don't get why
        is there so much space
        because of this note...)
    end note
	switch (Test a variable)
		case (case 1)
			:What if this is wider than expected?;
		case (case 2)
		case (case 3)
	endswitch
	:It's //a bit// broken on the left;
	switch (Test a variable)
		case (case 1)
		case (case 2)
		case (case%n() it %n()breaks)
			:What if this is wider?/
	endswitch
	:Also on the right!;
	note
	 If you use "What if this is a bit wider?"
	 string above, it works better, although
	 it still breaks in the beginning of
	 the arrow.
	end note
}

partition "Comments%n()hidden" {
    note
        I suppose this is something
        that happen by design, but
        it could at least throw an
        error... This is in fact a
        simple ""if"" sentence.
    end note
	switch (Test a variable)
		case (case 1)
		case (case 2)
		case (case 3)
			:Select 3/
	endswitch
}

partition "Miscalculated upper%n()margin or padding" {
	switch (Test a variable)
		case (This is a multiple%n()line and long text%n()arrow comment)
			:Option One/
		case (This is another multiple%n()line and long text%n()arrow comment)
			:Multiple%n()line option Two/
		case (else%n()with %tab()hree %n()lines)
			:In else case.../
	endswitch
}

:Let's go}

stop

@enduml
