{
  "sha1": "nh1g12l5dvgxzy3pb0ssaegtrlnp1d9",
  "insertion": {
    "when": "2025-05-14T17:39:22.100Z",
    "url": "https://github.com/plantuml/plantuml/pull/2177",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
<style>
sequenceDiagram {
  LineColor blue
  LineThickness 3
}
</style>

X -> X
X -> Y
newpage 
X -> X
@enduml
