{
  "sha1": "2at78ns1blm7neob5ab2cmoh59mc2my",
  "insertion": {
    "when": "2024-05-30T20:48:19.946Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam sequenceGroupBorderThickness 1
skinparam noteBorderThickness 3
skinparam sequenceGroupBorderColor blue
skinparam sequenceGroupBackgroundColor red

alt
Bob -> Alice : hello
note left: foo
end group
@enduml
