{
  "sha1": "f1h5lfrz695243t3ev04usqgeacnaja",
  "insertion": {
    "when": "2024-06-01T09:03:05.407Z",
    "url": "https://forum.plantuml.net/11288/mixed-signal-timing-diagram?show=11369#c11369",
    "user": "plantuml@gmail.com"
  }
}
@startuml
analog "Vcore" as VDD
analog "VCC" between -4.5 and 6.5 as VCC
VCC ticks num on multiple 3
VCC is 200 pixels height

@0
VDD is 0
VCC is 3
@2
VDD is 0
@3
VDD is 6
VCC is 6
VDD@1 -> VCC@2 : "test"
@enduml
