{
  "sha1": "f1pxgrxvle0ktgktjv88p5usxp8py6g",
  "insertion": {
    "when": "2024-06-01T09:03:05.416Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=5432/svg-monospace-output-has-wrong-font-family",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class foo {
""monospaced""
dummy
}
@enduml
