{
  "sha1": "f1rf8akyf039v71uoi3jdzrpnwh2a3j",
  "insertion": {
    "when": "2024-06-01T09:03:05.424Z",
    "url": "https://forum.plantuml.net/16663/small-rendering-difference-between-default-and-teoz",
    "user": "plantuml@gmail.com"
  }
}
@startuml
First -> Second : message
activate First
activate Second
Second ->  First: response
deactivate First
deactivate Second
@enduml
