{
  "sha1": "o2d9w8e1v0fgasynpg9buj4qxffwvdi",
  "insertion": {
    "when": "2024-06-06T17:24:18.632Z",
    "url": "https://github.com/plantuml/plantuml/issues/1723",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
'Issue #1723
dummy -> A ++: first step

A -> A: test
A -> B --++: second step

B -> B: test
B -> C--: third step
@enduml
