{
  "sha1": "o2n1ekd35acu7zkujj818kgjaodhmwq",
  "insertion": {
    "when": "2024-06-04T17:28:39.282Z",
    "url": "https://github.com/plantuml/plantuml/issues/1461",
    "user": "plantuml@gmail.com"
  }
}
@startuml
 	class SomeClass
    
    note top of SomeClass
      Monitors the workspace and collects all changed files
    end note
    
    footer Rendered with PlantUML version
 
@enduml
