{
  "sha1": "o2rf5tn9rmlrol43gmzm7n2t9967nvn",
  "insertion": {
    "when": "2024-06-04T17:28:39.297Z",
    "url": "https://github.com/plantuml/plantuml-server/issues/94",
    "user": "plantuml@gmail.com"
  }
}
@startuml
foo --(( bar
foo --(( bar1
foo --(( bar2
foo --(( bar3

azer -(( bar4
bar7 ))- toto
@enduml
