{
  "sha1": "o2ylvf9ursukrh49b1y29boet8vkgaj",
  "insertion": {
    "when": "2024-06-04T17:28:39.317Z",
    "url": "http://forum.plantuml.net/7360/drawing-single-detach-circle-after-symbol-level-with-desicion",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if (is a = b) then (yes)
  :next;
 else
  (A)
  detach
endif
 
stop
@enduml
