{
  "sha1": "oi0tfzm8ehtrojwgpfd8z0bu26fewn4",
  "insertion": {
    "when": "2024-06-04T17:28:39.907Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
() "my interface"
() "a brain new interface"

[component1] -- () "my other interface"

note left of ()"my interface" #red : this is a note
note top of () "a brain new interface" #blue
 this note
 is long
end note

@enduml
