{
  "sha1": "atm3lr8ayjgioqffw288ej3pq7rki9s",
  "insertion": {
    "when": "2025-12-05T20:00:28.838Z",
    "url": "https://github.com/plantuml/plantuml/pull/2452",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
+ 
++ 
++ 
+++ 
+++ 
++++ 
++++ 
+++ 
@endmindmap
