{
  "sha1": "3pw95usaj3qmjshjsgvctl9zp9ea3ap",
  "insertion": {
    "when": "2025-10-01T18:22:56.767Z",
    "url": "https://github.com/plantuml/plantuml/issues/2363",
    "user": "The-Lum"
  }
}
@startwbs
* Root
** C1
**(c2) C2
*** C21
***(c22) C22

c22 -> c2 #green
@endwbs
