{
  "sha1": "owiq1slfubl0cxhxi67wqi4muek2297",
  "insertion": {
    "when": "2026-02-24T15:52:50.903Z",
    "url": "https://github.com/plantuml/plantuml/pull/2499",
    "user": "plantuml@gmail.com"
  }
}
@startuml
clock clk with period 1
binary EN

@0
EN is low

@2
EN is high

@3
EN is low
@enduml
