{
  "sha1": "gjd9b0xae79j423lo880d38sas52le5",
  "insertion": {
    "when": "2024-06-01T09:03:07.865Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start;
if (Page.onSecutiryCheck()) then (true)
    if (isForwarded?) then (no)
        if (continue processing?) then (yes)
           :goto bareB1;
        endif
    endif
    :bareB1;
endif
:FIN;
stop
@enduml
