{
  "sha1": "b8aoz1a8e6xdfqavypghp6arr2apybt",
  "insertion": {
    "when": "2024-05-30T20:48:22.042Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Foo $a
Foo -- Goo
class Bar $z
note "A note" as N1 $z
N1 .. Bar
@enduml
