{
  "sha1": "ro1odpfnmfxga6bdnksci8d3swxctg0",
  "insertion": {
    "when": "2024-06-04T17:28:44.053Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

<style>
document {
  BackgroundColor transparent
}
</style>

class foo1
class foo2

@enduml
