{
  "sha1": "4blvwvk3pcyoo3g1uupqps5hgtc0z5s",
  "insertion": {
    "when": "2024-05-30T20:48:20.470Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:start2 on; <<#AAAAAA;line:blue;text:red>>
@enduml
