{
  "sha1": "7jprlhqju04i41s0uz1tv61powwoigr",
  "insertion": {
    "when": "2024-05-30T20:48:21.222Z",
    "url": "https://forum.plantuml.net/15544/stereotype-priorities-changed-compared-implementations",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    skinparam rectangle<<RedContainer>> {
        StereotypeFontColor red
        FontColor red
        BackgroundColor lightred
        BorderColor darkred
        RoundCorner 0
        DiagonalCorner 18
    }

    skinparam rectangle {
        StereotypeFontColor blue
        FontColor blue
    }
    
    skinparam rectangle<<ItalicContainer>> {
        FontStyle italic
        FontSize 8
    }
    
    skinparam rectangle<<GreenContainer>> {
        StereotypeFontColor green
        FontColor green
        BackgroundColor lightgreen
        BorderColor darkgreen
        RoundCorner 15
        DiagonalCorner 0
    }

	title produces a red+smallItalic rectangle
    rectangle  "C1"  <<ItalicContainer>><<RedContainer>>  as C1
@enduml
