{
  "sha1": "6phrnyxbecppzabm5dxcnf94tfztcne",
  "insertion": {
    "when": "2024-05-30T20:48:21.002Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
robust "Web Browser" as WB
concise "Web User" as WU

@0
WU is Idle
WB is Idle

@100
WU -> WB : URL
WU is Waiting : some note
WB is Processing : some other note

@300
WB is Waiting
@enduml
