{
  "sha1": "6pru8crpasnxfhhoq3in6p1gwvfghcx",
  "insertion": {
    "when": "2024-05-30T20:48:21.014Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant Alice as a
participant Bob   as b

  [o/- b : ""  [o/-""
@enduml
