{
  "sha1": "6zir5t5woz8dm277xzxjxikwy3omvb8",
  "insertion": {
    "when": "2024-05-30T20:48:21.086Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
note over Locus,Cassandra: [[{3 things Bill Gates thinks coand get rid of greenhouse gases}]]test it
@enduml
