{
  "sha1": "q7zwc1aqstb1p1xh77q87zvhfz26zrq",
  "insertion": {
    "when": "2024-06-04T17:28:42.111Z",
    "url": "https://github.com/plantuml/plantuml/pull/329",
    "user": "plantuml@gmail.com"
  }
}
@startuml
[*] -> State1
State1 --> State2 : Succeeded
State1 --> [*] : Aborted
State2 --> State3 : Succeeded
State2 --> [*] : Aborted
state State3 {
  state "Accumulate Enough Data" as long1
  long1 : Just a test
  [*] --> long1
  long1 --> long1 : New Data
  long1 --> ProcessData : Enough Data
  State2 --> [H*]: DeepResume
}
State3 --> State2 : Pause
State2 --> State3[H]: Resume
State3 --> State3 : Failed
State3 --> [*] : Succeeded / Save Result
State3 --> [*] : Aborted
@enduml
