{
  "sha1": "sdh5udoft1fqvz37xg1y3uzb13actho",
  "insertion": {
    "when": "2025-10-01T18:22:58.530Z",
    "user": "The-Lum"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***<_[#green]:L21 a
L21 b;
***<_(l2):L22 a
L22 b;

l2 -> l1
@endwbs
