{
  "sha1": "renrbkpv11ix5t2ydeuutqtm95w3q81",
  "insertion": {
    "when": "2024-06-04T17:28:43.681Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
package org.jgrapes [[jgrapes]] {
    package org.jgrapes.core [[org/jgrapes/core/package-summary.html#package.description]] {
    }

    package org.jgrapes.io {
    }

    package org.jgrapes.http {
    }
}
@enduml
