{
  "sha1": "reznu5cjjvrn6sus2358yrog4oa0aem",
  "insertion": {
    "when": "2024-06-04T17:28:43.707Z",
    "user": "plantuml@gmail.com"
  }
}
@startcute
 stick color=green position=30,30 dimension=20,5 rotation=10
 stick color=green position=30,34 dimension=15,5 rotation=10
 stick color=green position=30,38 dimension=10,5 rotation=10
@endcute
