{
  "sha1": "e2avs1mtfvurexxg1wd2bousxjtgohx",
  "humhash": "tusoma-63-dexa941",
  "insertion": {
    "when": "2026-06-11T14:03:39.328Z",
    "url": "https://github.com/plantuml/plantuml/issues/1973",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
projectscale monthly zoom 4

Project starts the 2024/11/07 
[Task1] on {Alice} requires 100 days
[Task2] on {Bob:50%} requires 20 days
then [Task3] on {Alice:25%} requires 10 days
then [Task4] on {Alice:25%} {Bob} requires 10 days

@endgantt
