{
  "sha1": "ojsr7917q1fyszr4r45ld47oyojegxj",
  "insertion": {
    "when": "2024-06-04T17:28:39.961Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
[AA] <<static lib >>
[BB] <<shared lib >>
[CC] <<static lib >>
node node1
node node2 <<shared node >>
database Production
skinparam component {
backgroundColor<<static lib >> DarkKhaki
backgroundColor<<shared lib >> Green
}
skinparam node {
borderColor Green
backgroundColor Yellow
backgroundColor<<shared node >> Magenta
}
skinparam databaseBackgroundColor Aqua
@enduml
