{
  "sha1": "qwi2e8xyvvpyfcnbgfw21n2cy280juz",
  "insertion": {
    "when": "2024-06-04T17:28:43.015Z",
    "url": "http://plantuml.sourceforge.net/qa/?qa=1768/how-tell-activity-beta-start-drawing-from-the-top-the-swimlane",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|QA|
start

:Finds issue
(Bug or Missing feature);

if (BDD needs to be updated?) then (yes)
    :Update BDD scenario;
else
endif

|Developer|

if (Unit tests accounts for issue?) then (no)
    :Add Unit test;
else
endif

repeat
    :Modify code;
    :Execute BDD and Unit tests;
repeat while (test fail?)

:Push code changes to Git;

|Jenkins|
:Start Continuous Integration;

if (All test pass?) then (yes)
else
    :Raise Issue;
    stop
endif

:Create Packages;
:Push to Package Repository;

end
@enduml
