{
  "sha1": "c4mhomrnxh4194z9gga3x1z116n7msn",
  "insertion": {
    "when": "2024-06-01T09:03:00.885Z",
    "url": "https://github.com/plantuml/plantuml/issues/1405",
    "user": "plantuml@gmail.com"
  }
}
@startuml
note as n
    my note
end note

package X {
    note as n
        my enother note
    end note
}
@enduml
