{
  "sha1": "l4ty5eq13b58jaru01vpxkz76pcx8b0",
  "insertion": {
    "when": "2024-06-03T18:59:33.702Z",
    "url": "http://forum.plantuml.net/9260/gantt-support-initial-separator",
    "user": "plantuml@gmail.com"
  }
}
@startgantt

-- Initialization --

[Config Routing Fabric] as [cfg_rte] lasts 73 days
[Init Counters] as [cfg_ctr] lasts 4 days
[Init Decay Ctr] as [cfg_dec] lasts 1 days
[cfg_rte] -> [cfg_ctr]
[cfg_ctr] -> [cfg_dec]

-- Run Time --

[foo] lasts 3 days
then [bar] lasts 5 days

@endgantt
