{
  "sha1": "28davy4niu1at9hcy9mifvi0usfelux",
  "insertion": {
    "when": "2024-05-30T20:48:19.930Z",
    "url": "https://forum.plantuml.net/11776/shape-issue-on-stack-element-deployement-diagram-on-v1-2020",
    "user": "plantuml@gmail.com"
  }
}
@startuml
scale 2
skinparam BackgroundColor pink
title Shape Stack **K0**
stack stack1
stack stack {
}
stack1--stack
@enduml
