{
  "sha1": "mhvlwtypxorihn2ls83gj0gmr6jc6qh",
  "insertion": {
    "when": "2024-06-03T18:59:35.277Z",
    "url": "https://github.com/plantuml/plantuml/issues/1096",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true
& A -> B
@enduml
