{
  "sha1": "opvrs6ysjt5l3nj0tuexnvs1th6gag6",
  "insertion": {
    "when": "2024-06-04T17:28:40.100Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml

A0 -- A1
A0 -- A3

A1 -- A5
A2 -- A4

note right of A1 : right
note left of A4 : left

@enduml
