{
  "sha1": "hcdi7ua9v92hgz2xq1zplhu3h2p7frx",
  "insertion": {
    "when": "2024-06-03T18:59:29.453Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam lifelineStrategy nosolid
Bob -> Alice : hello
...
Alice -> Bob : ok
...dummy...
Alice -> Bob : ok2
...dummy\non\nseveral\nlines...
Alice -> Bob : ok3
@enduml
