{
  "sha1": "44h5tofqintilbcvvz94vflpzd3qlu6",
  "insertion": {
    "when": "2024-05-30T20:48:20.418Z",
    "url": "https://forum.plantuml.net/16630/wbs-diagram-hyperlinkunderline-false",
    "user": "plantuml@gmail.com"
  }
}
@startwbs

<style>
wbsDiagram {
  hyperlinkUnderlineThickness 0
  hyperlinkColor Red
  
  .pinkname {
      BackgroundColor pink
  }
}
</style>

* Software Project
**[#SkyBlue] Design
***: Build team
 - John (The database) [[https://dawkins.com Dawkins]]
 - Sally (The javascript) Marten
 - Fred (The Animal) Johnson; <<pinkname>>
*** Start detailed estimation

@endwbs
