{
  "sha1": "j44ap6t4nxvgu07s5d63ile5gkrlnhk",
  "insertion": {
    "when": "2024-06-03T18:59:31.464Z",
    "url": "https://forum.plantuml.net/15577/gantt-with-weekly-scale-bugs",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
'ganttscale weekly
'Project starts the 2022/05/02
[Task1] on {Alice} lasts 10 days
[Task2] on {Bob:50%} lasts 20 days
then [Task3] on {Alice:25%} lasts 1 days
@endgantt
