{
  "sha1": "rhpqoit5fgdelxyejzk51jkylip94ij",
  "insertion": {
    "when": "2024-06-04T17:28:43.838Z",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] lasts 13 days
[Test prototype] lasts 4 days
[Test prototype] starts 3 days before [Prototype design]'s end
@endgantt
