{
  "sha1": "fplhwx82ngfubaj0li8qriaz3ngdb0c",
  "insertion": {
    "when": "2024-06-01T09:03:06.461Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
if(this%n()test%n()is%n()long) then
    :Activity1;
elseif() then(I would like to write%n()a long text here%n()on several lines%n()without getting over%n()the Activity box)
    :Activity2;
    :Activity3;
elseif() then(I would like to write%n()a long text here%n()on several lines%n()without getting over%n()the Activity box)
    :Activity4;
    :Activity5;
else
:Activity6;
endif
stop
@enduml
