{
  "sha1": "6um717jkig7vfueql3bkhkzrm3rcent",
  "insertion": {
    "when": "2025-04-07T15:00:17.556Z",
    "url": "https://github.com/plantuml/plantuml/issues/2148",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Observation  {
name 0
name 1 [[[https://example.com/link1]]]
name 2
name 3 [[[https://example.com/link3]]]
}
url of Observation is [[https://example.com/link2]]
@enduml
