{
  "sha1": "lrg3fwtzm7jlktzoaoha6mfys1kiemx",
  "insertion": {
    "when": "2024-06-03T18:59:34.464Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "nekote-79-pori818"
}
@startuml
usecase sameid
rectangle sameid
@enduml
