{
  "sha1": "8tczda08mk03jl5ic1fbmdpli9ihgpa",
  "humhash": "favexi-85-dipi032",
  "insertion": {
    "when": "2026-06-08T22:13:35.371Z",
    "url": "https://github.com/plantuml/plantuml/issues/2690",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class A {
{{regex
title someRegex
^\s*(\d{4,5}-?\d{3,4}-?\d{1,2})
}}
}
@enduml
