{
  "sha1": "2jar7wt7mez4ucx0v2rcd9kp69mw51o",
  "insertion": {
    "when": "2024-05-30T20:48:20.018Z",
    "url": "https://forum.plantuml.net/14563/style-object-allow-style-on-object-diagram",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
root {
  FontColor Red
  BackgroundColor palegreen
}
objectDiagram {
  object {
	  FontColor blue
	  BackgroundColor yellow
  }
}
</style>

object o1
object user {
  name = "Dummy"
  id = 123
}

o1  -> user
@enduml
