{
  "sha1": "rk14kla1ievq11jgv406bmdm6g5r7du",
  "insertion": {
    "when": "2024-06-04T17:28:43.907Z",
    "url": "http://forum.plantuml.net/7708/formatting-options-inside-%40startmath-%40endmath",
    "user": "plantuml@gmail.com"
  }
}
@startmath
scale 5
color red
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
