{
  "sha1": "453cx09a6ukuicokxa4rlptkfo8v7d7",
  "insertion": {
    "when": "2024-05-30T20:48:20.426Z",
    "url": "https://forum.plantuml.net/17019/prevent-wrap-for-comma-dot-etc",
    "user": "plantuml@gmail.com"
  }
}
@startuml

set separator none

skinparam {
  wrapWidth 200
  maxMessageSize 100
}

rectangle "blabla //blabla// blabla blabla //blabla//, les //blabla// et les //blabla//, les //blabla//, les //blabla// et les //blabla//."
@enduml
