{
  "sha1": "dvigarmtnx9k11zmbqek7vmdt8closk",
  "insertion": {
    "when": "2024-06-01T09:03:03.481Z",
    "url": "https://forum.plantuml.net/16188/gantt-closed-days-arent-ignored-when-delaying-tasks",
    "user": "plantuml@gmail.com"
  }
}
@startgantt

saturday are closed
sunday are closed
2022-07-04 to 2022-07-15 is closed

Project starts 2022-06-27
[task1] starts at 2022-06-27 and lasts 1 week
[task2] starts 2 working days after [task1]'s end and lasts 3 days

@endgantt
