{
  "sha1": "dvv9bz06kv4tel2quizszdcxt84kags",
  "insertion": {
    "when": "2024-06-01T09:03:03.510Z",
    "url": "https://forum.plantuml.net/15211/question-related-working-with-resources-feature-gantt-charts",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
hide ressources names
[Task1] on {Alice} lasts 10 days
[Task2] on {Bob:50%} lasts 2 days
then [Task3] on {Alice:25%} lasts 1 days
@endgantt
