{
  "sha1": "j2wf6tna6fxd1bzdxehqc6mm04jf94u",
  "insertion": {
    "when": "2024-06-03T18:59:31.408Z",
    "url": "http://wiki.plantuml.net/site/style-evolution",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true

<style>
arrow {
    FontColor red
    LineColor blue
  }
</style>

participant Alice

participant Bob
Alice -> Bob : hello1

Alice -> Bob : hello2

@enduml
