{
  "sha1": "ls6la5kkx7zrqn4oqptft8gg91ptpqv",
  "insertion": {
    "when": "2024-06-03T18:59:34.492Z",
    "url": "https://github.com/plantuml/plantuml/issues/1348",
    "user": "plantuml@gmail.com"
  }
}
@startuml

class a {
    int i
}

note right of a
    note on a
end note


@enduml
