{
  "sha1": "lsr00bsdgc38tqf320vz8z2oxgrx89f",
  "insertion": {
    "when": "2024-06-03T18:59:34.499Z",
    "url": "https://forum.plantuml.net/17566/global-%24variable-default-variable-produces-error-a001",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!global $variable = "changed value"
!global $variable ?= "default value"
[A] -> [B]: $variable
@enduml
