{
  "sha1": "lst8n68yylhwq0dzettqolsj9s4eaax",
  "insertion": {
    "when": "2024-06-03T18:59:34.516Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
usecase foo #orange;line:blue
(dummy) #orange;line:yellow
@enduml
