{
  "sha1": "n20dvb274v7k66s5o2so7k9n8gxg5tq",
  "insertion": {
    "when": "2024-06-01T09:03:07.211Z",
    "url": "https://forum.plantuml.net/10676/repeat-plus-colour",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:A;
repeat:B; <<task>>
repeat while (C)
:D; <<task>>
@enduml
