{
  "sha1": "tghm0gc1ufn55p268979e8q2m4wm8ex",
  "insertion": {
    "when": "2024-06-04T17:28:46.188Z",
    "user": "plantuml@gmail.com"
  }
}
@startproject
close sunday
close saturday


^X0 := 05-APR-2011
^X1 := 15-NOV-2011
^X2 := ^X1 + 60
^GL := 14-DEC-2012

~DEV1$capacity := 1
~DEV2$capacity := 1


@endproject
