{
  "sha1": "tglts6a7v66oddmh2kizpwac7pyqaeg",
  "insertion": {
    "when": "2024-06-04T17:28:46.208Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam useBetaStyle true
<style>
participant {
  BackgroundColor AntiqueWhite/Gold
  clickable {
     BackgroundColor red
     LineColor green
  }
}
</style>

participant Alice
participant Bob [[foo]]
Alice -> Bob : hello
'url of Bob is [[foo]]

@enduml
