{
  "sha1": "te236uhmuz2wlw2bflipeoc1gs01rpp",
  "insertion": {
    "when": "2024-06-04T17:28:46.087Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:<size:12>https://www.qwant.com/?r=FR&sr=fr&l=fr_fr&h=0&s=0&a=1&b=1&hc=1&smartNews=1&smartVideos=1&smartSocial=1&theme=0&i=1&client=brz-vivaldi&q=%s;
:<size:14>https://www.qwant.com/?r=FR&sr=fr&l=fr_fr&h=0&s=0&a=1&b=1&hc=1&smartNews=1&smartVideos=1&smartSocial=1&theme=0&i=1&client=brz-vivaldi&q=%s;
@enduml
