{
  "sha1": "te511k1alpl4yrtqs6duoeporhaiuw6",
  "insertion": {
    "when": "2025-09-25T19:50:52.748Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
* R
** Line 1
***(l1) L11
** Line 2
***[#green](z)_< L21
***[#pink](l2)< L22

l2 -> l1
@endwbs
