{
  "sha1": "ch4f8fx2ob1f89ge3zxg0op35emjft7",
  "insertion": {
    "when": "2024-06-01T09:03:01.414Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
!theme hacker
* 'Head'
** 'Branch One'
** 'Branch Two'
** 'Branch Three'
** 'Branch Five'
*** 'Subbranch Five-One'
@endwbs
