{
  "sha1": "chtia5qsos85s77f4e3n5lduku87trj",
  "insertion": {
    "when": "2024-06-11T19:48:28.963Z",
    "url": "https://github.com/plantuml/plantuml/issues/1809",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
[Prototype design] as [D] requires 15 days
[Test prototype] as [T] requires 10 days
[T] starts at [D]'s end
[Test prototype] as [Z] requires 3 days
@endgantt
