{
  "sha1": "ikkxegq7wet4za7m5kxv1tgkvpauidn",
  "insertion": {
    "when": "2024-06-03T18:59:30.835Z",
    "url": "https://forum.plantuml.net/13837/crash-when-using-%40startnwdiag?show=13841#c13841",
    "user": "plantuml@gmail.com"
  }
}
@startnwdiag

  vlan1 [shape = cloud];

  network vlan1{
    address = "192.168.168.0/24"

    vlan1;
    Switch4;
  }

  network {
    Switch4 [address = "port1/04"];
    Device1 [address = "192.168.168.1"];
  }
@endnwdiag
