{
  "sha1": "ck9k46367cfyxzalj0yyb1dkdg97dfa",
  "insertion": {
    "when": "2024-06-01T09:03:01.580Z",
    "url": "https://photos.app.goo.gl/FfSh5nystMQYh26V9",
    "user": "plantuml@gmail.com"
  }
}
@startuml

skinparam node {
    StereotypeFontSize 20
}

node node1 <<foo>>


@enduml
