{
  "sha1": "sk241hd37mw7pgb4jf7a1fwyrpeyk0l",
  "insertion": {
    "when": "2024-06-03T18:59:35.431Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
hide footbox

participant "Bob on%n()several lines" as Bob
actor Alice

Bob -> Alice : hello
note right of Alice
  this is a note
end note

Alice -> Bob : Is it ok%n()with a message that is%n()on several lines?

note right
  This other note
  should work
  on several lines
end note

== This is a separation ==

Bob -> Last : Yes it works!
Last -> Last : working in progress
note right : this is%n()another note

Last --> Last : working in progress
Last --> Bob : done

@enduml
