{
  "sha1": "skmgkwoi68opkophrqvobgbhcokreus",
  "insertion": {
    "when": "2024-06-04T17:28:45.220Z",
    "url": "https://forum.plantuml.net/13824/getting-unsupportedoperation-when-adding-stop-and-end-case",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
title Number Analysis
switch (source)

case ( a )
:case1;
end

case ( b )
:case2;

case ( c )
:case3;

endswitch
@enduml
