{
  "sha1": "4fqaw1alzkrko5yz1y57hssx0hfwmhc",
  "insertion": {
    "when": "2024-05-30T20:48:20.482Z",
    "url": "https://redfin.engineering/visualize-merge-history-with-git-log-graph-first-parent-and-no-merges-c6a9b5ff109c",
    "user": "plantuml@gmail.com"
  }
}
@startgit
*-.---------------.   2d2a6c2 (HEAD -> master) merge
|\ \              |  
| | |             * arnaud
| | * 2300c18 2 
| * | 7e096cb 1
| |/  
* | 50aa125 3
|/  
* a1e94fd root
@endgit
