{
  "sha1": "aeqdo3hzbnx9zvqzmx8sghknsymv5gn",
  "insertion": {
    "when": "2024-05-30T20:48:21.866Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "giduve-36-xuvo448"
}
@startjson
42
@endjson
