{
  "sha1": "984q9youtleqn9d7th0e2d65q0iq3g7",
  "insertion": {
    "when": "2024-05-30T20:48:21.630Z",
    "url": "http://forum.plantuml.net/7859/partition-are-compacted-distributed-over-multiple-swinlane",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|p1|
start
if (foo) then
:on p3;
note right
this is a long text note to have much bigger size on p3
end note
if (foo2) then
|p2|
:d1;
note right
this is a long text note to have much bigger size on p3
end note
|p1|
else
:d2;
endif

else
|p2|
:on p1;
|p1|
endif

@enduml
