{
  "sha1": "4vgcgcqv3fojdn98j5ioo00az1cp7tt",
  "insertion": {
    "when": "2024-05-30T20:48:20.590Z",
    "url": "https://forum.plantuml.net/16694/ebnf-add-notes",
    "user": "plantuml@gmail.com"
  }
}
@startebnf
title Test on comments

test_above_below_first = z (*this is a xcomment%n()below z*);
@endebnf
