{
  "sha1": "b34tqkndi8qan5iz1vad542652ka9la",
  "insertion": {
    "when": "2024-05-30T20:48:22.002Z",
    "url": "https://forum.plantuml.net/12663/ability-to-manage-several-groups-on-same-network-in-nwdiag?show=12663#q12663",
    "user": "plantuml@gmail.com"
  }
}
@startnwdiag
nwdiag {
  group {
    color = "#FF7777";
    web01;
    db01;
  }
  group {
    color = "#7777FF";
    web02;
    db02;
  }
  network dmz {
      web01;
      web02;
  }
  network internal {
      web01;
      web02;
      db01 ;
      db02 ;
  }
}
@endnwdiag
