{
  "sha1": "b3n3fgv11vpd3rs3r80cvu4iladcods",
  "insertion": {
    "when": "2024-05-30T20:48:22.006Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
partition "Empty partition" {
#FBFB77:Can the partition be centered%n()and the note be over the activity arrow; <<task>>
}
stop
@enduml
