{
  "sha1": "b3n3fgv11vpd3rs3r80cvu4iladcods",
  "insertion": {
    "when": "2024-06-04T17:28:41.111Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
partition "Empty partition" {
:Can the partition be centered\nand the note be over the activity arrow; <<task>> <<#FBFB77>>
}
stop
@enduml
