{
  "sha1": "jpgte6nndexb9wxdclg207f8fn7xpqs",
  "insertion": {
    "when": "2024-06-03T18:59:32.076Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
state "Some State" as A_State {
	state "Task" as Task1
	||
	state "Task" as Task2
	state ExitSuccessful <<exitPoint>>
    state ExitFailure <<exitPoint>>

}
@enduml
