{
  "sha1": "3wfgu9lz42v0sgenm12lis3u8gce9qf",
  "insertion": {
    "when": "2024-07-14T08:38:20.301Z",
    "url": "https://github.com/plantuml/plantuml/issues/1855",
    "user": "plantuml@gmail.com"
  }
}
@startuml
sprite AA <svg xmlns="http://www.w3.org/2000/svg" width="90" height="90">
  <g fill="#FF0000" font-size="30pt">
    <text x="5" y="30" font-family="Consolas" >A</text>
    <text x="30" style="fill:#00FF00;" y="30">A</text>
  </g>
</svg>
title <$AA>
@enduml
