{
  "sha1": "t9plq5hdq5zjda4cpnji1hyqro97ok",
  "insertion": {
    "when": "2026-01-16T18:16:52.094Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
:A;
repeat :foo; <<#red>>
:D;
repeat while (C) <<#blue>>
:D;
@enduml
