{
  "sha1": "pf48650vycukrmwictrp7rgmes36b8d",
  "insertion": {
    "when": "2024-06-04T17:28:41.104Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
participant Bob
participant Alice

Bob->Alice: c3
note right: toto1

note right of Alice: toto2 

activate Alice
@enduml
