{
  "sha1": "bu5bsfomo06fypqoputxudehjue7eep",
  "insertion": {
    "when": "2024-05-30T20:48:22.162Z",
    "url": "https://forum.plantuml.net/16147/the-horizontal-alignment-style-does-not-work-correctly",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
+ Qwerty
++ Ytrewq%n()poiuytrewq<<s1>>
+++ Mnbvcx

@endmindmap
