{
  "sha1": "9d8y4om7ttmdvsg69999g3rvyj9lglr",
  "insertion": {
    "when": "2024-05-30T20:48:21.654Z",
    "url": "https://forum.plantuml.net/13888/preprocessing-expose-builtin-functions-reverse-function",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
!$title_color = "#012345"
title {
  BackGroundColor $title_color
  FontColor %reverse_hsluv_color($title_color)
}
</style>
title
this is a title
endtitle
alice->bob
@enduml
