{
  "sha1": "pmtttyef8a22xo9scvcdznzwoyhaq0b",
  "insertion": {
    "when": "2024-05-30T20:48:22.102Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
#lightblue:Action; <<procedure>>
-[#blue]-> callback;
if () then (OK)
-[#black]->
else if () then (ERROR)
  -[#red]->
   #lightpink:ERROR; <<task>>
   stop
else (timeout)
  -[#green]->
   #lightpink:TIMEOUT; <<task>>
   stop
endif
-[#yellow]->
end
@enduml
