{
  "sha1": "akgms7dnbsuyyzg8ay237jjudxykjv3",
  "insertion": {
    "when": "2024-05-30T20:48:21.894Z",
    "url": "http://forum.plantuml.net/6495/wrong-class-widths-after-latex-export",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam tikzFont 0.8;4.5
participant "I have a really" as A
participant "long name" as B
participant "I have a really%n()long name" as C

@enduml
