{
  "sha1": "8f59mio7jeoh17qkquk4mhmjcdxj4fn",
  "insertion": {
    "when": "2024-05-30T20:48:21.406Z",
    "url": "https://forum.plantuml.net/13245/skinparam-arrowcolor-cannot-combined-multiple-stereotypes",
    "user": "plantuml@gmail.com"
  }
}
@startuml
<style>
arrow {
  LineColor #Green
  FontColor #Green
  LineStyle 10-5
  
  .va {
  	FontColor #Red
  }
  .vb {
  	LineColor #Red
  }

}
</style>

[Component]

Component --> Participant10<<va>> : va stereotype
Component --> Participant20<<vb>> : vb stereotype
Component --> Participant30<<va>><<vb>> : va and vb stereotype

@enduml
