{
  "sha1": "kzevbib57odttmtcer9jjny0y7rf13n",
  "insertion": {
    "when": "2024-06-03T18:59:33.499Z",
    "url": "https://github.com/plantuml/plantuml/issues/1058#issuecomment-1385261883",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma svek_trace on
node {
 [c]
 portout p
}

c -> p : <color:red>label not shown
@enduml
