{
  "sha1": "l0djv465xw1y9unihiewgan49n290d2",
  "insertion": {
    "when": "2024-06-03T18:59:33.520Z",
    "user": "plantuml@gmail.com"
  }
}
@startsalt
{
Window Title
---
Section Header
===
{/ Tab 1
Tab 2
Tab 3
}
}
@endsalt
