{
  "sha1": "l0l11v9a6roe5v2d6hjvwt9xe8r97bh",
  "insertion": {
    "when": "2024-06-03T18:59:33.527Z",
    "url": "https://github.com/plantuml/plantuml/issues/23#issuecomment-646933577",
    "user": "plantuml@gmail.com"
  }
}
@startuml
activate a
a -> a : put
deactivate actor
@enduml
