{
  "sha1": "hjrt7zqdwtewx2uckanzb0jhytrj0qu",
  "insertion": {
    "when": "2024-06-03T18:59:29.660Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
start
:Bind;
fork
  repeat
    :Listen admin;<<input>>
    :Execute;
    :Reply admin;<<output>>
  repeat while (shutdown>) is (no)
fork again
  repeat
    :Listen user<;
    :Reply user;<<output>>
  repeat while (forever)
  detach
endfork
:Release;

@enduml
