{
  "sha1": "hjvo0opsf0ov6g6satdu6ew4fo5o4u4",
  "insertion": {
    "when": "2024-06-03T18:59:29.253Z",
    "url": "https://forum.plantuml.net/9660/legend-comes-on-top-of-title-when-having-large-header",
    "user": "plantuml@gmail.com"
  }
}
@startuml
title
Some Title
end title

right header
<size:16>Generated date</size>
end header

legend top
Some legend.
end legend

A -> B
@enduml
