{
  "sha1": "9b96r2ltf9ngc9hie7kak65q7n28dnv",
  "insertion": {
    "when": "2026-02-18T18:13:55.533Z",
    "url": "https://github.com/plantuml/plantuml/issues/2162",
    "user": "plantuml@gmail.com"
  }
}
@startuml
X -> X
destroy Y
@enduml
