{
  "sha1": "8vjveirp06ehtax0qyjbz6aehuz0lsf",
  "insertion": {
    "when": "2026-03-01T21:48:16.752Z",
    "user": "plantuml@gmail.com"
  }
}
@startchart
h-axis 0 --> 100
v-axis 0 --> 100 grid
scatter [(10,45), (25,62), (40,58), (55,70)] #3498db
@endchart
