{
  "sha1": "26qyx3x8i6aul2q2o2skuzunyixs5ij",
  "insertion": {
    "when": "2024-05-30T20:48:19.914Z",
    "url": "http://forum.plantuml.net/8945/skinparam-wrapwidth-brake-line-incorrectly",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam wrapWidth 300
'a -> b : init
'note over a 
'long text1 long text2 long text3 long text4 long text5 long text6 long text7 long text8 long text9 long text10
'end note
a <- b : ack
note over a 
long text1 long text2 long text3 long text4 long text5 long text6 <color #red>foo1 foo2</color> text7 long text8 long text9 long text10
end note
@enduml
