{
  "sha1": "26xu7fp7dqbr366pp3q5c9jsbw992t",
  "insertion": {
    "when": "2024-05-30T20:48:19.914Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
Class01 <|-- Class02
Class03 *-- Class04
Class04b --* Class03b
Class05 o-- Class06
Class06b --o Class05b
Class07 .. Class08
Class09 -- Class10
Class11 <|.. Class12
Class13 --> Class14
Class15 <.. Class16
Class17 ..|> Class18
Class19 <--* Class20
@enduml
