{
  "sha1": "sx541icw4082uhbxg5ukbz6y7zimla2",
  "insertion": {
    "when": "2024-06-04T17:28:45.583Z",
    "url": "https://forum.plantuml.net/4834/activation-shorthand-for-sequence-diagrams?show=12981#c12981",
    "user": "plantuml@gmail.com"
  }
}
@startuml
alice -> bob ++ : hello1
bob -> charlie --++ : hello2
charlie --> alice -- : ok

@enduml
