{
  "sha1": "lwysg6heo2p3fkiykrjxhhy8hu2i85v",
  "insertion": {
    "when": "2024-06-03T18:59:34.607Z",
    "url": "https://forum.plantuml.net/17187/verticals-separators-gantt-chart-appear-certain-conditions?show=18171#c18171",
    "user": "plantuml@gmail.com"
  }
}
@startgantt
Project starts 2022-12-01
projectscale weekly zoom 10

[task1] lasts 1 week
[task2] starts 20 days after [task1]'s end and lasts 3 days

Separator just at [task1]'s end
Separator just 2 days after [task1]'s end

@endgantt
