{
  "sha1": "rr17oxw8dox6xruzs03zamhe6z5wkrz",
  "insertion": {
    "when": "2024-06-04T17:28:44.176Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class cl1
class cl2
class cl3
class cl4
cl1 -- cl2 : this is%n()on several%n()lines
cl2 -- cl3 : this is%left_align()on several%left_align()lines
cl3 -- cl4 : this is%right_align()on several%right_align()lines
@enduml
