{
  "sha1": "djutlzhv0jr5t1rcxtbcsl9oceydt4k",
  "insertion": {
    "when": "2024-06-01T09:03:03.094Z",
    "url": "https://github.com/plantuml/plantuml/issues/255",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam NoteBackgroundColor green
skinparam NoteFontColor red
skinparam NoteFontSize 30
skinparam NoteBackgroundColor<<test>> yellow
skinparam NoteFontColor<<test>> blue
skinparam NoteFontSize<<test>> 50

Bob -> Alice : hello
note over Bob: test note 1
note<<test>> over Bob: test note 2
@enduml
