{
  "sha1": "iyv3vczqx080olj2t8lnbswc92rrbut",
  "insertion": {
    "when": "2024-06-03T18:59:31.329Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam dpi 300
:ac: --> (uc)
:ac1: --> (uc)
:ac2: --> (uc)
@enduml
