{
  "sha1": "rvhmosioforb9ru3ns5uain821iqkek",
  "insertion": {
    "when": "2024-06-04T17:28:44.294Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
class Short
Short: this is a very long text for testing the size
@enduml
