{
  "sha1": "rvhuze2lne0ohodxu9qjedslsub97bj",
  "insertion": {
    "when": "2024-11-08T10:07:54.467Z",
    "url": "https://github.com/plantuml/plantuml/issues/1952",
    "user": "The-Lum"
  }
}
@startuml
state 1.2
state a.b

1 -> b
@enduml
