{
  "sha1": "axmu991ofs7zdbnvxbv4waioxjaxm88",
  "insertion": {
    "when": "2024-09-09T14:56:50.970Z",
    "url": "https://github.com/plantuml/plantuml/pull/1900",
    "user": "The-Lum"
  }
}
@startjson
[]
@endjson
