{
  "sha1": "mjinshdlgn5k450077ms1kvs5bm3t1f",
  "insertion": {
    "when": "2024-06-03T18:59:35.326Z",
    "url": "https://github.com/plantuml/plantuml/issues/1023",
    "user": "plantuml@gmail.com"
  }
}
@startuml

!define AWS_BG_COLOR #FFFF00
!define AWS_BORDER_COLOR #FF9900

sprite $APIGateway [64x64/16z] {
xTC5biCm30JGiIfRqjp_lcMkqWqjUzuBvvlDjTFJ4uqlQJ5QA-1yYWCQOtNkan9IBTOotqoI4X9DvfvCIaZqi4zAIFImVrT2E-lt_bn2oxnpdAV_V2zIgG_7
D5-ASlDm_CZ-_tplDji7IIgSCSjRSP95wCLcUCF16ngzm2Rx4-S6mMC1Ktqv3G4s9r2c-We9ii98Xg1EzJmMKCgPSx9dXJagIKFb34-ddjuvPta6PDdwTP_d
-_ut3yRzOTCye9I7OvhNQcptXtxa-_n1ROmtHURP1ESYXlmPGnhJH1MWg0rvqm98ZOG-5Y6PbmHdyIf8_04xnyMpyNMkdPwU7G
}

<style>
participant {
    BackgroundColor AWS_BG_COLOR
    LineColor AWS_BORDER_COLOR
}
.APIGateway {
  ShowStereotype false
}
</style>


actor User as user
participant OnlyLabel as p1 << APIGateway >>
participant BothZWSP as p4 << ($APIGateway, #CC2264) APIGateway >>

user -> p4: renders as expected
@enduml
