{
  "sha1": "mjt9a87ei5c6p4azikextba87e49dfr",
  "insertion": {
    "when": "2024-06-03T18:59:35.333Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
    start
    if(foo) <<#green>>
    :...;
    elseif(bar) <<#red>>
    :...;
    else
    :..;
    endif
    stop

    start
    if(foo)
    :...;
    elseif(bar) <<#red>>
    :...;
    else
    :..;
    endif
    stop
@enduml
