{
  "sha1": "der7hkfbw8r2v3o2qw1ki7xbmtkabt1",
  "insertion": {
    "when": "2024-06-01T09:03:02.904Z",
    "user": "plantuml@gmail.com"
  },
  "humhash": "zubevi-64-fume582"
}
@startuml
class MyClass<S extends SomeClass,\nA extends AnotherClass,\nY YetAnotherClass> {
}
@enduml
