{
  "sha1": "fadrzc8z4e7naxm5146iupqk9vur3mw",
  "insertion": {
    "when": "2024-06-01T09:03:05.842Z",
    "url": "https://forum.plantuml.net/16985/center-aligned-text-not-in-the-middle-of-a-node",
    "user": "plantuml@gmail.com"
  }
}
@startmindmap
skinparam DefaultTextAlignment center
<style>
node {
  HorizontalAlignment center
  MaximumWidth 250
  MinimumWidth 250
}
</style>
* Root\nThis text is centered\nbut not in the middle
** Node\nThis text is centered\nbut not in the middle either
@endmindmap
