{
  "sha1": "fazeendr60gvn2ischruahtdeljsfhn",
  "insertion": {
    "when": "2024-06-01T09:03:05.880Z",
    "url": "https://forum.plantuml.net/16980/%25substr-%24variable-does-not-work-strings-are-added-same-line",
    "user": "plantuml@gmail.com"
  }
}
@startuml
legend
!$labelWithDetails = "Customer\nPeople that need products"
!$brPos = %strpos($labelWithDetails, "\n")
!$line = %substr($labelWithDetails, 0, $brPos) + " <color:gray>A" + %substr($labelWithDetails, $brPos + 2) + "B</color>"
$line
endlegend
@enduml
