{
  "sha1": "91ob4qw99i2qaqrezr242yahpjfmdui",
  "insertion": {
    "when": "2026-03-01T21:48:16.747Z",
    "user": "plantuml@gmail.com"
  }
}
@startchart
h-axis [Q1, Q2, Q3, Q4]
v-axis "Revenue ($K)" 0 --> 100 label-top
bar "Sales" [45, 62, 58, 70] #3498db
@endchart
