{
  "sha1": "d84cyth40kvszbyuu107eygphglu5a6",
  "insertion": {
    "when": "2024-06-01T09:03:02.672Z",
    "url": "https://forum.plantuml.net/16588/style-allow-all-style-for-mainframe",
    "user": "plantuml@gmail.com"
  }
}
@startuml

legend
The legend
end legend

a -- bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb

@enduml
