{
  "sha1": "kfjrbou8loyaawyjeizqfae2rkinr3z",
  "insertion": {
    "when": "2024-06-03T18:59:32.943Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
interface A1
interface A2
class B1 extends P implements A1 {
}
class B2 extends P implements A1,A2 {
}
class C1 {
+test : void()
}
class C2 {
+test : void()
}
class P {
}
B1 -() A1
B2 -() A1
B2 -() A2
A1 )-- C1
A2 )-- A2
A2 )--( A1
@enduml
