{
  "sha1": "c8pqw1cepdtk1r3sf55oeam5t4y6ejm",
  "insertion": {
    "when": "2024-06-01T09:03:01.077Z",
    "user": "plantuml@gmail.com"
  }
}
@startwbs
<style>
wbsDiagram {
  root {
    BackgroundColor yellow
    FontColor blue
    LineColor red
    LineThickness 1
    Margin 10
    Padding 6
    Shadowing 0.0
  }
  element {
    BackgroundColor red
  }
}
</style>
* Business Process Modelling WBS
** Launch the project
*** Complete Stakeholder Research
*** Initial Implementation Plan
** Design phase
*** Model of AsIs Processes Completed
**** Model of AsIs Processes Completed1
**** Model of AsIs Processes Completed2
*** Measure AsIs performance metrics
*** Identify Quick Wins
** Complete innovate phase
@endwbs
