{
  "sha1": "1ggg2u7o8yogc1ktsns6zm8pkds4moh",
  "insertion": {
    "when": "2024-05-30T20:48:19.674Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma teoz true

participant "party 1" as P1
participant "party 2" as P2


group inner1
P1->P2: select and make the diagram bigger in width so the note over both break
note over P1,P2
 if here is some note over both parties
end note
end

group inner2
P1->P2: short
note over P1,P2
 if here is some note over both parties
end note
end

@enduml
