{
  "sha1": "eh8kt1uw1u20d46vm5e3wnfoh75ppyy",
  "insertion": {
    "when": "2024-06-01T09:03:04.453Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
|S0|
start
|S1|
|S2 with a very long title|
|S2bsfdmlkjfdslkdsflkjsfdlksdlkfjis|
:df S2bsfdmlkjfdslkdsflkjsfdlksdlkfjis S2bsfdmlkjfdslkdsflkjsfdlksdlkfjis;
|S3|
|S4|
|S1|
:decision;
split
if (foo)
:foo1verylong;
else
:d;
endif
split again
|S2 with a very long title|
:foo2 foo2;
split again
|S3|
:foo3 foo3;
end split
end
@enduml
