{
  "sha1": "ehe39nqpexfenld3ai72nh2tou7cely",
  "insertion": {
    "when": "2024-06-01T09:03:04.464Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam SwimlaneTitleFontColor red
skinparam SwimlaneTitleFontSize 8
skinparam SwimlaneBorderColor blue
skinparam SwimlaneBorderThickness 5
|lane1|
:foo;
|lane2|
:bar; 
@enduml
