{
  "sha1": "gvuxj4374hpkdjd9xhbxer0atau9ga4",
  "insertion": {
    "when": "2024-06-01T09:03:08.413Z",
    "url": "https://github.com/plantuml/plantuml/issues/104",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam wrapWidth 100
component component1 [
   this is a very long component description
]
note left
   this is a very long note that show be wrapped
end note
@enduml
