{
  "sha1": "d3z8bvtm0eykxxxjrh608d27ulc6mmr",
  "insertion": {
    "when": "2024-06-01T09:03:03.618Z",
    "url": "https://forum.plantuml.net/15919/overlapped-groups-in-nwdiag-throws-exception",
    "user": "plantuml@gmail.com"
  },
  "humhash": "latave-579-gonaci"
}
@startnwdiag

nwdiag {
	group {
		color = "pink";
		app;
		db;
	}
	
	group {
		color = "blue"
		router;
		db;
	}
	
	network line1 {
		router;
		app;	
	}
	
	network line2 {
		app;
		db;
	}

}

@endnwdiag
