{
  "sha1": "scoyxqmj55wa269596wzb4jt0nt7f53",
  "insertion": {
    "when": "2024-06-04T17:28:44.965Z",
    "user": "plantuml@gmail.com"
  }
}
@startuml
skinparam CircledCharacterFontSize 18
class Toto
@enduml
