{
  "sha1": "2xx6ur1thc9x38v9pyysusnj04ultzi",
  "humhash": "lovasa-21-fito292",
  "insertion": {
    "when": "2026-07-25T16:32:32.604Z",
    "url": "https://github.com/plantuml/plantuml/issues/1638",
    "user": "plantuml@gmail.com"
  }
}
@startuml
!pragma layout smetana
component "componentA:1.0.0" #FF7F50 {
component [javafx.base] 
component [javafx.controls] 
component [javafx.graphics] 
}
@enduml
